### ISSUE TITLE
SFM: Selection of initial pair can fail

### ISSUE THREAD

**Issue by simonfuhrmann** [simonfuhrmann/mve#123]
The selected initial pair can lead to tracks which are removed due to small triangulation angle.

**Comment by ajabri** [comment]
I'm trying to do a reconstruction with ~6300 images. I get many inlier matches, yet, the SFM reconstruction always seems to terminate very quickly, with only 6 points/features triangulated. Is the problem the initialization pair? Is there a way to try more than one (without doing it manually)? 

If I recall correctly in tools like VSFM more than one pair is tried?

**Comment by ajabri** [comment]
This happens even when I chose an initialization pair:
```
Using initial pair (4242,4259).
SSE2 accelerated matching is enabled.
SSE3 accelerated matching is disabled.
Initializing scene with 6313 views...
Initialized 6313 views (max ID is 6312), took 476989ms.
Loading pre-bundle from file...
Cleanup: Released 0 embeddings in 0 of 6313 views.
Computing feature tracks...
Propagating track IDs...
Removing tracks with conflicts... deleted 13559 tracks.
Colorizing tracks...
Created a total of 185597 tracks.
Using views 4242 and 4259 as initial pair.
Triangulated 0 new tracks, rejected 120 bad tracks.
  Rejected 120 tracks with unstable angle.
Running full bundle adjustment...
PBA: CPU double-precision solver; 40 cores.
Camera 4242, focal length: 640 -> 640, distortion: 0
Camera 4259, focal length: 640 -> 640, distortion: 0
SfM reconstruction finished.
SfM reconstruction took 5615 ms.
Creating bundle data structure...
Writing bundle (6313 cameras, 0 features): scenes/spelman.filt/synth_0.out...
Saving MVE view scenes/spelman.filt/views/view_4242.mve
Saving MVE view scenes/spelman.filt/views/view_4259.mve
Saving MVE view scenes/spelman.filt/views/view_5676.mve
Saving MVE view scenes/spelman.filt/views/view_6006.mve
```

**Comment by simonfuhrmann** [comment]
Automatic selection of the initial pair is still not properly solved. Right now, MVE will not try multiple initial pairs. But there are several parameters you can tweak so that it might succeed. 

Increase the homography threshold:
https://github.com/simonfuhrmann/mve/blob/master/apps/sfmrecon/sfmrecon.cc#L213

Reduce homography inlier percentage:
https://github.com/simonfuhrmann/mve/blob/master/apps/sfmrecon/sfmrecon.cc#L215

Reduce the triangulation angle (this is why your tracks get rejected):
https://github.com/simonfuhrmann/mve/blob/master/apps/sfmrecon/sfmrecon.cc#L253

You might also want to try to switch to MVE2 (the "mve2" branch) but note that you have to convert your dataset and a backup is recommended.

**Comment by ajabri** [comment]
Okay, I see, I will try what you suggested. One thing is that I did not have any EXIF metadata for focal length included. Could a bad focal length estimate cause the reconstruction to fail?

**Comment by simonfuhrmann** [comment]
Yes. If no focal length estimate can be obtained, it falls back to a default:
https://github.com/simonfuhrmann/mve/blob/mve2/libs/sfm/extract_focal_length.cc#L48

The default is `1.0` and is equivalent to a 35mm lens on a 35mm sensor, i.e., `35mm / 35mm = 1.0`. You can change the global default there, or you can provide a better default in the `camera.focal_length` field in `meta.ini` for each view, in combination with the `--intrinsics-from-views` option for `sfmrecon`.

**Comment by simonfuhrmann** [comment]
Initial pair search has been improved (commit 10c68eb4ee8a01c339a7416e6a9f6a6bee62ddb5) by considering the track triangulation angle.
