### ISSUE TITLE
Python Binding

### ISSUE THREAD

**Issue by davll** [simonfuhrmann/mve#131]
I've built a Python binding for MVE for my current researches relating to multi-view stereo.
[Link](https://github.com/davll/photometric-stereo/tree/python/mve)

Features:
- Scene, View, CameraInfo, ImageBase
- Works with Numpy, and therefore OpenCV
- One image class with multiple data type (thanks to mve::ImageBase)
- Get data as Numpy Array from image

Work in progress:
- Mesh & Triangle Mesh
- Bundle

As the work has already done (well, partially) and usable, probably merging it into main repo so it can benefit others as well

**Comment by simonfuhrmann** [comment]
The repo has been linked from the official website and the wiki.
