### ISSUE TITLE
Crash when clicking on "Scene inspect" or "SfM Reconstruct"

### ISSUE THREAD

**Issue by Maweypeyyu** [simonfuhrmann/mve#134]
Hi,

when starting the application and clicking on ''Scene inspect'' or ''SfM Reconstruct'' the program terminates with the log below. I am using Debian 64bit with up-to-date libraries (libqt5-dev, libpng12-dev, libtiff5-dev, libjpeg8-dev) . It doesn't matter if actual data are used or not. I've loaded some examples, same result.

		X Error: BadRequest (invalid request code or no such operation) 1
		  Extension:    154 (Uknown extension)
		  Minor opcode: 34 (Unknown request)
		  Resource id:  0x3a00004
		X Error: BadRequest (invalid request code or no such operation) 1
		  Extension:    154 (Uknown extension)
		  Minor opcode: 34 (Unknown request)
		  Resource id:  0x3a00021
		Resizing GL from 0x0 to 586x620
		Using OpenGL 3.3 ...
		Loading shaders from /home/m/Development/Research/mve/apps/umve/shaders/surface_330.*
		Error while loading shaders from /home/m/Development/Research/mve/apps/umve/shaders/.
		Qt has caught an exception thrown from an event handler. Throwing
		exceptions from an event handler is not supported in Qt. You must
		reimplement QApplication::notify() and catch all exceptions there.

		terminate called after throwing an instance of 'util::Exception'
		  what():  /home/m/Development/Research/mve/apps/umve/shaders/surface_330.vert: 0:1(15): preprocessor error: syntax error, unexpected IDENTIFIER, expecting NEWLINE

		Aborted

**Comment by flanggut** [comment]
Hi, seems like the shaders are not compiling on your system. Can you please check your OpenGL version?
    glxinfo | grep -i opengl

**Comment by Maweypeyyu** [comment]
Hi,

     OpenGL version string: 3.0 Mesa 8.0.5

Which version is needed at least?
thanks for the fast reply :)

**Comment by simonfuhrmann** [comment]
Hi,

I don't think this is related to UMVE directly. There seems to be a problem with your OpenGL drivers. In particular, the "X Error: BadRequest" indicates that there is an issue requesting a proper OpenGL context. The leads to a problem when compiling the shaders, but this is a secondary error.

It seems you are using Mesa, which may not support the required context. What graphics hardware are you using? Try the following command to find out: `lspci | grep VGA`.

Simon

**Comment by Maweypeyyu** [comment]
Oh, does it mean, that the driver is not used? I think it is installed as apt-get install xserver-xorg-video-intel package is there...

lspci output:

    00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)

Sorry, sounds like not being a issue related to the software.

**Comment by simonfuhrmann** [comment]
Well, I'm not sure what the exact problem is. However, your board seems pretty old. According to this article [1] there is no OpenGL 3 driver support Intels 2nd generation cards. It sounds like you will not be able to run UMVE, sorry.

I'm closing this ticket for now. If you find a way to get it running, keep us posted.

[1] http://en.wikipedia.org/wiki/List_of_Intel_graphics_processing_units
