### ISSUE TITLE
What algorithms is used to compute the dense stereo matching?

### ISSUE THREAD

**Issue by mojovski** [simonfuhrmann/mve#139]
I gave today MVE a try and received a nice point cloud 
http://ibin.co/1v1e680F7shK
from the fountain dataset (http://cvlabwww.epfl.ch/data/multiview/denseMVS.html)
However, I wonder if its possible to improve this by selecting a different dense matching method.
So I have basically two questions:

1. The applied "dmrecon" algorithm does not refere to some paper. Are there any details about the approach?

2. How can I replace this to compute 3D points in the mve-scene-format?

Thanks in advance!

**Comment by simonfuhrmann** [comment]
The implemented MVS algorithm is:
http://www.gris.informatik.tu-darmstadt.de/~mgoesele/download/Goesele-2007-MVS.pdf

For more information, check this page:
http://www.gris.informatik.tu-darmstadt.de/projects/multiview-environment/

You can implement any stereo you want and run it as an app. Use the MVE libraries to store depth maps into the views. Make sure you also try FSSR for surface reconstruction:
https://github.com/simonfuhrmann/fssr
