### ISSUE TITLE
How to compare results with the ground truth?

### ISSUE THREAD

**Issue by mojovski** [simonfuhrmann/mve#140]
Hi Simon,

I would like to compare the quality of the final 3D reconstruction result with a mesh based ground truth data like [this](http://cvlabwww.epfl.ch/data/multiview/denseMVS.html).
However, the 3D points provided do not have the same orientation nor scale. Thus, I cannot evaluate the vertex-based distance of the GT model and the result using the proposition from [Strecha](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=4587706&tag=1)

Is there a way to fix this without large effort?

PS: OpenMVG was used for BA.

Thank you very much in advance!

**Comment by simonfuhrmann** [comment]
This is unrelated to MVE and does not belong here. However, the proper way to do this is to use the camera information provided with Strecha's data sets and directly inject them in the MVE views. Since you need SfM points for MVS, this will not work "easily" as you have to generate SfM points yourself. Another way is to align the meshes using ICP.

**Comment by Meekohi** [comment]
@mojovski it is also reasonable to just run iterative closest points (ICP) to align the computed model to the ground truth, and then measure deviation based on that result. That is probably the quickest solution (MeshLab will do this for you, for example).

**Comment by mojovski** [comment]
ok icp is an option. Thank you!

by the way: what would I have to do in order to inject known (or approximately known) camera poses into the sfm module? I usually have precomputed poses from a SLAM system. Is this somehow supported?

**Comment by simonfuhrmann** [comment]
You can edit the views (views/*.mve) by hand, or use the API to set the camera parameters.
https://github.com/simonfuhrmann/mve/blob/master/libs/mve/view.h#L120
