### ISSUE TITLE
UMVE running issue 

### ISSUE THREAD

**Issue by amiltonwong** [simonfuhrmann/mve#142]
Dear all,

I had installed succesfully MVE and UMVE according to the following steps:
    # <download and untar>
    # cd mve
    # make
    # cd apps/umve/
    # qmake && make -j8
    # ./umve
After I open UMVE by command './umve', and I can see UMVE interface, but when I click 'scene inspect' tab or 'sfm reconstruct',  it blows out and the log is shown as follows:

=============================================================

root@milton-OptiPlex-760:~/Downloads/mve-master/apps/umve# ./umve 
X Error: GLXBadFBConfig 181
  Extension:    154 (Uknown extension)
  Minor opcode: 34 (Unknown request)
  Resource id:  0x4000004
X Error: GLXBadFBConfig 181
  Extension:    154 (Uknown extension)
  Minor opcode: 34 (Unknown request)
  Resource id:  0x4000020
Resizing GL from 0x0 to 585x641
Using OpenGL 3.3 ...
Loading shaders from /root/Downloads/mve-master/apps/umve/shaders/surface_330.*
Error while loading shaders from /root/Downloads/mve-master/apps/umve/shaders/.
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.

terminate called after throwing an instance of 'util::Exception'
  what():  /root/Downloads/mve-master/apps/umve/shaders/surface_330.vert: 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES

Aborted (core dumped)
root@milton-OptiPlex-760:~/Downloads/mve-master/apps/umve# 

====================================================

Could someone give me some suggestions to fix it?
(My system is Ubuntu 12.04 64bit, no GPU card installed)
I check my system  opengl version by following command,
'>> glxinfo | grep "OpenGL version"
OpenGL version string: 2.1 Mesa 10.1.3
Should I upgrade 2.1 into version 3.3  ??

Thanks in advance!
Milton

**Comment by simonfuhrmann** [comment]
You need at least OpenGL 3.3 with GLSL 3.3 to run UMVE. I am not sure if you can get it to work with Mesa.

**Comment by amiltonwong** [comment]
@simonfuhrmann ,
Would you mind telling me which version of linux you had installed UMVE successfully? Or is it necessary to equip with a nvidia gpu card?
