### ISSUE TITLE
UMVE Workflow

### ISSUE THREAD

**Issue by hellocatfood** [simonfuhrmann/mve#153]
I'm attempting to use UMVE but I'm having difficulty in knowing which steps to take. Is there a video or document available describing a complete workflow from start to finish?

**Comment by simonfuhrmann** [comment]
You should take a look at the Wiki
https://github.com/simonfuhrmann/mve/wiki
In particular, the User Guide
https://github.com/simonfuhrmann/mve/wiki/The-MVE-Users-Guide

Use UMVE only for inspection of the scene, and the command line tools for processing.
