### ISSUE TITLE
SFM: camera database improvements

### ISSUE THREAD

**Issue by keksberg** [simonfuhrmann/mve#156]
There is a wrong entry for the Olympus E-PL5 (https://github.com/simonfuhrmann/mve/blob/master/libs/sfm/camera_database.cc#L294) and the E-PL7 is missing in the database.
E-PL5 and E-PL7 have both a sensor size of 17.3 x 13 mm. The maximum resolution is 4608 x 3456. (However the real sensor resolution is a bit higher.)
```
this->add("OLYMPUS IMAGING CORP.", "E-PL5", 17.3f, 13.0f, 4608, 3456);
this->add("OLYMPUS IMAGING CORP.", "E-PL7", 17.3f, 13.0f, 4608, 3456);
```

**Comment by simonfuhrmann** [comment]
Pull Request?
