### ISSUE TITLE
UMVE: scanalyze feature wishlist

### ISSUE THREAD

**Issue by jackerma2012** [simonfuhrmann/mve#16]
Some features from scanalyze that I would like to see in UMVE (in no particular order):
1. Analyze line for depth
2. False color for mesh rendering
3. Switching between different navigation styles (fixed axis, free, camera vs. model, ...)
4. Specify mesh transform by hand
5. Clip mesh and save result
6. Diffuse/specular mesh shading
7. Dump Camera/Mesh info (position, bounding box, ...)
8. Registration through corresponding points
9. Visualize current rotation center

**Comment by simonfuhrmann** [comment]
Some of these features will never be implemented, others are already implemented. I'm closing this.
