### ISSUE TITLE
Wrong links to guides on homepage

### ISSUE THREAD

**Issue by ajabri** [simonfuhrmann/mve#163]
Just wanted to let you guys know, on homepage the guides are linked as

https://github.com/simonfuhrmann/mve/wiki/The-MVE-Users-Guide
https://github.com/simonfuhrmann/mve/wiki/The-MVE-Developers-Guide

instead of

https://github.com/simonfuhrmann/mve/wiki/MVE-Users-Guide
https://github.com/simonfuhrmann/mve/wiki/MVE-Developers-Guide

**Comment by simonfuhrmann** [comment]
On which website exactly? The `README.txt` in the old, almost deprecated, branch still has the old links. The `README.txt` in the `mve2` branch and the website should be up-to-date.

**Comment by ajabri** [comment]
I see, my mistake
