### ISSUE TITLE
using masks in scene2pset

### ISSUE THREAD

**Issue by lulu1315** [simonfuhrmann/mve#195]
hello , I'm trying to use masks in scene2pset with option -m
I created one channel(greyscale) mask.png in each view directory.white where I want to keep data black elsewhere

I'm using something like
scene2pset -ddepth-L0 -iundistorted -mmask -n -s -c mve/ mve/pset-L0.ply

but ...
Filtering points using silhouette masks...
Expected 1-channel mask for image "DSC_0617", skipping.
Expected 1-channel mask for image "DSC_0618", skipping.
Expected 1-channel mask for image "DSC_0619", skipping.
Expected 1-channel mask for image "DSC_0620", skipping.
Expected 1-channel mask for image "DSC_0621", skipping.
Expected 1-channel mask for image "DSC_0622", skipping.
Expected 1-channel mask for image "DSC_0623", skipping.
Expected 1-channel mask for image "DSC_0624", skipping.
Expected 1-channel mask for image "DSC_0625", skipping.

what am I doing wrong?
luc

**Comment by simonfuhrmann** [comment]
Just a wild guess, but you're not using a 1-channel mask?

**Comment by lulu1315** [comment]
I used gimp to draw the mask , set image mode to greyscale and save as png...

**Comment by simonfuhrmann** [comment]
Run `identify` on your mask please.

**Comment by lulu1315** [comment]
identify mask.png
mask.png PNG 3008x2000 3008x2000+0+0 8-bit DirectClass 24.3KB 0.000u 0:00.000

**Comment by simonfuhrmann** [comment]
`identify -verbose mask.png | grep -i color`

**Comment by lulu1315** [comment]
Colorspace: Gray
  Colors: 2
  Background color: graya(255,255,255,1)
  Border color: graya(223,223,223,1)
  Matte color: graya(189,189,189,1)
  Transparent color: graya(0,0,0,0)
    png:bKGD                 : chunk was found (see Background color, above)
    png:IHDR.color_type      : 4 (GrayAlpha)

**Comment by simonfuhrmann** [comment]
has alpha

**Comment by lulu1315** [comment]
ok sorry for the noise.. thanks anyway :)
