### ISSUE TITLE
Masking with different masks

### ISSUE THREAD

**Issue by aph3xtwin** [simonfuhrmann/mve#198]
Hello,

I've got 30 images
DSC01.jpg
...
DSC30.jpg

and their masks:
DSC01.png
...
DSC30.png

Masking needs to be done with scene2pset but how can that be done?
I'm trying scene2pset -mDSC01.png,DSC02.png etc but that does not work as the program doesn't seem to find the files.

Thanks!

**Comment by simonfuhrmann** [comment]
The masks need to be part of the views, i.e., copy the masks to a `mask.png` inside the views. Then use `scene2pset -mmask SCENE OUTPUT` to consider the masks.

**Comment by aph3xtwin** [comment]
Thanks. Is there any way to attach a mask to an image beforde doing scene2pset as it is inconvenient to identify every view/image-relationship and to copy the images by hand?

**Comment by simonfuhrmann** [comment]
Unfortunately, no. If you have many images, you will have to write a script that reads the original filename from `meta.ini` and copies the corresponding mask to the view. The use case so far has been to create the mask from within MVE, so this problem never occurred.

Feel free to re-open if you think there is something wrong. The mask feature is not regularly used.
