### ISSUE TITLE
How to use the UMVE in windows

### ISSUE THREAD

**Issue by SimFaris** [simonfuhrmann/mve#199]
This project is wonderful and I downloaded the software of windows' version, but I have no idea to handle the UMVE by the qt, so could you have the any manual to guide to use the software? thank you.

**Comment by simonfuhrmann** [comment]
https://github.com/simonfuhrmann/mve/wiki/MVE-Users-Guide

**Comment by simonfuhrmann** [comment]
Here is the users guide. Use UMVE on any existing scene (that may have been created with `makescene`.
https://github.com/simonfuhrmann/mve/wiki/MVE-Users-Guide
