### ISSUE TITLE
make error in OSX

### ISSUE THREAD

**Issue by andrew-davie** [simonfuhrmann/mve#201]
Tried to follow the build instructions for OSX, but when I get to 'make' in 'apps/umve' it gives the following...

viewinspect/scrollimage.cc:58:29: error: no member named 'scaled' in 'QSize'
    QSize newsize = imgsize.scaled(this->maximumViewportSize(),
                    ~~~~~~~ ^

Am I doing something wrong?
Thanks
A

**Comment by flanggut** [comment]
Hi Andrew,

I cannot reproduce your error. Can you please check if you have an up to date version of MVE (the current HEAD of the github repo), XCode and Qt?

    g++ --version : 
        Apple LLVM version 7.0.2 (clang-700.1.81)
    qmake --version: 
        QMake version 3.0 Using Qt version 5.5.1
    system_profiler SPSoftwareDataType: 
       System Version: OS X 10.11.2 (15C50)

Best,
-Fabian

**Comment by andrew-davie** [comment]
Thanks for the quick reply.
The problem was that qt5 is not fully installed by the given instructions.
Specifically… here’s my workflow (and fix)…

using instructions at
https://github.com/simonfuhrmann/mve/wiki/Build-Instructions-for-OS-X <https://github.com/simonfuhrmann/mve/wiki/Build-Instructions-for-OS-X>

CLT NOT installed on my machine
ran Xcode for first time then exited
then download http://adcdownload.apple.com/Developer_Tools/Command_Line_Tools_OS_X_10.11_for_Xcode_7.2/Command_Line_Tools_OS_X_10.11_for_Xcode_7.2.dmg <http://adcdownload.apple.com/Developer_Tools/Command_Line_Tools_OS_X_10.11_for_Xcode_7.2/Command_Line_Tools_OS_X_10.11_for_Xcode_7.2.dmg>
install
checked brew installed - yes already there
did ‘brew update’
Updated Homebrew from ff561606 to eea7220a.
brew install git libpng jpeg lib tiff qt5
Andrews-MacBook-Pro:kryten boo$ brew install git libpng jpeg libtiff qt5
Warning: jpeg-8d already installed
Warning: libtiff-4.0.6 already installed
==> Downloading https://homebrew.bintray.com/bottles/git-2.7.0.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring git-2.7.0.el_capitan.bottle.tar.gz
==> Caveats
The OS X keychain credential helper has been installed to:
  /usr/local/bin/git-credential-osxkeychain

The "contrib" directory has been installed to:
  /usr/local/share/git-core/contrib

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions

Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/git
==> Summary
🍺  /usr/local/Cellar/git/2.7.0: 1,407 files, 235.8M
Error: libpng-1.6.19 already installed
To install this version, first `brew unlink libpng`
==> Downloading https://homebrew.bintray.com/bottles/qt5-5.5.1_2.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring qt5-5.5.1_2.el_capitan.bottle.tar.gz
==> Caveats
We agreed to the Qt opensource license for you.
If this is unacceptable you should uninstall.

This formula is keg-only, which means it was not symlinked into /usr/local.

Qt 5 conflicts Qt 4 (which is currently much more widely used).

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/qt5/lib
    CPPFLAGS: -I/usr/local/opt/qt5/include


.app bundles were installed.
Run `brew linkapps qt5` to symlink these to /Applications.
==> Summary
🍺  /usr/local/Cellar/qt5/5.5.1_2: 7,197 files, 292.6M
Andrews-MacBook-Pro:kryten boo$ 


Andrews-MacBook-Pro:software boo$ git clone git://github.com/simonfuhrmann/mve.git
Cloning into 'mve'...
remote: Counting objects: 8631, done.
remote: Total 8631 (delta 0), reused 0 (delta 0), pack-reused 8631
Receiving objects: 100% (8631/8631), 3.31 MiB | 571.00 KiB/s, done.
Resolving deltas: 100% (5664/5664), done.
Checking connectivity... done.
Andrews-MacBook-Pro:software boo$ 


cd mve; make

all OK

Andrews-MacBook-Pro:mve boo$ cd apps/umve/; qmake; make; ./umve
-bash: qmake: command not found
make: *** No targets specified and no makefile found.  Stop.
-bash: ./umve: No such file or directory
Andrews-MacBook-Pro:umve boo$ 

OK, so need to get qmake working…
Andrews-MacBook-Pro:umve boo$ brew linkapps qt5
Linking /usr/local/opt/qt5/libexec/Assistant-qt5.app to /Applications.
Linking /usr/local/opt/qt5/libexec/Designer-qt5.app to /Applications.
Linking /usr/local/opt/qt5/libexec/Linguist-qt5.app to /Applications.
Linking /usr/local/opt/qt5/libexec/pixeltool-qt5.app to /Applications.
Linking /usr/local/opt/qt5/libexec/qml-qt5.app to /Applications.
Linking /usr/local/opt/qt5/libexec/QMLViewer-qt5.app to /Applications.
Andrews-MacBook-Pro:umve boo$ 

changed the path
Andrews-MacBook-Pro:umve boo$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin:/usr/texbin:/Users/boo/Documents/VisualSFM/vsfm/bin
Andrews-MacBook-Pro:umve boo$ export PATH=$PATH:/usr/local/opt/qt5/bin
Andrews-MacBook-Pro:umve boo$ qmake
Info: creating stash file /Users/boo/Documents/software/mve/apps/umve/.qmake.stash

Andrews-MacBook-Pro:umve boo$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/opt/qt5/lib

also modified ~/.bash_profile to have these paths fixed up

make
all OK
./umve
WORKS!



Diagnosis:  qt5 was not fully installed
fixed up PATH and LIBRARY_PATH as above
did the suggested linkup

**Comment by simonfuhrmann** [comment]
Updated the OSX Instructions a bit. Thanks for reporting.
