### ISSUE TITLE
missing the Property page of sfmReconstruction

### ISSUE THREAD

**Issue by SimFaris** [simonfuhrmann/mve#204]
I have downloaded the Windows binaries of UMVE, and used it according to the paper MVE – A Multi-View Reconstruction Environment. However the software misses the Property page of sfmReconstruction, so I could not get the sparse point clouds.Anyone could give me some advise, thank U.

**Comment by simonfuhrmann** [comment]
The SfM UI has been removed from UMVE. It lead to code duplication and licensing implications. Please use the sfmrecon app and use UMVE for inspection of the results only.

**Comment by SimFaris** [comment]
thank u
