### ISSUE TITLE
importing openMVG bundle?

### ISSUE THREAD

**Issue by frugivore** [simonfuhrmann/mve#209]
Hi all,

is there any exampe on how to import an openMVG bundle with the makescene command?

As far as I know openMVG generates an sfm_data.json after sequential reconstruction, which holds the estimated camera poses. So is there a way to import this file directly?

Regards,
Torsten

**Comment by pmoulon** [comment]
HI,
Just follow the doc ;-)
https://openmvg.readthedocs.org/en/latest/software/MVS/MVE/

**Comment by simonfuhrmann** [comment]
In the OpenMVG case, MVE is not importing but OpenMVG is expoting. Closing this. Feel free to comment if you have more questions.

**Comment by simonfuhrmann** [comment]
Pierre,  for scene2pset, -dinsc can be replaced with -F$resolution. Can you update the docs? Thanks.

**Comment by frugivore** [comment]
Hello,
I wasn't aware that I have to export data from openMVG. Everything works fine.

Thanks a lot,
Torsten

**Comment by pmoulon** [comment]
@simonfuhrmann 
You mean that I must remove the -d -n -s -c option
```
args.add_option('d', "depthmap", true, "Name of depth map to use [depth-L0]");
args.add_option('n', "with-normals", false, "Write points with normals (PLY only)");
args.add_option('s', "with-scale", false, "Write points with scale values (PLY only)");
args.add_option('c', "with-conf", false, "Write points with confidence (PLY only)");
```
and use only -F$resolution to set all of them once.

Briefly, replace the old command line by
```
scene2pset -F$resolution -iundist $directory $directory/OUTPUT.ply
```

-L seems do not exist any longer.

**Comment by simonfuhrmann** [comment]
No. You replace all of `-depth-L2 -iundist-L2 -nsc` with only a single flag `-F2`.

    Usage: scene2pset [ OPTS ] SCENE_DIR MESH_OUT
    Available options: 
      -F, --fssr=ARG           FSSR output, sets -nsc and -di with scale ARG
