### ISSUE TITLE
About compile error on vs2013

### ISSUE THREAD

**Issue by tmac1002** [simonfuhrmann/mve#216]
Hi, 
I have already compile 3dparty successfully on vs2013. But when I compile MVE.sln, it occured lost of error and warning. Could you help me have a look it. I will appreciate it. Thank you.
![qq 20160328155209](https://cloud.githubusercontent.com/assets/11924213/14073685/b9b5e404-f4fd-11e5-8b80-c39d9b4e8f49.jpg)
![qq 20160328155217](https://cloud.githubusercontent.com/assets/11924213/14073780/5d193d6c-f4fe-11e5-8208-6fee8324a2d4.jpg)
![qq 20160328155323](https://cloud.githubusercontent.com/assets/11924213/14073903/547209ea-f4ff-11e5-9298-23ff4b733e71.jpg)

**Comment by andre-schulz** [comment]
I wrote an answer to the issue [here](https://github.com/andre-schulz/mve/issues/2#issuecomment-202839731).

**Comment by simonfuhrmann** [comment]
Won't fix, closing this.
Nice screenshots BTW.

**Comment by tmac1002** [comment]
Hi, Simon
I am very sorry to these screenshots, maybe it is too big to stand but I have no idea to make it smaller. Again I am so sorry. I don't mean it!
