### ISSUE TITLE
Wrapper for COLMAP

### ISSUE THREAD

**Issue by ahojnnes** [simonfuhrmann/mve#221]
Hi,

I just released my SfM pipeline (https://github.com/colmap/colmap) and would like to advertise your library as a good dense pipeline. I see that `makescene.cc` supports VisualSfM and Bundler as input format. Does MVE already provide an interface for the PMVS/CVMS directory/file structure?

Thanks, Johannes

**Comment by pmoulon** [comment]
Perhaps you can write your own exporter to MVE
Here the OpenMVG2MVE interface https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/main_openMVG2MVE2.cpp

MVE does not have any importer for the PMVS/CMVS data format.
But perhaps this one can help you to write your own colmap exporter to this framework
https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/main_openMVG2PMVS.cpp

**Comment by ahojnnes** [comment]
Thanks Pierre! Looks like it might be easiest to implement an importer for COLMAP in MVE. @simonfuhrmann Would you be interested in such a contribution to the `makescene.cc`?

**Comment by simonfuhrmann** [comment]
Hi Johannes,

PMVS/CMVS are dense tools. I don't understand what an interface to those tools should do. Import the dense result? Export the MVE SfM output to the PMVS format?

I have never heard of COLMAP. If people would like to use its output together with MVE, we can think about writing either an importer on the MVE side, or an exporter on the COLMAP side. The question is mainly: Do I need any additional dependencies in MVE to write the importer? E.g., for OpenMVG it would require parsing JSON, and I don't want to add this dependency to MVE. So Pierre and I ended up putting the exporter in OpenMVG.

Simon

**Comment by ahojnnes** [comment]
Hi Simon,

Colmap provides an exporter to the PMVS/CMVS format. If MVE provided an importer for that format, it would have been easy to export to MVE as well. Since you provide import functionality for Bundler/VisualSfM, it should be easily possible to do so for Colmap or PMVS/CMVS as well.

> I have never heard of COLMAP
The reason being that I only open-sourced a few days ago.

I can just send you a pull request with changes to `makescene.cc`, no additional dependencies required.

Cheers, Johannes

**Comment by simonfuhrmann** [comment]
Hi, 

Sure if you can send me a PR with a function that imports from a COLMAP directory, that would be great. 

Simon

**Comment by simonfuhrmann** [comment]
Updates?

**Comment by ahojnnes** [comment]
@simonfuhrmann I am still planning to do it, but I have some submission deadlines going on at the moment, so I had to postpone this for a little while. Sorry.

**Comment by simonfuhrmann** [comment]
Closing this. Feel free to re-open if you have updates.
