### ISSUE TITLE
Use of unnormalized quaternion

### ISSUE THREAD

**Issue by ibtaylor** [simonfuhrmann/mve#227]
Shouldn't `camera_rot` in apps/meshalign/stanford_alignment.cc be normalized before `.rotate()` is called, which converts it to a rotation matrix in lines 83 and 84?

**Comment by simonfuhrmann** [comment]
To be honest, I never really understood why the code works as it is. And it's been a while. Have you tried normalizing the Quaternion? At least for the Stanford datasets I tried, the code worked as it is right now. Are you experiencing issues?

**Comment by ibtaylor** [comment]
First off, I do not and have not used `meshalign`. So, no, I'm not experiencing issues.

In some of my personal projects, I experienced errors because I did not normalize my quaternions and so I went searching through various libraries that I use for similar errors. In my search, I spotted this one, and even though it does not affect me, I thought I would mention it.

From my understanding, the error can come from precision loss when reading/writing floating points to ascii formats and also from floating point errors in general. Applying a non-unit length quaternion for rotation has undefined behavior as mentioned in the Eigen documentation here https://eigen.tuxfamily.org/dox/classEigen_1_1Quaternion.html

**Comment by simonfuhrmann** [comment]
You are right, quaternions need to be normalized regularly to prevent inaccuracies. However, in this instant the quaternion is read once, expected to be normalized, and used often. I think it's fine here. Closing the isse. 

Thanks for the feedback
