### ISSUE TITLE
MVE: Change K matrix to comply with common text book notation

### ISSUE THREAD

**Issue by simonfuhrmann** [simonfuhrmann/mve#23]
MVE builds the calibration `K` of the camera matrix `P = K [R | t]` as follows `K = [-ax 0 px; 0 ay py; 0 0 -1]` where `(ax,ay)` are the focal lengths in image dimensions, and `(px,py)` is the principal point. The reasoning was to obtain a calibration that properly projects into usual image coordinates given an OpenGL reference frame (looking along the negative z-axis).

According to literature, the K matrix should not have any negative value on the diagonal. This can be fixed in a several step process. Surprisingly, it seems possible to only fix camera parameters and no structure (i.e. points or geometry).

The calibration is fixed by introducing a scaling matrix `X`. `P = K [R | t] = K X X^ [R | t]` where `X^` is the inverse if `X`. Choose `X = X^ = diag(-1, 1, -1)`. Now multiplying `K * X` yields a textbook notation `K` matrix. The new rotation is `[R' | t'] = X^ * [R | t]`.

Process:
- Change code that generates the K matrix
  - also rename fill_projection to fill_calibration
  - also change fill_calibration to use float (see bug #2)
- Change [R | t] of each camera in all data sets
  - Implement script that copies views while applying `X^` to the camera.
  - Modify `mveshell` to do this?
- Change affected code
  - Change makescene to generate the new [R | t]
  - Check if dmrecon needs to be changed

**Comment by HelliceSaouli** [comment]
Hello
So according to this if I want to reproduce a view in OpenGL , all I need to do is to feed the shaders the projection matrix P without the need to flip axis in rotation matrix R or something ?

**Comment by simonfuhrmann** [comment]
Check out our rephotographer code in UMVE to reproduce a view in OpenGL:
https://github.com/simonfuhrmann/mve/blob/master/apps/umve/scene_addins/addin_rephotographer.cc#L112

**Comment by HelliceSaouli** [comment]
Thank you.Sir
It seems that the build I have is outdated and I can't find _fill_gl_viewtrans_ -___- and looking to the code on
[line 75](https://github.com/simonfuhrmann/mve/blob/cf68daad28f8871a58ea9987a1694937eadbefdb/libs/mve/camera.cc#L75)   you  flip the axis of _mve_ rotation camera (the y and z, and it's weird since in this post (above) you said you already changed R and t to match OpenGL. thus using the mve camera directly must yield a correct rephotography.

**Comment by simonfuhrmann** [comment]
Where does it say it was changed to match OpenGL? It says the *original* reasoning was to follow the OpenGL conventions, and we ended up with a strange K matrix. So we fixed that. The linked code should do exactly what you want, no?
