### ISSUE TITLE
Problem of SfM: Error finding initial pair

### ISSUE THREAD

**Issue by xialang2012** [simonfuhrmann/mve#231]
I used command `sfmrecon.exe ./img-res` to get the SfM result, but it showed me the error

> MVE SfM Reconstruction (built on May 19 2016, 14:36:12)
> SSE2 accelerated matching is enabled.
> SSE3 accelerated matching is enabled.
> Initializing scene with 9 views...
> Initialized 9 views (max ID is 8), took 8ms.
> Computing image features...
> View ID 0001 (2304x1728), 21347 features, took 9668 ms.
> View ID 0002 (2304x1728), 22366 features, took 9888 ms.
> View ID 0008 (2304x1728), 25460 features, took 9892 ms.
> View ID 0000 (2304x1728), 21200 features, took 10007 ms.
> View ID 0003 (2304x1728), 23159 features, took 10325 ms.
> View ID 0004 (2304x1728), 25695 features, took 10376 ms.
> View ID 0007 (2304x1728), 26827 features, took 10441 ms.
> View ID 0006 (2304x1728), 27626 features, took 10554 ms.
> View ID 0005 (2304x1728), 28081 features, took 10649 ms.
> Computed 221761 features for 9 views (average 24640).
> Computing features took 11669 ms.
> Performing feature matching...
> Pair (3,0) rejected, only 3 of 5 low-res matches.
> Pair (4,1) rejected, only 2 of 5 low-res matches.
> Pair (4,0) rejected, only 3 of 5 low-res matches.
> Pair (5,0) rejected, only 1 of 5 low-res matches.
> Pair (1,0) matched, 3341 inliers, took 5599 ms.
> Pair (2,0) matched, 837 inliers, took 5794 ms.
> Pair (2,1) matched, 4855 inliers, took 6031 ms.
> Pair (3,1) matched, 1327 inliers, took 6033 ms.
> Pair (3,2) matched, 5299 inliers, took 6376 ms.
> Pair (4,2) matched, 717 inliers, took 7054 ms.
> Pair (7,4) rejected, only 0 of 5 low-res matches.
> Pair (6,0) matched, 524 inliers, took 7251 ms.
> Pair (4,3) matched, 2426 inliers, took 7291 ms.
> Pair (5,1) matched, 740 inliers, took 7391 ms.
> Pair (6,1) matched, 2191 inliers, took 7441 ms.
> Pair (6,2) matched, 4316 inliers, took 7705 ms.
> Pair (8,3) rejected, only 1 of 5 low-res matches.
> Pair (5,2) matched, 2853 inliers, took 7737 ms.
> Pair (8,4) rejected, only 0 of 5 low-res matches.
> Pair (8,5) rejected, only 0 of 5 low-res matches.
> Pair (6,3) matched, 2413 inliers, took 7920 ms.
> Pair (5,3) matched, 5290 inliers, took 8056 ms.
> Pair (6,4) matched, 635 inliers, took 8855 ms.
> Pair (5,4) matched, 2032 inliers, took 8922 ms.
> Pair (7,0) matched, 1652 inliers, took 7215 ms.
> Pair (7,1) matched, 3650 inliers, took 7184 ms.
> Pair (7,2) matched, 2010 inliers, took 7691 ms.
> Pair (7,3) matched, 641 inliers, took 7878 ms.
> Pair (8,0) matched, 5396 inliers, took 7006 ms.
> Pair (8,1) matched, 1936 inliers, took 6985 ms.
> Pair (8,2) matched, 494 inliers, took 7304 ms.
> Pair (6,5) matched, 5928 inliers, took 9940 ms.
> Pair (8,7) matched, 3618 inliers, took 8883 ms.
> Pair (8,6) matched, 1127 inliers, took 9024 ms.
> Pair (7,5) matched, 1450 inliers, took 9879 ms.
> Pair (7,6) matched, 4917 inliers, took 9818 ms.
> Found a total of 28 matching image pairs.
> Matching took 17167 ms.
> Saving pre-bundle to file...
> Cleanup: Released 0 embeddings in 0 of 9 views.
> Initializing camera intrinsics...
> Computing feature tracks...
> Propagating track IDs...
> Removing tracks with conflicts... deleted 33 tracks.
> Colorizing tracks...
> Created a total of 32096 tracks.
> Searching for initial pair...
>   Pair   1,  8: 2375 matches, 2348 H-inliers (98%)
>   Pair   2,  7: 2610 matches, 2574 H-inliers (98%)
>   Pair   3,  4: 2530 matches, 2504 H-inliers (98%)
>   Pair   1,  6: 2667 matches, 2645 H-inliers (99%)
>   Pair   3,  6: 3087 matches, 3010 H-inliers (97%)
>   Pair   2,  5: 3360 matches, 3325 H-inliers (98%)
>   Pair   0,  1: 3559 matches, 3546 H-inliers (99%)
>   Pair   7,  8: 3826 matches, 3823 H-inliers (99%)
>   Pair   1,  7: 4049 matches, 4041 H-inliers (99%)
>   Pair   2,  6: 4807 matches, 4799 H-inliers (99%)
>   Pair   1,  2: 5041 matches, 5025 H-inliers (99%)
>   Pair   0,  8: 5506 matches, 5506 H-inliers (100%)
>   Pair   2,  3: 5464 matches, 5447 H-inliers (99%)
>   Pair   4,  5: 2232 matches, 2186 H-inliers (97%)
>   Pair   6,  8: 1485 matches, 1478 H-inliers (99%)
>   Pair   1,  3: 1827 matches, 1676 H-inliers (91%)
>   Pair   3,  5: 5569 matches, 5558 H-inliers (99%)
>   Pair   5,  7: 1944 matches, 1918 H-inliers (98%)
>   Pair   6,  7: 5176 matches, 5175 H-inliers (99%)
>   Pair   0,  4:   10 matches
>   Pair   4,  8:    6 matches
>   Pair   0,  2: 1273 matches, 1151 H-inliers (90%)
>   Pair   0,  7: 2068 matches, 2063 H-inliers (99%)
>   Pair   3,  7: 1211 matches, 1147 H-inliers (94%)
>   Pair   5,  6: 6158 matches, 6156 H-inliers (99%)
>   Pair   1,  5: 1198 matches, 1172 H-inliers (97%)
>   Pair   4,  6: 1016 matches,  969 H-inliers (95%)
>   Pair   1,  4:  198 matches,  192 H-inliers (96%)
>   Pair   4,  7:  193 matches,  191 H-inliers (98%)
>   Pair   3,  8:  140 matches,  127 H-inliers (90%)
>   Pair   0,  3:  157 matches,  117 H-inliers (74%)
>   Pair   5,  8:  185 matches,  177 H-inliers (95%)
>   Pair   0,  5:  123 matches,  115 H-inliers (93%)
>   Pair   2,  4: 1002 matches,  939 H-inliers (93%)
>   Pair   2,  8:  942 matches,  881 H-inliers (93%)
>   Pair   0,  6:  889 matches,  880 H-inliers (98%)
> Searching for pair with best score...
> Error finding initial pair, exiting!
> Try manually specifying an initial pair.
> MVE SfM Reconstruction (built on May 19 2016, 14:36:12)
> SSE2 accelerated matching is enabled.
> SSE3 accelerated matching is enabled.
> Initializing scene with 9 views...
> Initialized 9 views (max ID is 8), took 8ms.
> Computing image features...
> View ID 0001 (2304x1728), 21347 features, took 9668 ms.
> View ID 0002 (2304x1728), 22366 features, took 9888 ms.
> View ID 0008 (2304x1728), 25460 features, took 9892 ms.
> View ID 0000 (2304x1728), 21200 features, took 10007 ms.
> View ID 0003 (2304x1728), 23159 features, took 10325 ms.
> View ID 0004 (2304x1728), 25695 features, took 10376 ms.
> View ID 0007 (2304x1728), 26827 features, took 10441 ms.
> View ID 0006 (2304x1728), 27626 features, took 10554 ms.
> View ID 0005 (2304x1728), 28081 features, took 10649 ms.
> Computed 221761 features for 9 views (average 24640).
> Computing features took 11669 ms.
> Performing feature matching...
> Pair (3,0) rejected, only 3 of 5 low-res matches.
> Pair (4,1) rejected, only 2 of 5 low-res matches.
> Pair (4,0) rejected, only 3 of 5 low-res matches.
> Pair (5,0) rejected, only 1 of 5 low-res matches.
> Pair (1,0) matched, 3341 inliers, took 5599 ms.
> Pair (2,0) matched, 837 inliers, took 5794 ms.
> Pair (2,1) matched, 4855 inliers, took 6031 ms.
> Pair (3,1) matched, 1327 inliers, took 6033 ms.
> Pair (3,2) matched, 5299 inliers, took 6376 ms.
> Pair (4,2) matched, 717 inliers, took 7054 ms.
> Pair (7,4) rejected, only 0 of 5 low-res matches.
> Pair (6,0) matched, 524 inliers, took 7251 ms.
> Pair (4,3) matched, 2426 inliers, took 7291 ms.
> Pair (5,1) matched, 740 inliers, took 7391 ms.
> Pair (6,1) matched, 2191 inliers, took 7441 ms.
> Pair (6,2) matched, 4316 inliers, took 7705 ms.
> Pair (8,3) rejected, only 1 of 5 low-res matches.
> Pair (5,2) matched, 2853 inliers, took 7737 ms.
> Pair (8,4) rejected, only 0 of 5 low-res matches.
> Pair (8,5) rejected, only 0 of 5 low-res matches.
> Pair (6,3) matched, 2413 inliers, took 7920 ms.
> Pair (5,3) matched, 5290 inliers, took 8056 ms.
> Pair (6,4) matched, 635 inliers, took 8855 ms.
> Pair (5,4) matched, 2032 inliers, took 8922 ms.
> Pair (7,0) matched, 1652 inliers, took 7215 ms.
> Pair (7,1) matched, 3650 inliers, took 7184 ms.
> Pair (7,2) matched, 2010 inliers, took 7691 ms.
> Pair (7,3) matched, 641 inliers, took 7878 ms.
> Pair (8,0) matched, 5396 inliers, took 7006 ms.
> Pair (8,1) matched, 1936 inliers, took 6985 ms.
> Pair (8,2) matched, 494 inliers, took 7304 ms.
> Pair (6,5) matched, 5928 inliers, took 9940 ms.
> Pair (8,7) matched, 3618 inliers, took 8883 ms.
> Pair (8,6) matched, 1127 inliers, took 9024 ms.
> Pair (7,5) matched, 1450 inliers, took 9879 ms.
> Pair (7,6) matched, 4917 inliers, took 9818 ms.
> Found a total of 28 matching image pairs.
> Matching took 17167 ms.
> Saving pre-bundle to file...
> Cleanup: Released 0 embeddings in 0 of 9 views.
> Initializing camera intrinsics...
> Computing feature tracks...
> Propagating track IDs...
> Removing tracks with conflicts... deleted 33 tracks.
> Colorizing tracks...
> Created a total of 32096 tracks.
> Searching for initial pair...
>   Pair   1,  8: 2375 matches, 2348 H-inliers (98%)
>   Pair   2,  7: 2610 matches, 2574 H-inliers (98%)
>   Pair   3,  4: 2530 matches, 2504 H-inliers (98%)
>   Pair   1,  6: 2667 matches, 2645 H-inliers (99%)
>   Pair   3,  6: 3087 matches, 3010 H-inliers (97%)
>   Pair   2,  5: 3360 matches, 3325 H-inliers (98%)
>   Pair   0,  1: 3559 matches, 3546 H-inliers (99%)
>   Pair   7,  8: 3826 matches, 3823 H-inliers (99%)
>   Pair   1,  7: 4049 matches, 4041 H-inliers (99%)
>   Pair   2,  6: 4807 matches, 4799 H-inliers (99%)
>   Pair   1,  2: 5041 matches, 5025 H-inliers (99%)
>   Pair   0,  8: 5506 matches, 5506 H-inliers (100%)
>   Pair   2,  3: 5464 matches, 5447 H-inliers (99%)
>   Pair   4,  5: 2232 matches, 2186 H-inliers (97%)
>   Pair   6,  8: 1485 matches, 1478 H-inliers (99%)
>   Pair   1,  3: 1827 matches, 1676 H-inliers (91%)
>   Pair   3,  5: 5569 matches, 5558 H-inliers (99%)
>   Pair   5,  7: 1944 matches, 1918 H-inliers (98%)
>   Pair   6,  7: 5176 matches, 5175 H-inliers (99%)
>   Pair   0,  4:   10 matches
>   Pair   4,  8:    6 matches
>   Pair   0,  2: 1273 matches, 1151 H-inliers (90%)
>   Pair   0,  7: 2068 matches, 2063 H-inliers (99%)
>   Pair   3,  7: 1211 matches, 1147 H-inliers (94%)
>   Pair   5,  6: 6158 matches, 6156 H-inliers (99%)
>   Pair   1,  5: 1198 matches, 1172 H-inliers (97%)
>   Pair   4,  6: 1016 matches,  969 H-inliers (95%)
>   Pair   1,  4:  198 matches,  192 H-inliers (96%)
>   Pair   4,  7:  193 matches,  191 H-inliers (98%)
>   Pair   3,  8:  140 matches,  127 H-inliers (90%)
>   Pair   0,  3:  157 matches,  117 H-inliers (74%)
>   Pair   5,  8:  185 matches,  177 H-inliers (95%)
>   Pair   0,  5:  123 matches,  115 H-inliers (93%)
>   Pair   2,  4: 1002 matches,  939 H-inliers (93%)
>   Pair   2,  8:  942 matches,  881 H-inliers (93%)
>   Pair   0,  6:  889 matches,  880 H-inliers (98%)
> Searching for pair with best score...
> Error finding initial pair, exiting!
> Try manually specifying an initial pair.

then I tried `sfmrecon.exe ./img-res --initial-pair=0,0`, it showed

> Pair (8,0) matched, 5396 inliers, took 6996 ms.
> Pair (8,1) matched, 1936 inliers, took 6956 ms.
> Pair (8,2) matched, 494 inliers, took 7276 ms.
> Pair (6,5) matched, 5928 inliers, took 10308 ms.
> Pair (8,6) matched, 1127 inliers, took 9353 ms.
> Pair (8,7) matched, 3618 inliers, took 9100 ms.
> Pair (7,5) matched, 1450 inliers, took 9945 ms.
> Pair (7,6) matched, 4917 inliers, took 9877 ms.
> Found a total of 28 matching image pairs.
> Matching took 17440 ms.
> Saving pre-bundle to file...
> Cleanup: Released 0 embeddings in 0 of 9 views.
> Initializing camera intrinsics...
> Computing feature tracks...
> Propagating track IDs...
> Removing tracks with conflicts... deleted 33 tracks.
> Colorizing tracks...
> Created a total of 32096 tracks.
> No matches for initial pair

but, it did not work. I did not know what causes the problem, no enough match point? But the SfM product by VisualSfM is ok.

**Comment by simonfuhrmann** [comment]
Automatically determining the initial pair failed because your your views are mainly related by a homography tranformation, which means the scene geometry is basically a plain, or you don't have enough parallax between the views.

Try manually specifying an initial pair. Which you tried, but specifying a pair with two times the same view is not very useful. Try `--initial-pair=0,3`.

**Comment by fasterthan** [comment]
I am running into this issue as well, except sfmrecon does not compute any features.

Here is the output in console:
```
[david@hmd apps]$ ./sfmrecon/sfmrecon --initial-pair=12,33 /work/Projects/Photogrammetry/COLMAP4/mve_makescened/
MVE SfM Reconstruction (built on Sep 20 2018, 14:54:19)
Using initial pair (12,33).
SSE2 accelerated matching is enabled.
SSE3 accelerated matching is enabled.
Initializing scene with 330 views...
Initialized 330 views (max ID is 329), took 10ms.
Computing image features...
Computed 0 features for 330 views (average 0).
Computing features took 1 ms.
Performing feature matching...
Found a total of 0 matching image pairs.
Matching took 280 ms.
Error: No matching image pairs. Exiting.
```

I used `makescene` to import a bundle.out file generated with COLMAP.

I initially tried running my image dataset through the TexRecon pipeline but I got stuck on the `texrecon` command: the process gets killed without an error message printed to console.
