### ISSUE TITLE
Windows build does not wor

### ISSUE THREAD

**Issue by dnjiang** [simonfuhrmann/mve#234]
I tried to build MVE-cmake branch in VS 2015, but it failed at building qt5 project in the 3rdparty solution while it tries to download qt5:
Error downloading	qt5	C:\work\main\CommonLibs\trunk\ThirdParty\mve-cmake\3rdparty\VS2015\CUSTOMBUILD	1	

Any idea how to fix this?

Thanks
Dan

**Comment by dnjiang** [comment]
A bit more info: looks like the qt5 download link in the qt5 project is no-longer valid...

**Comment by dnjiang** [comment]
Update:  I manually downloaded qt5 from the link giving in the CMakefile.lst and unzip it to mve-cmake\3rdparty\VS2015\qt5\src folder. QT5 project in 3rdparty.sln now starts to compile, but it errors out after a while (I think it was close to the end):
![image](https://cloud.githubusercontent.com/assets/9577994/15647185/14cecb2c-2630-11e6-9da1-8a5db86278a4.png)

After that, I tried to generate MVE solution from CMake, but I got error msg below:
![image](https://cloud.githubusercontent.com/assets/9577994/15647223/44f5eb82-2630-11e6-9377-80e336c4b4bb.png)

**Comment by andre-schulz** [comment]
Well, if it works with your browser then it should work with cmake.
Regarding the compilation issue you described, can you please try to compile mve/3rdparty in a folder that has a shorter path? For example, "C:\work\mve"? I suspect that the path is becoming too long during compilation of qt5.

**Comment by dnjiang** [comment]
Ok, I moved mve_cmake to be directly under c:\ drive, then 3rdparty soluton compiles. 

Next, I try to configure for MVE, no problem, but when trying to generate solution for mve, I got the following:
![image](https://cloud.githubusercontent.com/assets/9577994/15658956/1627fe9c-2691-11e6-8f5e-91d27a8ab9d7.png)

Any clue?

Thanks,
Dan

**Comment by andre-schulz** [comment]
Can you please include the message box of cmake in the screenshot?
Btw, did you build 3rdparty in-source or in a separate build folder?

**Comment by dnjiang** [comment]
The error dialog I gave in the previous screen shot is from CMake.

Not sure what you mean by in-source. 3rdparty is directly under c:\mve-cmake folder. CMake output of 3rdparty is at c:\mve-cmake\3rdparty\VS2015, Please refer to the screenshot below:
![image](https://cloud.githubusercontent.com/assets/9577994/15679197/f61a0490-271e-11e6-9265-3d35c99858b2.png)

-Thanks

**Comment by andre-schulz** [comment]
CMake has a window directly beneath the configuration variables to which messages are written (see screenshot, area highlighted with a red rectangle).
![cmake_message_window](https://cloud.githubusercontent.com/assets/7137149/15680047/69f0db7a-2754-11e6-8575-bae23afa9077.png)

With in-source I mean that the folder where the binaries are built is the same as the folder where the source code is. Judging from the screenshot, it seems that you build 3rdparty in "C:\mve-cmake\3rdparty\VS2015" which is unsupported and will cause MVE's CMakeLists.txt to not find the 3rdparty libraries. Please build 3rdparty in "C:\mve-cmake\3rdparty".

**Comment by dnjiang** [comment]
The version of CMake I used was 3.1.1 which does not have a window beneath the configuration variables. I changed to 3.5.2, same GUI. So there maybe a configuration setting somewhere  in CMake that I do not know (I am new to CMake).

Anyhow, with the new CMake version, Generate button does work now regardless where I put my binaries for MVE! 

Many Thanks for your Help!
Dan

**Comment by andre-schulz** [comment]
Just to clarify, CMake has had the message window for a very long time. The reason why you don't see it is very likely because it has been resized to be hidden. If you place the mouse cursor a bit above the bottom border of the CMake window, the cursor should change into a resizing icon. You should then be able to drag the cursor up and make the message window visible.

Again just to clarify, you can put the MVE binaries anywhere you want but 3rdparty has to be built in the same folder where `3rdparty/CMakeLists.txt` resides in. The CMake version shouldn't have any influence on this.
