### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by kabaka0** [simonfuhrmann/mve#235]
I needed to modify the CXXFLAGS to add -lglut -lGLU -lGL  to make it build successfully on Ubuntu 14. Perhaps edit the Makefile.inc to include this?

**Comment by flanggut** [comment]
The current version builds just fine on our Ubuntu 14 installation. Can you elaborate?

**Comment by kabaka0** [comment]
I have tried rebuilding it again with no issue - perhaps I was missing a dependence previously. I did install freeglut3 (to add OpenGL support). Thanks for your prompt response.
