### ISSUE TITLE
scene2pset (for Windows) fails to export point set from a scene

### ISSUE THREAD

**Issue by dnjiang** [simonfuhrmann/mve#239]
I use Theia to create a sfm and then convert that to bundler format. I then use makescene.exe and dmrecon.exe to create  depth maps. They all seem to work. But when using scene2pset.exe (located in .\mve-win64 folder):

.\mve-win64\scene2pset -F0 .\MVE .\MVE\pset-L0.ply  

I get an empty point set back:

MVE Scene to Pointset (built on Jun  8 2016, 13:33:26)
Using depthmap "depth-L0" and color image "undistorted"
Initializing scene with 4 views...
Initialized 4 views (max ID is 3), took 2ms.
Processing view "0000" (with colors)...
Processing view "0002" (with colors)...
Processing view "0003" (with colors)...
Processing view "0001" (with colors)...
Writing final point set (0 points)...
Writing PLY file (0 verts, with colors, with normals, with confidences, with val
ues, 0 faces, with colors)... done.

From VS2015 debugger, it seems that the pixels counter in depthmap_triangulate() is always 0.

I have attached the zip file that contains the input to scene2pset under ".\mve" folder.

BTW, I was able to use Theia's sfm output with pmvs for dense point cloud reconstruction.

-Thank you.
[mve.zip](https://github.com/simonfuhrmann/mve/files/319409/mve.zip)

**Comment by simonfuhrmann** [comment]
That's because your depth maps don't contain any reconstructed pixels. Probably because you don't have enough views for depth map reconstruction.
