### ISSUE TITLE
scene2pset returns empty point set

### ISSUE THREAD

**Issue by dnjiang** [simonfuhrmann/mve#245]
I have a dataset (attached) that works with Theia/PMVS, but MVE returns empty point set:
makescene.exe -o -i ..\dataset_images\ET ..\dataset_images\ET\MVE_MakeScene_Output
sfmrecon.exe ..\dataset_images\ET\MVE_MakeScene_Output
dmrecon -s2 ..\dataset_images\ET\MVE_MakeScene_Output

// .. scene2pset would return 0 sample points while theia/pmvs works
scene2pset -F2 ..\dataset_images\ET\MVE_MakeScene_Output ..\dataset_images\ET\MVE_MakeScene_Output\pset-L2.ply

[ET.zip](https://github.com/simonfuhrmann/mve/files/356203/ET.zip)

**Comment by simonfuhrmann** [comment]
The result is likely because dmrecon did not reconstruct any depth values. Did you check with UMVE that the scene (SfM) has been reconstructed properly, and the depth maps contain values?
