### ISSUE TITLE
Build Issues in Windows

### ISSUE THREAD

**Issue by lishi0927** [simonfuhrmann/mve#246]
I have read the build instructions for windows but I still have two questions, I hope you can help me solve the issues. Thank you.

The first is the build qt5 step in the 3rdparty, there is an error that unable to **detect the platform from environment** and i have tried to added "-platform win32-msvc2015" in the configure_command in the qt5's externalProject_add module in the CmakeLists.txt, there is still another error which is showed in the following picture.
![image](https://cloud.githubusercontent.com/assets/7486571/16829183/3587193e-49c9-11e6-9df3-9fb94510a71b.png)

The second is the mve-sfm step in the mve, I build in the Win32 and Release configuration, but there is an error C3861, **'mm_popcnt_u64': identifier not found in line 452 of the cascade_hashing.h**. I have tried build in the x64 but there are a lot of link errors. I have done a test in my computer and 'mm_popcnt_u64" can get the right result in the x64 architecture according to the MSDN examples (https://msdn.microsoft.com/en-us/library/bb531475.aspx).
Thank you.

**Comment by simonfuhrmann** [comment]
Sorry for the delay. I'm not maintaining the Windows build, and we don't officially support Windows. I will leave this open for a few more days, maybe somebody knows what's going on.

**Comment by lishi0927** [comment]
Thank you for your reply, and i'm glad to tell you I have solved these issues. The work should all build in the x64 architecture and it would work.
