### ISSUE TITLE
Is it possible to force the use of the FocalLengthIn35mmFormat tag?

### ISSUE THREAD

**Issue by lee7670** [simonfuhrmann/mve#247]
I have a camera that is not in the database and I'm using the precompiled binaries. Is it possible to use FocalLengthIn35mmFormat? It looks like the code supports this here: https://github.com/simonfuhrmann/mve/blob/master/libs/sfm/extract_focal_length.cc

**Comment by simonfuhrmann** [comment]
If the code cannot find the sensor size in the database, it should fall back to the 35mm equivalient if present. Does it now work?

**Comment by lee7670** [comment]
![image](https://cloud.githubusercontent.com/assets/3894242/17004620/a6a6dd3c-4e8a-11e6-891a-39e049d2d46a.png)
![image](https://cloud.githubusercontent.com/assets/3894242/17004648/c43d6528-4e8a-11e6-94cf-a11314f2cc46.png)
It doesn't seem to be, my command I'm using is sfmrecon.exe --intrinsics-from-views --video-matching=10 Scene

**Comment by simonfuhrmann** [comment]
Don't use  --intrinsics-from-views  as you want to use the intrinsics from EXIF.

**Comment by simonfuhrmann** [comment]
Closing. Feel free to re-open if this doesn't solve the issue.
