### ISSUE TITLE
Limit the number of polygones

### ISSUE THREAD

**Issue by fabiencastan** [simonfuhrmann/mve#248]
Hi,

From our experiments with MVE, we get the impression that the triangulation is too much dense regarding the precision achieved. If we add more images to improve the precision, the results are so dense that it cannot be loaded in many standard 3D softwares.
One solution seems to be the "scale" parameter at the dmrecon step. Currently we use 2 and if we put an higher value the quality decreased.

Is there a way to limit the number of generated polygones at the fssrecon step?

Regards,
Fabien

**Comment by simonfuhrmann** [comment]
The number of polygons depend on the scale on which the geometry is reconstructed (assuming that you are using FSSR for reconstruction). Indeed, the only way to reduce the number of generated polygons is the reduce the scale of the depth maps in `dmrecon`, like you did.

Note that `meshclean` will remove most of the "useless" triangles, but still leaves the over-tessellation in planar regions. Over-tessellation itself needs to be reduced in post-processing using a simplification software.

Another way is to multiply the sample scale in `fssrecon` with a factor, say `-s2`. Be warned, however, that this is a hack as you are messing around with the sample scales. This is NOT the approach you usually want to limit the polygons. Also consider `--min-scale` if you have a fairly uniform mesh, but be careful for the same reasons.

**Comment by fabiencastan** [comment]
Ok, thanks for the feedback.
