### ISSUE TITLE
Problem of the dmrecon

### ISSUE THREAD

**Issue by xialang2012** [simonfuhrmann/mve#249]
As shown as the output
> C:\Users\xialang2012\Desktop\mve-20160517-win64>dmrecon.exe uhd-res
> MVE Depth Map Reconstruction (built on May 17 2016, 12:36:21)
> Initializing scene with 7 views...
> Initialized 7 views (max ID is 6), took 7ms.
> Reading Photosynther file (7 cameras, 8969 features)...
> Reconstructing all views...
> scaled image size: 1000 x 1000
> scaled image size: 1000 x 1000
> scaled image size: 1000 x 1000
> scaled image size: 1000 x 1000
> scaled image size: 1000 x 1000
> scaled image size: 1000 x 1000
> Global View Selection failed
> Global View Selection failed
> Global View Selection failed
> Global View Selection failed
> Global View Selection failed
> Global View Selection failed
> scaled image size: 1000 x 1000
> Global View Selection failed
> Reconstruction took 641ms.
> Saving views back to disc...
> Saving views to MVE files... done.

The input file can be downloaded here. http://pan.baidu.com/s/1gf8sXs3

**Comment by simonfuhrmann** [comment]
It couldn't find neighboring views. Check if your scene is valid and has pose.
