### ISSUE TITLE
Won't import Bundler

### ISSUE THREAD

**Issue by foobarbecue** [simonfuhrmann/mve#250]
I am trying to import a project in Noah Snavely's bundler format. I tried to follow the instructions given in  makescene.exe for how to arrange the files, but I just get:

`Error: Could not detect bundle format.`

I also tried with an [example from the bundler repository](https://github.com/snavely/bundler_sfm/tree/master/examples/kermit).

**Comment by foobarbecue** [comment]
Hm, so if I rename things so that I have:

├── bundle
│   └── bundle.out
└── list.txt

Then I get:

> Info: Detected Noah's Bundler format.
> Reading Bundler file (398 cameras, 2592424 features)...
> Warning: Unexpected EOF (at feature 2518286)
> Error: Invalid amount of original images.

**Comment by simonfuhrmann** [comment]
Usually you don't need to "arrange" the files as Bundler should output the files using this structure. Is there any particular reason why you have to use bundler? Have you tried MVE's SfM? Just use `makescene` with `-i` to import images only, then run `sfmrecon` on the scene.

**Comment by foobarbecue** [comment]
Well, this is irrelevant to the question at hand, but I'm trying to work with output from other programs, particularly RealityCapture. I'd like to use FSSR and other MVE features on datasets (thousands of images) where I've already completed the reconstruction.

The bug here is that MVE fails to import the example output given by Noah Snavely, which presumably means that MVE's bundler import feature is broken. Either it should be fixed, or removed.

**Comment by simonfuhrmann** [comment]
Well, it's quite possible that the Bundler output changed and broke the importer. Would you mind getting down to the issue? Here is a pointer to the code that causes the issue. In particular, I would check if the documentation above the function matches the `bundle.out` file you have.

https://github.com/simonfuhrmann/mve/blob/master/libs/mve/bundle_io.cc#L392

**Comment by flanggut** [comment]
Well, no it didn't. I just ran the complete import and it worked without problems.
The example in the bundler git does not provide the files in the usual directory structure but if you arrange things correctly it just works.

Here's what I did:

```
git clone https://github.com/snavely/bundler_sfm.git
cd bundler_sfm/bin/
ln -s /usr/local/bin/jhead .
cd ../../examples/kermit 
../../bin/extract_focal.pl
cp prepare/list.txt .
mkdir bundle
cp results.example/bundle.out bundle
makescene . kermit
```

**Comment by simonfuhrmann** [comment]
Is this one more of these absurd std::binary windows problems?

**Comment by flanggut** [comment]
Maybe. Another option might be that RealityCapture doesn't conform with Noah's format to 100%. Or the image list `list.txt` is wonky.

**Comment by foobarbecue** [comment]
I'll look into this some more tonight. RealityCapture bundler output is [indeed](https://www.capturingreality.com/forum/viewtopic.php?f=5&t=714)several [kinds](https://www.capturingreality.com/forum/viewtopic.php?f=5&t=712) of broken, but I've almost figured out how to fix it. Glad to see the bunder example data worked for you. I am using windows but will try in my linux VM to see if that works.

**Comment by xialang2012** [comment]
It works well for me to exporter Noah's bundler to mve

**Comment by simonfuhrmann** [comment]
I'll just close this for now. Feel free to re-open if you think it's an MVE issue.
