### ISSUE TITLE
QT compile the umve

### ISSUE THREAD

**Issue by hushanming** [simonfuhrmann/mve#251]
Hi，I'm using the qt compile the umve ,but it shows the error in this [line](https://github.com/simonfuhrmann/mve/blob/master/apps/umve/viewinspect/scrollimage.cc#L58),and the error is as follows

_class QSIZE has no member named scaled_

so,what's your view on it? thank you.

**Comment by flanggut** [comment]
Are you using QT5?

**Comment by hushanming** [comment]
no,I'm using QT 4.8.7

**Comment by hushanming** [comment]
No,I'm using QT4.8.7,Perhaps this is the reason for my error.I'm going to update QT and try it again.Thank you for replying.Thank you.

**Comment by hushanming** [comment]
I'm using the QT5.7 to compile the umve,and it still show the same error  in this [line](https://github.com/simonfuhrmann/mve/blob/master/apps/umve/viewinspect/scrollimage.cc#L58).I checked the class QSIZE and it has no scaled,was I wrong?

**Comment by flanggut** [comment]
According to the [documentation](http://doc.qt.io/qt-5/qsize.html) the method should exist. Pretty sure you're still using the wrong version.
