### ISSUE TITLE
the problem about compiling sfm 

### ISSUE THREAD

**Issue by hushanming** [simonfuhrmann/mve#255]
Hi,
I use the vs2013 compile the [sfm](https://github.com/simonfuhrmann/mve/tree/master/libs/sfm),but it show the error C2797: 'sfm::MatchingBase::Options::sift_matching_opts': list initialization inside member initializer list or non-static data member initializer is not implemented in this [line](https://github.com/simonfuhrmann/mve/blob/master/libs/sfm/matching_base.h#L28) and in this [line](https://github.com/simonfuhrmann/mve/blob/master/libs/sfm/matching_base.h#L30).
There also show the error C2039: "allocate" is not the member of the "std::vector<T,util::AlignedAllocator<T,0x010>>" when compile this [line](https://github.com/simonfuhrmann/mve/blob/master/libs/sfm/_test_homography.cc#L71),Would you give me some advices about this error?
Thank you!

**Comment by andre-schulz** [comment]
Hi,
Visual Studio 2013 is no longer supported because it does not support some C++11 features which are used in MVE. Please try Visual Studio 2015.

**Comment by hushanming** [comment]
Thank you for replying.I will try  Visual Studio 2015.
