### ISSUE TITLE
3D to 2D correspondences

### ISSUE THREAD

**Issue by chuqiaodev** [simonfuhrmann/mve#258]
@simonfuhrmann,

Thanks very much for providing this nice open source, the performance is good. I am wondering may I obtain the 3D to 2D correspondence, e.g. for each 3D point in ply file, how do I know which images it mapping from, furthermore which 2D features it corresponding to, in any kind of outputs? Look forward to your reply. Thanks.

**Comment by nmoehrle** [comment]
The 2D3D correspondences for the SfM points (SIFT or SURF features) is implicitly saved in the bundle file (_synth_0.out_).
The bundle file contains for each 3D feature ([`mve::Bundle::Feature3D`](https://github.com/simonfuhrmann/mve/blob/master/libs/mve/bundle.h#L46)) a list (`Feature3D::refs`) of 2D features ([`mve::Bundle::Feature2D`](https://github.com/simonfuhrmann/mve/blob/master/libs/mve/bundle.h#L33)) that were used to reconstruct it. The Feature2D contains also a reference to the view it originated from (`Feature2D::view_id`). But be aware that the 2D position (`Feature2D::pos`) is not properly initialized for MVEs bundle files ([_libs/mve/bundle_io.cc_](https://github.com/simonfuhrmann/mve/blob/master/libs/mve/bundle_io.cc#L379)). However, you may obtain the position by projecting it into the view. Be sure to subtract (0.5, 0.5) from the 2D position if you want pixel coordinates, for more information have a look at the [Math Cookbook](https://github.com/simonfuhrmann/mve/wiki/Math-Cookbook).
