### ISSUE TITLE
Lots of compiler errors when running make (Mac OS)

### ISSUE THREAD

**Issue by zharvey-welltok** [simonfuhrmann/mve#259]
I am trying to build MVE on a Mac OS (El Capitan 10.11.5), and am following your [Mac OS build instructions]().

I was able to run the following commands without any problems whatsoever:

    brew install git libpng jpeg libtiff qt5
    cd ~/thelab
    git clone git://github.com/simonfuhrmann/mve.git
    cd mve
    make
    cd apps/umve
    qmake

But when I ran `make` (from inside the `apps/umve` directory), I get **lots** of compiler errors:

    myuser$ make
    clang++ -c -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -fPIC -O2 -arch x86_64 -Wall -W -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/local/Cellar/qt/4.8.7_2/mkspecs/unsupported/macx-clang-libc++ -I. -I/usr/local/Cellar/qt/4.8.7_2/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.7_2/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.7_2/lib/QtOpenGL.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.7_2/include -I../../libs -I/usr/local/include -I/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/System/Library/Frameworks/AGL.framework/Headers -Ibuild -o build/batchoperations.o batchoperations.cc
    In file included from batchoperations.cc:22:
    In file included from ../../libs/mve/mesh_io_ply.h:18:
    In file included from ../../libs/mve/image.h:17:
    In file included from ../../libs/math/functions.h:16:
    ../../libs/math/vector.h:85:25: error: expected ';' at end of declaration list
        static int constexpr dim = N;
                            ^
                            ;
    ../../libs/math/vector.h:277:5: warning: variable templates are a C++14 extension [-Wc++14-extensions]
    int constexpr Vector<T,N>::dim;
        ^
    ../../libs/math/vector.h:277:14: error: expected ';' at end of declaration
    int constexpr Vector<T,N>::dim;
                 ^
                 ;
    ../../libs/math/vector.h:277:22: error: use of undeclared identifier 'T'
    int constexpr Vector<T,N>::dim;
                         ^
    ../../libs/math/vector.h:277:28: error: definition or redeclaration of 'dim' cannot name the global scope
    int constexpr Vector<T,N>::dim;
                             ~~^
    ../../libs/math/vector.h:277:28: error: no member named 'dim' in the global namespace
    int constexpr Vector<T,N>::dim;
                             ~~^
    In file included from batchoperations.cc:22:
    In file included from ../../libs/mve/mesh_io_ply.h:18:
    In file included from ../../libs/mve/image.h:17:
    In file included from ../../libs/math/functions.h:17:
    ../../libs/math/matrix.h:58:25: error: expected ';' at end of declaration list
        static int constexpr rows = N;
                            ^
                            ;
    ../../libs/math/matrix.h:59:16: error: duplicate member 'constexpr'
        static int constexpr cols = M;
                   ^
    ../../libs/math/matrix.h:58:16: note: previous declaration is here
        static int constexpr rows = N;
                   ^
    ../../libs/math/matrix.h:59:25: error: expected ';' at end of declaration list
        static int constexpr cols = M;
                            ^
                            ;
    ../../libs/math/matrix.h:224:5: warning: variable templates are a C++14 extension [-Wc++14-extensions]
    int constexpr Matrix<T,N,M>::rows;
        ^
    ../../libs/math/matrix.h:223:1: error: too many template parameters in template redeclaration
    template <typename T, int N, int M>
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../../libs/math/vector.h:276:1: note: previous template declaration is here
    template <typename T, int N>
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from batchoperations.cc:22:
    In file included from ../../libs/mve/mesh_io_ply.h:18:
    In file included from ../../libs/mve/image.h:17:
    In file included from ../../libs/math/functions.h:17:
    ../../libs/math/matrix.h:224:14: error: expected ';' at end of declaration
    int constexpr Matrix<T,N,M>::rows;
                 ^
                 ;
    ../../libs/math/matrix.h:224:22: error: use of undeclared identifier 'T'
    int constexpr Matrix<T,N,M>::rows;
                         ^
    ../../libs/math/matrix.h:224:30: error: definition or redeclaration of 'rows' cannot name the global scope
    int constexpr Matrix<T,N,M>::rows;
                               ~~^
    ../../libs/math/matrix.h:224:30: error: no member named 'rows' in the global namespace
    int constexpr Matrix<T,N,M>::rows;
                               ~~^
    ../../libs/math/matrix.h:227:5: warning: variable templates are a C++14 extension [-Wc++14-extensions]
    int constexpr Matrix<T,N,M>::cols;
        ^
    ../../libs/math/matrix.h:226:1: error: too many template parameters in template redeclaration
    template <typename T, int N, int M>
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../../libs/math/vector.h:276:1: note: previous template declaration is here
    template <typename T, int N>
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from batchoperations.cc:22:
    In file included from ../../libs/mve/mesh_io_ply.h:18:
    In file included from ../../libs/mve/image.h:17:
    In file included from ../../libs/math/functions.h:17:
    ../../libs/math/matrix.h:227:14: error: expected ';' at end of declaration
    int constexpr Matrix<T,N,M>::cols;
                 ^
                 ;
    ../../libs/math/matrix.h:227:22: error: use of undeclared identifier 'T'
    int constexpr Matrix<T,N,M>::cols;
                         ^
    ../../libs/math/matrix.h:227:30: error: definition or redeclaration of 'cols' cannot name the global scope
    int constexpr Matrix<T,N,M>::cols;
                               ~~^
    ../../libs/math/matrix.h:227:30: error: no member named 'cols' in the global namespace
    int constexpr Matrix<T,N,M>::cols;
                               ~~^
    In file included from batchoperations.cc:22:
    In file included from ../../libs/mve/mesh_io_ply.h:20:
    ../../libs/mve/view.h:82:23: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]
            bool is_dirty = false;
                          ^
    ../../libs/mve/view.h:89:23: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]
            bool is_dirty = false;
                          ^
    ../../libs/mve/view.h:102:29: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]
            bool is_initialized = false;
                                ^
    ../../libs/mve/view.h:103:23: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]
            int32_t width = 0;
                          ^
    ../../libs/mve/view.h:104:24: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]
            int32_t height = 0;
                           ^
    ../../libs/mve/view.h:105:26: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]
            int32_t channels = 0;
                             ^
    ../../libs/mve/view.h:106:24: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]
            ImageType type = IMAGE_TYPE_UNKNOWN;
                           ^
    ../../libs/mve/view.h:116:23: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]
            bool is_dirty = false;
                          ^
    ../../libs/mve/view.h:128:29: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]
            bool is_initialized = false;
                                ^
    ../../libs/mve/view.h:129:23: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]
            uint64_t size = 0;
                          ^
    In file included from batchoperations.cc:22:
    ../../libs/mve/mesh_io_ply.h:52:24: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]
        bool format_binary = true;
                           ^
    ../../libs/mve/mesh_io_ply.h:53:30: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]
        bool write_vertex_colors = true;
                                 ^
    ../../libs/mve/mesh_io_ply.h:54:31: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]
        bool write_vertex_normals = false;
                                  ^
    ../../libs/mve/mesh_io_ply.h:55:35: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]
        bool write_vertex_confidences = true;
                                      ^
    ../../libs/mve/mesh_io_ply.h:56:30: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]
        bool write_vertex_values = true;
                                 ^
    ../../libs/mve/mesh_io_ply.h:57:28: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]
        bool write_face_colors = true;
                               ^
    ../../libs/mve/mesh_io_ply.h:58:29: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]
        bool write_face_normals = false;
                                ^
    ../../libs/mve/mesh_io_ply.h:59:36: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]
        unsigned int verts_per_simplex = 3;
                                       ^
    21 warnings and 18 errors generated.
    make: *** [build/batchoperations.o] Error 1

**Please advise!**

**Comment by flanggut** [comment]
You're compiling against qt4, but you need qt5. 
```
brew uninstall qt
brew link --force qt5
```
If you still run into issues, please try [this](https://github.com/simonfuhrmann/mve/wiki/Build-Instructions-for-OS-X#toubleshooting) first.
