### ISSUE TITLE
How to use makescene for converting OpenMVG outputs?

### ISSUE THREAD

**Issue by zharvey-welltok** [simonfuhrmann/mve#262]
So I have run OpenMVG on some sample photos and generated a `sfm_data.bin` and lots of other files/directories as outputs. I am now trying to load these as inputs to `makescene` so I can import them into MVE.

I built MVE on a Ubuntu 14.04 server and see a `~/mve/apps/makescene/makescene` app. When I run it (no arguments), I see a lot of output, ending with:

```
Usage: ./makescene [ OPTIONS ] INPUT OUT_SCENE
Available options: 
  -o, --original        Import original images
  -b, --bundle-id=ARG   Bundle ID (Photosynther and Bundler only) [0]
  -k, --keep-invalid    Keeps images with invalid cameras
  -i, --images-only     Imports images from INPUT_DIR only
  -a, --append-images   Appends images to an existing scene
  -m, --max-pixels=ARG  Limit image size by iterative half-sizing
```

Comparing that to the instructions in your [SfM wiki](https://github.com/simonfuhrmann/mve/wiki/Structure-from-Motion), I can't figure out how to use `makescene` (specifically, what arguments/options to pass it) so that I can convert all of OpenMVG's outputs into something that is compatible with MVE. **Any ideas?**

**Comment by pmoulon** [comment]
makescene is not required. There is a binary in OpenMVG that exports the sfm_data scene as a MVE scene
http://openmvg.readthedocs.io/en/latest/software/MVS/MVE/

**Comment by simonfuhrmann** [comment]
Thanks Pierre.
