### ISSUE TITLE
After meshclean runs, where are the textures for the associated PLY file?

### ISSUE THREAD

**Issue by zharvey-welltok** [simonfuhrmann/mve#263]
Hello,

I imported SfM data from OpenMVG and then ran it through an MVE pipeline like so:

```
directory=/path/to/openMVG_output/MVE
resolution=2

dmrecon -s$resolution $directory
scene2pset -ddepth-L$resolution -iundist-L$resolution -n -s -c $directory $directory/OUTPUT.ply
fssrecon $directory/OUTPUT.ply $directory/OUTPUT_MESH.ply
meshclean $directory/OUTPUT_MESH.ply $directory/OUTPUT_MESH_CLEAN.ply
```

All of those binaries ran fine, indicating success.

I was then able to load the the final PLY file (`OUTPUT_MESH_CLEAN.ply`) into Blender. The problem is, it's just a gray mesh (I only imported the `.ply` file, no textures/images):

<img width="1116" alt="screen shot 2016-10-07 at 4 55 09 am" src="https://cloud.githubusercontent.com/assets/20440748/19184284/5d76cf84-8c4a-11e6-9258-19f251f1b334.png">

Under my MVE `$directory/MVE` folder, I only see:

* `OUTPUT_MESH_CLEAN.ply`
* `OUTPUT_MESH.ply`
* `OUTPUT.ply`
* `synth_0.out`
* `views/view_*.mve` (10 MVE files altogether)

I was expecting to see some PNG/image/texture files in there, or something representing textures. After all, I'd like to be able to load the castle mesh + textures into Blender, not just the mesh. **Any ideas as to where the textures might be hiding, or how I can generate them?**

Thanks in advance!

**Comment by flanggut** [comment]
The regular MVE pipeline only creates vertex colors and does not generate textures for the output mesh. Please have a look at this project if you're looking for high-quality textures: https://github.com/nmoehrle/mvs-texturing.

**Comment by zharvey-welltok** [comment]
Thanks @flanggut - I'll have a look!

**Comment by simonfuhrmann** [comment]
You can also visualize the per-vertex colors in blender. For this you have
to enable "Vertex Paint" in your blender material.

**Comment by zharvey-welltok** [comment]
Thanks @simonfuhrmann - just curious, are the per-vertex colors stored in the PLY file?

**Comment by simonfuhrmann** [comment]
Yes.
