### ISSUE TITLE
Determine camera intrinsics form K matrix and image dimension

### ISSUE THREAD

**Issue by nmoehrle** [simonfuhrmann/mve#273]
Given the current implementation of [fill_calibration](https://github.com/simonfuhrmann/mve/blob/master/libs/mve/camera.cc#L114) it is not possible to determine a pixel aspect ratio and focal length for certain K matrices and image dimension combinations.

Given a K matrix:
```
ax    0     width * ppx
0     ay    height * ppy
0     0     1
```
It is not possible to find values for the focal length and pixel aspect ratio if the pixel aspect ratio changes the image aspect ratio.

For "landscape" images (width / height >= 1.0) this happens if ax / ay > width / height >= 1.0
and for "portrait" images (width / height < 1.0) this happens if 1.0 > width / height > ax / ay.

Note that ax and ay determine the pixel aspect ratio, it is either ay / ax in the [landscape](https://github.com/simonfuhrmann/mve/blob/master/libs/mve/camera.cc#L127) or ax / ay in the [portrait](https://github.com/simonfuhrmann/mve/blob/master/libs/mve/camera.cc#L121) case.

The issue is that the pixel aspect ratio has an influence on whether a camera is considered a landscape or portrait camera.

Example:
```
ax = 14, ay = 12, width = 10, height = 9, ppx = 0.5, ppy = 0.5
```
The K matrix is:
```
14    0     5
0     12    4.5
0     0     1
```

Assuming landscape:
```
flen = ax / width = 14 / 10 = 1.4
paspect = ay / ax = 12 / 14 = 0.85
```
Calculating corresponding K matrix entries:
```
image_aspect = width / height * 0.85 = 0.95 -> portrait
ax = flen * height / paspect = 10.7
ay = flen * height = 12.6
```

Assuming portrait:
```
flen = ay / height = 12 / 9 = 1.33
paspect = ax / ay = 14 / 12 = 1.16
```
Calculating corresponding K matrix entries:
```
image_aspect = width / height * 1.16 = 1.28 -> not landscape
ax = flen * width = 13.3
ay = flen * width * paspect = 15.4
```

**Comment by flanggut** [comment]
> Note that ax and ay determine the pixel aspect ratio, it is either ay / ax in the landscape or ax / ay in the portrait case.

I'm not sure what you're trying to say? As far as I can see `ay/ax == paspect` in both cases [here](https://github.com/simonfuhrmann/mve/blob/master/libs/mve/camera.cc#L119)

**Comment by nmoehrle** [comment]
Yes my mistake - Thanks
