### ISSUE TITLE
How to capture a virtual rephoto?

### ISSUE THREAD

**Issue by NicksonYap** [simonfuhrmann/mve#274]
Hi guys,
I've tried MVE successfully on Linux.
Thanks Simon for the efforts :)

I understand that the virtual rephoto can be used to compare with the original photo to evaluate the reconstruction through the following link:
https://ibmr-benchmark.gcc.informatik.tu-darmstadt.de/

I should potentially be able adjust the angles and position of the virtual camera and capture to align with previously taken photos and produce a timelapse.

So question is, how do I do this with MVE? Or is there another software for this?

My guess is to extract camera parameters from SFM results...

Thanks!

**Comment by flanggut** [comment]
You can use UMVE to do this, [see the menu on the right] (http://imgur.com/a/tbQiU).
The code for this part is [here](https://github.com/simonfuhrmann/mve/blob/master/apps/umve/scene_addins/addin_rephotographer.cc).
