### ISSUE TITLE
Segmentation fault.

### ISSUE THREAD

**Issue by supertobi** [simonfuhrmann/mve#276]
I compiled umve an run it, then I created a new scene and imported 16 photos. Then umve crashed. If I now try to start umve I get:

$ ./umve 
Segmentation fault (core dumped)
Or:
$ ./umve 
QWidget::paintEngine: Should no longer be called
QWidget::paintEngine: Should no longer be called
Segmentation fault (core dumped)

Run in gdb I got this bt:

$ gdb ./umve 
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./umve...done.
(gdb) run
Starting program: /home/tobias/dev/mve/apps/umve/umve 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffebad6700 (LWP 28785)]
[New Thread 0x7fffdd5c2700 (LWP 28787)]
[New Thread 0x7fffdcdc1700 (LWP 28788)]
[New Thread 0x7fffd7fff700 (LWP 28789)]
[New Thread 0x7fffd77fe700 (LWP 28790)]

Thread 1 "umve" received signal SIGSEGV, Segmentation fault.
0x00007ffff6f63f50 in QLayout::widgetEvent(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
(gdb) bt
#0  0x00007ffff6f63f50 in QLayout::widgetEvent(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#1  0x00007ffff6f4302e in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#2  0x00007ffff6f48516 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#3  0x00007ffff665038b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007ffff6f9fcc4 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007ffff6fa2bb3 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007ffff6f4305c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff6f48516 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007ffff665038b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007ffff698f4bf in QGuiApplicationPrivate::processGeometryChangeEvent(QWindowSystemInterfacePrivate::GeometryChangeEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#10 0x00007ffff699429d in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#11 0x00007ffff6977f08 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#12 0x00007ffff7e99060 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#13 0x00007ffff25c81a7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007ffff25c8400 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007ffff25c84ac in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff66a67cf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff664db4a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007ffff6655bec in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x0000000000448575 in main ()
(gdb) 

My system:
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609

$ uname -or
4.4.0-45-generic GNU/Linux

$ lsb_release -irc
Distributor ID: Ubuntu
Release: 16.04
Codename: xenial

**Comment by simonfuhrmann** [comment]
I don't really know what is going here. Is your OpenGL properly running in other applications?

**Comment by supertobi** [comment]
I've just tested some qt5 3D examples, and they work. Blender and other 3D programs work too.

**Comment by simonfuhrmann** [comment]
The backtrace itself doesn't really give any code point we have control over, i.e., doesn't indicate a crash in one of our files. I believe it is NOT related to OpenGL, since your other programs seem to work fine and we initialize OpenGL late, only when you manually click on "Scene Inspect". So I honestly don't know what is happening here and why. Sorry.

**Comment by supertobi** [comment]
Just some more infos about the OpenGL driver on my system:

$ glxinfo | grep "version"
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 3.3
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL core profile version string: 3.3 (Core Profile) Mesa 11.2.0
OpenGL core profile shading language version string: 3.30
OpenGL version string: 3.0 Mesa 11.2.0
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 11.2.0
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00

$ glxinfo | grep -i opengl
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 11.2.0
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 11.2.0
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 11.2.0
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:

**Comment by supertobi** [comment]
Is there a flag to get more debug output from umve?

**Comment by supertobi** [comment]
Now I had thee idea to run umve with valgrind. This is the output:

[valgrid.txt](https://github.com/simonfuhrmann/mve/files/600761/valgrid.txt)

**Comment by simonfuhrmann** [comment]
Can you try to launch it on another Linux installation?

**Comment by supertobi** [comment]
No, sorry I don't have a 2nd system.

**Comment by simonfuhrmann** [comment]
Sorry we couldn't help. I'm closing this. Feel free to reopen if you have updates.
