### ISSUE TITLE
Question: where is SIFT matching-threshold defined?

### ISSUE THREAD

**Issue by lexvandersluijs** [simonfuhrmann/mve#277]
Hi,

First of all, thanks for publishing such a great package of tools! I'm getting great results with the 'standard' matte / heavily textured objects. 

Currently I'm doing an experiment to see if it is possible to create a sparse point cloud of an object with somewhat glossy surfaces (like car paint). These are therefore somewhere between completely matte and completely reflective. The problem is of course that the 'brightness-constancy for different viewing directions' assumption does not hold: the surface has a slightly different appearance for each direction.

However, the appearance does not change _completely_ of course (unless there is a strong highlight, that scenario is out of scope here). The patch will get darker and ligher locally, so gradient magnitudes will change, but the gradient _direction_ will approximately stay the same. 

I would like to try to change the SIFT-matching threshold, to see if 2D-2D correspondences that would normally be discarded can then be found again. There will be more false positives, so there will more work to find the pose that matches, meaning the process likely takes more time. But if the result is good, then this is not a problem.

So my question is: where could I change this matching threshold in MVE? After browsing through the source code I wasn't able to find it yet. I'll report back with some results if you're interested.

Best regards,
Lex

**Comment by simonfuhrmann** [comment]
There are several thresholds for SIFT and SURF which cannot be configured via command line. But you can play with it by editing the code. Here you can set the options for `FeatureSet` (`feature_set.h`), which does the feature extraction.

https://github.com/simonfuhrmann/mve/blob/master/apps/sfmrecon/sfmrecon.cc#L94

It contains members for `Sift::Options` and `Surf::Options` which you can set to your feature extraction needs. Then there are two thresholds for matching itself (in `matching.h`), the Lowe ratio and the feature distance. We don't use the latter, and the former is hard-coded here:

https://github.com/simonfuhrmann/mve/blob/master/libs/sfm/matching_base.h#L27

I hope this helps.

**Comment by lexvandersluijs** [comment]
Hi Simon,

Thanks a lot for your answer, I'm going to give it a go.

BR,
Lex
