### ISSUE TITLE
Option to mask out certain pixel values?

### ISSUE THREAD

**Issue by bsugerman** [simonfuhrmann/mve#278]
I'm loving this software suite! I have imaged in which some regions are saturated and would benefit from being masked out. I'm curious if there is a hidden feature to have a routine ignore certain pixel values?  I know that I can create a single mask image for the MVE, but that doesn't really apply here.  My particular problem is that saturated regions aren't always cleaned by meshclean, because their edges generate extruded point clusters pointing right at toward the camera, which the cleaner thinks are real.

Thanks!!!

-ben

**Comment by simonfuhrmann** [comment]
You can create mask for each image and the masked pixels will not be exported when you use `scene2pset`. I am not sure if this is the mask feature you were mentioning. Other than this, there is no option to mask. I don't yet full understand what, or where exactly you want to apply a mask. Can you clarify?

**Comment by bsugerman** [comment]
Thank you for your quick reply!!! Suppose I have a group of images called 001.jpg, 002.jpg, etc, all sitting in a directory called "images."  Each image has its own bad pixels I need to mask out, because of noise or changing lighting or whatever.  I can think of a few options for masking out bad pixels in each image. 

1. Create a "bad bit" flag in the software to ignore pixels of a certain value, such as --badbit=0. The user could pre-process each image to set bad pixels to 0. 

2. Create a mask image for each input image, with the same name but in a new directory. i.e. masks/001.jpg, masks/002.jpg, ..., and the software asks for the directory name where masks are held. 

3. Create a mask for each image using the image name and a given suffix, i.e. 001_msk.jpg, 002_msk.jpg, ...  the masks are kept in the images/ directory and the software is given the suffix for the masks. 

Does your software currently allow any of those options? 

-ben

**Comment by simonfuhrmann** [comment]
The bad pixels don't harm SfM or MVS reconstruction. In MVS, you might get some false matches. And you *can* ignore these regions when you convert the depth maps to a point cloud with `scene2pset` using masks. Just add a one-channel image to each view directory and make it black in regions you want to mask out. Points are re-projected into the mask and if the mask is black, the point is not emitted.

Make sure your masked out regions are larger than the actual defective region because MVS uses patches of size 5x5 (if you use the default value). So make your mask 5x5 pixels around every defective pixel.

**Comment by bsugerman** [comment]
If I understand you correctly, I would put one single mask in the directory
and every image would refer back to it using the transformations found in
sfmrecon and dmrecon?  In that case, the mask should be registered to a
given image in the set...which one?

The problem I am having is that there is a part of my particular scene that
is always saturated (pixel values all 255), because of the lighting. As a
result, the edges of that region have been rendered as very long
protrusions pointing directly toward the observer. For this particular
project, I suspect that your method (one single mask works for the whole
image set) could work. But if there are only some of the images where a
region is saturated, and in other images that particular region is
unsaturated, I worry about the saturated pixels influencing the 3-d
reconstruction.  That is why I think it could be very useful to either
allow a different mask to be associated to each image, or a flag to ignore
pixels of a given value in each image.  If I were using mac os x or linux,
I would very happily go into the source code and add this functionality and
pass it back to you, but unfortunately I'm so much of a newbie with windows
that I haven't yet tried to edit and recompile. That's why I brought this
possible feature to your attention. :-)

-ben

**Comment by simonfuhrmann** [comment]
I wrote: "Just add a one-channel image (`NAME.png`) to each view directory...".
It is per view.

**Comment by bsugerman** [comment]
You know, it finally makes sense. All my images are held in a given folder,
but makescene.exe moves each image to its own subdirectory inside the
views/ directory. So I just make a file called e.g. mask.png in each of
those .mve directories.

Would you mind if I edited the Users Guide wiki a little to make this more
clear to future users?

-ben

**Comment by simonfuhrmann** [comment]
Sure go ahead.
