### ISSUE TITLE
FSSR with a set of 3D points

### ISSUE THREAD

**Issue by LUYUJIA** [simonfuhrmann/mve#281]
Hi Simon
I am a beginner in MVE. I have a question that whether it's possible to reconstruct a surface with a set of 3D points by FSSR, no normals, no scale values, only coordinates. If it's possible how can I calculate normals and scale values? 

looking forward to your reply.

**Comment by simonfuhrmann** [comment]
Generally, no, it is not possible. You need at least normals and scales. Computing normals consistently is not trivial (see Hoppe's classical work on Surface Reconstruction). Scales can be reconstructed from density, but the point we are making in the paper is, that thia not the correct thing to do in general.

**Comment by LUYUJIA** [comment]
A helpful reply, thank you so much. Since it is not possible,  I found another paper that Surface reconstruction from unorganized points - Hugues Hoppe. What is the difference? does it work?
could you give me some advices about this situation that only have coordinates of 3D points.  

appreciate it.

**Comment by simonfuhrmann** [comment]
This is the work I was talking about. This approach also requires normals, but they are estimated as part of the algorithm. I would say it is generally better to estimate the normals using their approach, and use PSR or SSD for surface reconstruction.

**Comment by LUYUJIA** [comment]
Thanks for your clear explanation, I have figured it out. :) 👍
