### ISSUE TITLE
SiftGPU

### ISSUE THREAD

**Issue by mgumley** [simonfuhrmann/mve#282]
First of all, thank you for spending so much time to write an excellent tool and open source it.

My company has been evaluating this software and another similar one named VisualSFM ( http://ccwu.me/vsfm/ )

We are specifically interested in the ability to recover extrinsic camera information (location + rotation over time) from a series of images taken by a single camera. The sfmrecon program does a fine job at this, but it is at least **10 times slower** than VisualSFM. I believe this can be attributed to the way VisualSFM utilizes the GPU.  It uses SiftGPU ( http://cs.unc.edu/~ccwu/siftgpu/ ) , compared to MVE using what appears to be a custom implementation of Sift.

I am considering trying to integrate SiftGPU into the MVE project, but I first wanted to get your thoughts on the issue. 
 
- Is there an easier way that MVE can get the results we need, faster?
- Have you attempted using SiftGPU?
- Do you think it would provide a significant speed advantage?
- Is there a reason not to use it, such as accuracy?

Cheers,
Maxwell Gumley

**Comment by simonfuhrmann** [comment]
We are aware of SiftGPU but it was a conscious decision to not put any GPU code in MVE. It makes the code more difficult to compile and maintain. Further, I don't think that SiftGPU is increasing performance by a lot: Feature extraction itself is much faster than our CPU implementation of SIFT, but on computers with many CPU cores, the CPU bound version has its advantages.

The most time-consuming step in SfM reconstruction is matching, not feature extraction, as matching is quadratic in the number of images. Have you tried using our cascade hashing implementation?

Try running `sfmrecon --cascade-hashing SCENE`.

**Comment by simonfuhrmann** [comment]
I am closing this for now. Feel free to reopen if needed.
