### ISSUE TITLE
OpenMVG to MVE, problem with scene2pset?

### ISSUE THREAD

**Issue by andykorth** [simonfuhrmann/mve#284]
I have an image set I'm trying to run MVE on, and it fails to produce a mesh, and the point cloud looks obviously wrong. The dataset is 37 pictures of a tennis court, taken mostly straight down by a DJI drone.

I've also used the output of OpenMVG in other software, and the data coming out of OpenMVG works pretty well elsewhere.

I followed the instructions here: https://openmvg.readthedocs.io/en/latest/software/MVS/MVE/

OpenMVG created a pretty good colorized set of points: 
http://kortham.net/temp/colorized.ply

Here's the point set viewed side-on:
![Meshlab of OpenMVG](http://kortham.net/temp/upshot_o8LIeSWY.png)

As expected, the points were all approximately co-planar.. which is sometimes a challenge to stitch. We project the OpenMVG camera positions and orientations onto a mesh we have from another source and get okay results:
![Our software](http://kortham.net/temp/upshot_M0DFwsvO.png)

Now, we'd like to use the OpenMVG results in MVE, so we run:

```
openMVG_main_openMVG2MVSTEXTURING -i $RECONSTRUCTION/sfm_data.bin -o $OUT/toMVSTex
```

which produces a folder of views. 

Followed by:

```
resolution=2

mve/apps/dmrecon/dmrecon -s$resolution $directory
mve/apps/scene2pset/scene2pset -ddepth-L$resolution -iundist-L$resolution -n -s -c $directory $directory/MVG_OUTPUT.ply
```

Which produces this problematic output. I expected it to look like the point cloud generated by OpenMVG.
![Meshlab of MVE](http://kortham.net/temp/upshot_0ZcMQNv5.png)
http://kortham.net/temp/MVG_OUTPUT.ply

And you can continue along with the mesh generation.... 
![Icky Mesh](http://kortham.net/temp/upshot_YxDPNi1u.png)

And the cleaned mesh contains zero elements.

So it seems like something went wrong either in the scene2pset, or perhaps the dmrecon stage. Any ideas?

Here's the output of MVE, and the options I used (basically just the defaults recommended in the docs)
https://gist.github.com/andykorth/397df0cfb4700e2182cdea10135e8fcb
Here's the download for all the files, in case that's helpful:
http://kortham.net/temp/DJITennis512Points.zip

Thanks in advance for your time!

**Comment by pmoulon** [comment]
One of the possible reason of the failure could be due to the usage of large coordinates.
The OpenMVG gps registration make the SfM coordinate system using very large coordinates.
Perhaps MVE does not like to have this large coordinates.

Did you tried the scene without GPS registration?

**Comment by andykorth** [comment]
Ahh, good suggestion. I will try converting or adjusting the coordinates and post my findings. Thanks!

**Comment by andykorth** [comment]
Much better! 

My old `views/view_0000.mve/meta.ini` files included a line like:
```
translation = -306083 82647.6 6.37053e+06 
```

So there's clearly not enough precision in those floats. When fixed (dropping the -P from openMVG_main_SfMInit_ImageListing), OpenMVG outputs much better data, like:

```
translation = -0.935551 1.13465 -0.168783 
```

Here's the new point cloud!
![Point Cloud](http://kortham.net/temp/upshot_5EBlkA3U.png)

Thanks for your help!

**Comment by pmoulon** [comment]
I would be worth it to see if exporting the camera position with its full precision would leads to the good result.
See here https://github.com/openMVG/openMVG/blob/develop_geodesy/src/openMVG/sfm/sfm_data_io_ply.hpp#L56

**Comment by simonfuhrmann** [comment]
Yes, @pmoulon, that what I was going to say. Maybe we can try adding a `--normalize` flag to the MVE exporter and see if that helps?
