### ISSUE TITLE
could you disclose the parameters used in the reconstruction pipeline for your own public dataset?

### ISSUE THREAD

**Issue by autosquid** [simonfuhrmann/mve#286]
MVE is a cool tool, and also the public dataset is awesome. 

I noticed you gave gave an example on how to use MVE in [Let There Be Color! – Large-Scale Texturing of 3D Reconstructions](http://www.gcc.tu-darmstadt.de/home/proj/texrecon/index.en.jsp).

 However, there are many parameters to tune,  and I am wondering if all the parameters for each dataset the same? Could you kindly disclose the parameters for each public dataset for reconstructions? (I am trying to reproduce your results for a paper publication)

**Comment by simonfuhrmann** [comment]
Parameters for which parts of the pipeline? Usually for `sfmrecon`, no parameter tuning is necessary if it reconstructs properly. With `dmrecon` you only want to control the size of the resulting depth maps (`-s` parameter). Then `scene2pset` needs the appropriate scale(s), and `fssrecon` works without parameters. `meshclean` needs a bit of experimentation with `-t` and `-c`. Regarding texturing, @nmoehrle can probably help.

**Comment by autosquid** [comment]
@simonfuhrmann  thanks for your information.

As you explained, I simply ignored parameters other than  `-s` `-F` `-t -c`, however,  the values of the four parameters still seems a bit misterious to me: what values would you recommand (or did you use) for **each** of the four datasets? Are they all the same (which are 3,3, 10, 10000 respectively)?

**Comment by simonfuhrmann** [comment]
Well, `-s` for dmrecon controls how large, or detailed, the depth maps are. Usually we use `-s2`. Larger values will lead to smoother but more complete reconstructions. It all depends on the image size, but for the majority of photos (6-12MP) `-s2` is what we use. `-s1` leads to pretty accurate and high-resolution reconstructions at much higher computation time with many of holes, so we usually avoid that. Note that you can also compute reconstructions on multiple scales, export each of them with `scene2pset` and combine then with `fssrecon`. This often gives nice results.
