### ISSUE TITLE
How to use sfm reconstruct in the umve.exe

### ISSUE THREAD

**Issue by lishi0927** [simonfuhrmann/mve#287]
Hi, 
I don't know how to use sfm reconstruct function in the umve, and I have found that my UMVE UI is a little different with the paper figure, my UMVE is lack of sfm reconstruct tab. So How to solve this problem?
Thank you!
![image](https://cloud.githubusercontent.com/assets/7486571/21095704/a6d4b30e-c097-11e6-9ab5-86e6c2a9cc0d.png)

**Comment by simonfuhrmann** [comment]
The UI doesn't provide this feature anymore. Please use the command line utils for this task. Here is the users guide:
https://github.com/simonfuhrmann/mve/wiki/MVE-Users-Guide
