### ISSUE TITLE
"Viewports/scene size mismatch" error trying to run sfmrecon incrementally

### ISSUE THREAD

**Issue by mikeroberts3000** [simonfuhrmann/mve#289]
Hello there,

I have a quick silly question about running the MVE pipeline in incremental mode. I understand that I can append images to an existing MVE scene with the -a flag, e.g.,

```
makescene -i path/to/image_batch_0 path/to/mve_scene
sfmrecon path/to/mve_scene
makescene -i -a path/to/image_batch_1 path/to/mve_scene
sfmrecon path/to/mve_scene
```

However, when I run ```sfmrecon``` for the second time in this example, I get the following error,

```
MVE SfM Reconstruction (built on Oct  6 2016, 17:41:19)
SSE2 accelerated matching is enabled.
SSE3 accelerated matching is enabled.
Initializing scene with 75 views...
Initialized 75 views (max ID is 74), took 4ms.
Loading pairwise matching from file...
Cleanup: Released 0 embeddings in 0 of 75 views.
Initializing camera intrinsics...
Viewports/scene size mismatch
```

How do I run ```sfmrecon``` in incremental mode? Am I missing some command line argument to make this work correctly?

Of course I could just delete the ```prebundle.sfm``` and ```synth.out``` files, and run ```sfmrecon``` from scratch, but this would throw away all the computational effort from the first run of ```sfmrecon``` in the above example.

**Comment by simonfuhrmann** [comment]
Good question. I am not sure if this is currently possible, and for what reason the incremental mode in makescene has been added. I can give it a look, but it has to wait until next year.

**Comment by mikeroberts3000** [comment]
Ah, no worries. Best of luck with your SIGGRAPH submission and/or holidays 😄

If anyone reads this and is looking for a quick workaround, VisualSFM can be run in incremental mode. I'm currently using VisualSFM's sfm+resume+fixcam command line options to solve the SfM problem incrementally as I add batches of images, and then I'm using MVE for the rest of my reconstruction pipeline. This seems to be doing the trick. I'll leave this issue open though because it's probably worth digging into at some point.

**Comment by gundeepsingh1** [comment]
I am facing the same issue. Not able to perform incremental sfm manually.

**Comment by simonfuhrmann** [comment]
MVE does not support manual incremental SfM. At this point, we also don't support using `makescene` incrementally (i.e., adding views to a scene) and then running `sfmrecon` again. Sorry about that.
