### ISSUE TITLE
[Question] Meta.Ini and generate a camera

### ISSUE THREAD

**Issue by stephane-lb** [simonfuhrmann/mve#290]
Hi Simon and MVE's developers,

I read the documentation about the new directory format you use to store parameters for each camera. And I do not understand what is a "**normalised**" focal length. For example in my current experiment I have a focal length equal to 1.16, if it is 1.16 mm it is wird.  I am used to work with virtual cameras in OpenGL or with Pathtracers, and I would like to be able to generate a virtual camera at the same position as one of my picture.

Could you help me please and provide a little bit more details on how to use it ? 

Thanks,

Stephane-lb

**Comment by simonfuhrmann** [comment]
Hi Stephane,

the normalized focal length doesn't have a unit. For example, if you have a 42mm lens on a 35mm sensor, you get a normalized focal length of 42mm/35mm = 1.2. And ultimately, this is the distance from the camera center to the image plane, if the image plane is [a square of] size 1.

We might add this explanation to the math cookbook.
https://github.com/simonfuhrmann/mve/wiki/Math-Cookbook

**Comment by simonfuhrmann** [comment]
Remark: If you want to compute the camera FOV from the focal length, use trigonometry like this, where w=1 and f is the normalized focal length.

**Comment by stephane-lb** [comment]
Hi Simon,

Thanks you very much for your help! If anyone as similar question :
fov = 2 * atan( .5 / f ) * 180 / pi

**Comment by simonfuhrmann** [comment]
Make sure you cover the case where images are portrait / landscape. This formula will give you the FOV of the longer image side, as the longer side will be normalized to 1.
