### ISSUE TITLE
camera from bundler

### ISSUE THREAD

**Issue by autosquid** [simonfuhrmann/mve#294]
I am having problem in calculation  *view_dir* in CameraInfo.

I made some investigation, and here is what I found and my question:

 
The camera in bundler is facing -z, which is different from Visual Sfm or mve. where is the code to convert the camera parameters from a bundler bundle into mve's (stored in meta.ini)?

**Comment by simonfuhrmann** [comment]
The code that converts from the bunder format to MVE is here:
https://github.com/simonfuhrmann/mve/blob/master/apps/makescene/makescene.cc#L566

As you can see, for Bundler, there is no conversion happening. Meaning that the rotation and translation is exactly the same as in MVE.

**Comment by autosquid** [comment]
Thanks for your quick reply. I guess you meant lines staring from L572: https://github.com/simonfuhrmann/mve/blob/master/apps/makescene/makescene.cc#L572 

It indeed solves my question about the view direction. However, another related question (still for noah bundler camera):

In `CameraInfo::fill_calibration`, `ppoint` is used to fill camera intrinsics， which for noah bundler camera should be 0, according to the projection function: 

![image](https://cloud.githubusercontent.com/assets/758925/21918815/383fbef4-d990-11e6-977f-5928315b4e64.png)



[source: http://www.cs.cornell.edu/~snavely/bundler/bundler-v0.4-manual.html#S6]

The problem is the default value for `ppoint` is (0.5, 0.5), so for noah bundler camera, where the code to reset it to (0,0)? (I tried, but could not find it :( )

**Comment by simonfuhrmann** [comment]
Indeed I meant L572, and there is conversion happening. Regarding the principal point, the Noah bundler does not optimize for this. Most SfM systems don't optimize the principal point, and neither does MVE. The MVE default is (0.5, 0.5), which is the center of the image.

**Comment by autosquid** [comment]
so, does that mean we have to set `ppoint` to be (0,0) when converting a Noah camera in lines following L572? In that way, the ppoint in meta.ini would also be set to (0,0) explicitly.

**Comment by autosquid** [comment]
Sorry, I missed the part of viewport transformation, thing are now clear.

By the way, I did some math, and it seems we only have to negtive R[0:3] and T[0] in the conversion function starting from L572 to adapt a Noah camera.

**Comment by simonfuhrmann** [comment]
If it doesn't make a difference, I'd keep the current code for safety reasons :)
