### ISSUE TITLE
Apps: prebundle.cc license is GPL or BSD?

### ISSUE THREAD

**Issue by s-wtnb** [simonfuhrmann/mve#295]
hi,

MVE is cool apps!
I ask about this issue.

bundler_incremental.cc
sfmrecon.cc
```
 * This software may be modified and distributed under the terms
 * of the GPL 3 license. See the LICENSE.txt file for details.
```

others
```
 * This software may be modified and distributed under the terms
 * of the BSD 3-Clause license. See the LICENSE.txt file for details.
```

**prebundle.cc**
```
 * This software may be modified and distributed under the terms
 * of the GPL 3-Clause license. See the LICENSE.txt file for details.
```

thx.

**Comment by simonfuhrmann** [comment]
`prebundle.cc` is actually BSD. I changed the license. If you want a completely GPL free version of MVE, check out the `imba` branch. We still have to merge some recent changes into this branch, however.

**Comment by simonfuhrmann** [comment]
Let me correct: `prebundle.cc` is GPL because it links with the sfm library. The sfm library contains GPL code (pba in particular, and everything that includes it). If you want a completely GPL-free version of MVE, check out the `imba` branch. We have to merge some recent changes into this branch, however.

**Comment by ssampang** [comment]
Hi,

I can't find the imba branch on github. Was it discontinued? I'm interested in a GPL-free version of MVE.

Thanks!

**Comment by ssampang** [comment]
Looking at the other branches, I see that one of the has a LICENSE.txt file which includes the GPL license. Since the LICENSE.txt file on the master branch doesn't include the GPL license, does this mean that all code (except sift and surf) on the master branch is contained under the BSD license?

**Comment by simonfuhrmann** [comment]
We recently moved our `imba` branch to `master`. The old `master` branch is still accessible under `pba`. The new `master` branch doesn't contain GPL code. Even SIFT and SURF are BSD, but may be patented.
