### ISSUE TITLE
umve needs a user guide

### ISSUE THREAD

**Issue by mardy** [simonfuhrmann/mve#296]
Hi there!
  Thanks for this project, I tried reconstructing a scene from the command line and it worked much better than similar products :-)
However, I didn't understand how to use umve: I created a new scene, imported the images, but then I don't know what to do. I don't find any way to run sfmrecon from the GUI.

Also, do you happen to have a mailing list or discussion forum? I think that such questions would be more appropriate there. :-)

**Comment by simonfuhrmann** [comment]
UMVE is just for inspecting the scene. It cannot reconstruct anything, except depth maps. At this point it's probably best and least confusing if we remove the import images feature...
