### ISSUE TITLE
Using openMVE as a third party library

### ISSUE THREAD

**Issue by naveenjafer** [simonfuhrmann/mve#300]
Hi, I intend to try a small demo application using a few libraries of openMVE, what would be the procedure to link the libraries as target libraries in my cmake file for the application created?

**Comment by flanggut** [comment]
Hi, we do not use cmake as a build environment, so you have to write your own cmake files. [This fork](https://github.com/andre-schulz/mve/tree/cmake) might have some helpful examples.

**Comment by simonfuhrmann** [comment]
Please refer to the cmake docs how to do that. We don't use cmake. 

If you just want to write a small demo application, consider copying the `Makefile` from one of the applications in `apps/` and don't use cmake yourself.

**Comment by naveenjafer** [comment]
I'll do that, Thank you :)
