### ISSUE TITLE
How to do SFM if I just know the landmarks on face images?

### ISSUE THREAD

**Issue by wguo68** [simonfuhrmann/mve#303]
For example if I have 6 landmarks (eye corner ,mouth corners ... )on each images
The SIFT feature detection and matching can't work for facial images. But We can use other libs to detect facial landmarks. How to use mve to do SFM and then 3d reconstruction?

**Comment by simonfuhrmann** [comment]
You would have to provide a `prebundle.sfm` file for your landmarks, and then run `sfmrecon` which will skip feature detection and matching if the prebundle is provided. See here for how the file format works:
https://github.com/simonfuhrmann/mve/blob/master/libs/sfm/bundler_common.cc#L54
