### ISSUE TITLE
Qt5 link no longer valid

### ISSUE THREAD

**Issue by ahsteven** [simonfuhrmann/mve#305]
Hi I am trying to install the umve on windows. When I build the solution I get the error qt download failed.
The link is no longer valid.
set(QT5_URL "https://download.qt-project.org/official_releases/qt/5.5/5.5.1/single/${QT5_FILENAME}")

I installed Qt 5.8 for Visual studio 2015 64 seperately. How can I get cmake to recognize it when building mve so that umve gets installed?

**Comment by andre-schulz** [comment]
Hi @ahsteven,
I haven't gotten around to updating the Qt5 URL yet. In the meantime, you can try the following URL instead: https://download.qt.io/archive/qt/5.5/5.5.1/single/${QT5_FILENAME}

**Comment by andre-schulz** [comment]
Fixed in andre-schulz@21630071620964bec0baaefd2cb51e7d81cf7c58

**Comment by Yzhbuaa** [comment]
Hi, @andre-schulz. Sorry to trouble you, but again, the Qt5 link seems no longer valid. How can I get an up-to-date URL of Qt5? Thank you!
![image](https://user-images.githubusercontent.com/44798666/87415332-8c55ff80-c5ff-11ea-8602-b50c5b951b69.png)

**Comment by andre-schulz** [comment]
Hi @Yzhbuaa,
no problem, I've fixed the link in andre-schulz@a098a94cee6d9df92f564c5966fd04d34a37c7c8.
Have a nice day!

**Comment by Yzhbuaa** [comment]
@andre-schulz Thanks for your instruction, I've built mve on win10 successfully!
