### ISSUE TITLE
How do I evaluate actual mse?

### ISSUE THREAD

**Issue by tmac1002** [simonfuhrmann/mve#308]
Hi, Simon

I saw your mve adopt PBA and normalized coordinate. But when after BA, how do I know the actual mse. 
The mse in your software just did not represent the actual pixel mse. I just want to know how we transfer it? Thank you very much!

**Comment by simonfuhrmann** [comment]
The image coordinates are normalized by max(width, height). So I believe you just have to multiply the normalized MSE with max(width, height)^2 to obtain the MSE in pixel units.

**Comment by flanggut** [comment]
If all images have the same size this works. If they have different sizes you have to write some code  that computes the unnormalized MSE. It's not that difficult - you can use the first loop in [this](https://github.com/simonfuhrmann/mve/blob/master/libs/sfm/bundler_incremental.cc#L413) function and just denormalize the coordinates before you compute the error in L445 and sum up everything for all tracks.
