### ISSUE TITLE
MVE Options

### ISSUE THREAD

**Issue by john-davies** [simonfuhrmann/mve#318]
This is more of a question rather than an issue.

I have been testing MVE with openMVG and I am getting some good results with models of architectural features on buildings, like doors & windows. However I'm having some small difficulty with making a model of a standing stone. I'm using the MVE commands: dmrecon, scene2pset, fssrecon & meshclean, as suggested on the page:
https://openmvg.readthedocs.io/en/latest/software/MVS/MVE/

Using openMVG and using some image masks to remove unnecessary features in the background I get a clean model as shown in the Meshlab screenshot: ( there are gaps on the top because the stone is 3m high and I can't get good images of that region )
![openmvg](https://cloud.githubusercontent.com/assets/16657559/24222611/8c9cceca-0f4a-11e7-9f95-004a05c02212.png)

Using MVE I get great detail on the stone but also some extra artifacts on the sides of the stone as shown on this screenshot:
![mve](https://cloud.githubusercontent.com/assets/16657559/24222639/a3beefb6-0f4a-11e7-91c2-e3e020552e5d.png)

I'm sure that these can be removed by changing some of the command line parameters of the tools but I'm not sure where to start. Any suggestions that you can give would be helpful.

If you need any more information or anything is not clear then please let me know.

**Comment by simonfuhrmann** [comment]
Honestly, the easiest way to get rid of those is just by using the Meshlab tools. Select the faulty faces, and delete them.

This is erroneous `mvsrecon` geometry, which you could clean in the depth maps (but we don't have tools for that), or in the giant point cloud before you run `fssrecon` (but the point cloud is HUGE and exporting it from Meshlab will likely silently drop important PLY attributes), or from the final mesh using `meshclean` (use a higher threshold, or, if the artifacts are disconnected from the main geometry, use a larger component size). Usually, however, these artifacts ARE connected to the main object, and increasing the threshold also deletes other stuff you don't want.

So yea, it's easiest to just use Meshlab. Next time, if you take photos, just increase the coverage. How many photos did you use for the store? Almost independent of you answer, you will get better results if you take twice as many, from different angles and different heights. :)

**Comment by simonfuhrmann** [comment]
Also consider this documentation:
https://github.com/simonfuhrmann/mve/wiki/MVE-Users-Guide

**Comment by john-davies** [comment]
Thanks for the quick response. I had 37 photos, 27 around the stone at about 1.5m height and 10 from higher up but further away to try and get the top of the stone. ( The 10 from further away didn't really work because I had forgotten to take my longer lens! )

However as you say more photos are always better :)

In this case most of the artifacts were detached and adding "-c 10000" to the "meshclean" command fixed most of the problems:
![mve2](https://cloud.githubusercontent.com/assets/16657559/24225239/4b3f5d46-0f57-11e7-9140-4a0295d7dde5.png)
There are some small remaining artifacts but I will clean these using Meshlab.

Thank you very much for the information, it has given me some useful suggestions and I will experiment more with the "meshclean" options.

I'm closing this issue.

**Comment by simonfuhrmann** [comment]
I am actually surprised that you used only 37 photos. I would have taken 100 - 200. :)

**Comment by caomw** [comment]
Good
