### ISSUE TITLE
Take ownership of the "mve" snap

### ISSUE THREAD

**Issue by mardy** [simonfuhrmann/mve#320]
Hi!
  At the moment, the "mve" name is registered in the snap store under my name. Given that I'm not active on mve development, which also happens to be rather fast-paced, I think it's better if someone from the mve team takes care of updating the package. I can also do it from time to time, but anyway it's preferrable if the ultimate ownership belongs to you.

I'd suggest that you create an account in the snap store for your team; then, when being logged in with that account, visit https://myapps.developer.ubuntu.com/dev/click-apps/register-name/ and claim the "mve" name. You can add a link to this bug in the comment, so that the reviewers will understand that we all agree on the ownership switch.

Then, from https://myapps.developer.ubuntu.com/dev/click-apps/, click on the "mve" app and in the "collaborators" page you can add any e-mail address you like. Feel free to add my address mardy@users.sourceforge.net as well, if you'd like me to help with the uploads.

**Comment by simonfuhrmann** [comment]
I would assume that now, three years after this issue was created, no one is willing to maintain this. I'll close this out for now.
