### ISSUE TITLE
A PLY file exported from MeshLab cannot put in FSSR process.

### ISSUE THREAD

**Issue by smallflowerwoo** [simonfuhrmann/mve#327]
I exported a ply file from the software MeshLab and put it into FSSR process. The terminal said "Missing sample scale". How to solve this problem? Does anyone know the solution? Thanks for any help.

**Comment by simonfuhrmann** [comment]
FSSR requires the PLY attribute `value`, which is interpreted as the sample scale. See the "Floating Scale Surface Reconstruction" paper for technical details, and various other issues for potential solutions:
https://github.com/simonfuhrmann/mve/issues/298
