### ISSUE TITLE
FssRecon - Missing Sample Scale

### ISSUE THREAD

**Issue by soulslicer** [simonfuhrmann/mve#330]
I seem to get this following error when running fssrecon. What exactly am i missing here? It seems to be because I am missing this "value" parameter in my PLY file.

Your documentation seems to say " Note that the value field corresponds to the per-vertex scale values.", however, I tried adding such a field where I set all the scales to 1.0 but I got no output for my mesh then

**Comment by simonfuhrmann** [comment]
You can't just set it to 1. See other issues regarding a solution:
https://github.com/simonfuhrmann/mve/issues/298

**Comment by soulslicer** [comment]
So let me try to understand what scale is..if my pointcloud was downsampled uniformly to a 1cm voxel grid, does that mean the scale for each point is 0.1?

**Comment by simonfuhrmann** [comment]
Did you read the explanation in issue #298? It explains what the sample scale is. The paper also explains it in detail.

**Comment by simonfuhrmann** [comment]
To put it in terms of metric units, if your sample represents an area of 1cm (diameter) then the sample scale is 1cm. However you translate this to world units.
