### ISSUE TITLE
Question about different property in the .ply file generated by MVE

### ISSUE THREAD

**Issue by silentspring2** [simonfuhrmann/mve#339]
Hi!

I find there are 11 properties in the elements in pset-L2.ply : x,y,z,nx,ny,nz,red,green,blue,confidence and value.
I understand the x,y,z and red, green, blue. But I have doubt about the others.
First, I'm not sure about the nx,ny,nz. Are they the normalized x,y and z? Also is the property 'confidence' some kind of parameter that will determine whether a vertex will be abandoned in the following steps such as fssrecon or meshclean? 
Second,  I have no idea what the property 'value' represent or how to get it?

I find the following code that may be used to get these properties:
in scene2pset.cc from line 172 to 178

    /* Prepare output mesh. */
    mve::TriangleMesh::Ptr pset(mve::TriangleMesh::create());
    mve::TriangleMesh::VertexList& verts(pset->get_vertices());
    mve::TriangleMesh::NormalList& vnorm(pset->get_vertex_normals());
    mve::TriangleMesh::ColorList& vcolor(pset->get_vertex_colors());
    mve::TriangleMesh::ValueList& vvalues(pset->get_vertex_values());
    mve::TriangleMesh::ConfidenceList& vconfs(pset->get_vertex_confidences());

If the questions above it a bit complex to explain, I hope you could tell me where these functions locate in the your mve project.

Thanks!!!

**Comment by flanggut** [comment]
Hi,
- The vector [nx, ny, nz] is the surface normal estimated at the vertex
- The confidence property is a measure of (un)certainty for each vertex that can be used in a surface reconstruction algorithm like FSSR; usually 0 means the vertex position is very unlikely to be correct whereas 1 means the vertex position is definitely correct
- The value property is in general arbitrary but FSSR interprets this as the scale of the sample, in the sense of a physical extend associated with each vertex

For more detailed information on how these properties are handled please also see the [FSSR paper](http://www.gcc.tu-darmstadt.de/media/gcc/papers/Fuhrmann-2014-FSS.pdf) and related issues https://github.com/simonfuhrmann/mve/issues/298.

**Comment by silentspring2** [comment]
thank you
