### ISSUE TITLE
A way to compile the latest MVE for Windows?

### ISSUE THREAD

**Issue by JacobRoth** [simonfuhrmann/mve#340]
Hi all, first of all great program. I'm getting good results for some of our research running the latest and greatest MVE from this git repo on my Linux server, but I wanted to run it on one of our lab's Windows workstations because they have good processors. However, the Windows binaries available on the MVE web page are about a year old and they don't work as well. I found these [Build instructions for Windows](https://github.com/simonfuhrmann/mve/wiki/Build-Instructions-for-Windows), but they refer to a fork of MVE that isn't completely up to date. 

We only need the command-line tools, not UMVE.

I was hoping for a way to compile the MVE in *this* repository for Windows 7. Is that possible? We have Cygwin on one of the lab workstations, and I suppose I could also cross-compile on the Linux machine to make Windows binaries.

**Comment by flanggut** [comment]
Unfortunately we currently don't have anyone with enough experience and time to update the windows port. 
If you really need an up to date version for windows you could have a look at the CMAKE files in the fork and simply try to update them yourself.

**Comment by andre-schulz** [comment]
Hi @JacobRoth,
I've just updated my CMake fork with the latest MVE changes. Please let me know if it works for you.

**Comment by JacobRoth** [comment]
Hi! Thanks for updating it. However, when I go into the 3rdparty folder and run 
`cmake .` ,

I get this error:

`Forcing build type to "Release"
Reminder: Select Release configuration in Visual Studio before building
CMake Error at CMakeLists.txt:111 (message):
  Unsupported Visual Studio version


-- Configuring incomplete, errors occurred!
See also "/cygdrive/e/Jacob's Random Crap/mve-andre/3rdparty/CMakeFiles/CMakeOutput.log".`

I'm doing this via Cygwin on a computer that has Visual Studio Community 2017 installed. Is that not a supported version? Do we need the paid version of VS?

**Comment by andre-schulz** [comment]
Unfortunately, VS 2017 is currently unsupported. But you can use VS Community 2015 instead.
I will take a look at what's needed for supporting VS 2017 by the end of this week.

**Comment by andre-schulz** [comment]
I've committed several changes to my MVE fork and it now compiles with VS Community 2017 on my end. @JacobRoth, please let me know if it works for you.
