### ISSUE TITLE
Using a model with Geodetic coordinates

### ISSUE THREAD

**Issue by bigakoz** [simonfuhrmann/mve#341]
Hello,

I have created two models from a bundle adjustment. 
- One without geodetic coordinates for the model (an arbitray coordinate system using the initial pair). This works fine.

_ One using 'pose priors'. That is a reasonable estimate is given for the camera poses based on GPS coordinates. This does not work in the pipeline.  Basically I end up with a mesh with zero vertices when the mesh cleaning is done.

Is there special settings that need to be applied when using using data with geodetic coordinates or could it be an issue with floating point numbers in your algorithms (perhaps doubles instead of floats would fix this).

Regards,

Alan

**Comment by flanggut** [comment]
Hi Alan, I don't really see how you would use GPS as a prior for camera poses. It doesn't give you any orientation at all and the GPS positions are way to inaccurate for a proper initialization before bundle adjustment. What exactly did you try to do?

Float vs Double is definitely not an issue.

**Comment by bigakoz** [comment]
GPS for the camera is used to form the model prior to the bundle adjustment. The bundle adjustment then solves the camera and model coordinates in geodetic coordinates. This is a established way of completely the exterior orientation.
Alternatively a geodetic model could be computed post bundle using a similarity transformation.
Either way I have a model that is on a geodetic datum that doesn't seem to work in MVE so would like to work out what is wrong


Sent from my Samsung Galaxy smartphone.-------- Original message --------From: Fabian Langguth <notifications@github.com> Date: 19/05/2017  15:03  (GMT+08:00) To: simonfuhrmann/mve <mve@noreply.github.com> Cc: bigakoz <alan.buchanan@ashrock.net>, Author <author@noreply.github.com> Subject: Re: [simonfuhrmann/mve] Using a model with Geodetic coordinates
  (#341) 
Hi Alan, I don't really see how you would use GPS as a prior for camera poses. It doesn't give you any orientation at all and the GPS positions are way to inaccurate for a proper initialization before bundle adjustment. What exactly did you try to do?
Float vs Double is definitely not an issue.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/simonfuhrmann/mve","title":"simonfuhrmann/mve","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/simonfuhrmann/mve"}},"updates":{"snippets":[{"icon":"PERSON","message":"@flanggut in #341: Hi Alan, I don't really see how you would use GPS as a prior for camera poses. It doesn't give you any orientation at all and the GPS positions are way to inaccurate for a proper initialization before bundle adjustment. What exactly did you try to do?\n\nFloat vs Double is definitely not an issue. \n\n"}],"action":{"name":"View Issue","url":"https://github.com/simonfuhrmann/mve/issues/341#issuecomment-302625854"}}}

**Comment by flanggut** [comment]
Sorry, but no - it cannot work this way. As I said before, GPS doesn't give you a proper camera orientation so you cannot use only GPS to initialize the scene before bundle adjustment.

**Comment by bigakoz** [comment]
Fab Ian
My issue isn't with the bundle adjustment. I am using openmvg which can compute a geodetic bundle adjustment using GPS camera coordinates and coordinates for ground control. I have a good solution at 0.5 pixel RMSS. 
Are there any issues or settings when using a bundle adjustment that uses Geodetic coordinates. GEODETIC COORDINATES (ecef) generally require double precision 




Sent from my Samsung Galaxy smartphone.-------- Original message --------From: Fabian Langguth <notifications@github.com> Date: 19/05/2017  15:42  (GMT+08:00) To: simonfuhrmann/mve <mve@noreply.github.com> Cc: bigakoz <alan.buchanan@ashrock.net>, Author <author@noreply.github.com> Subject: Re: [simonfuhrmann/mve] Using a model with Geodetic coordinates
  (#341) 
Sorry, but no - it cannot work this way. As I said before, GPS doesn't give you a proper camera orientation so you cannot use only GPS to initialize the scene before bundle adjustment.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/simonfuhrmann/mve","title":"simonfuhrmann/mve","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/simonfuhrmann/mve"}},"updates":{"snippets":[{"icon":"PERSON","message":"@flanggut in #341: Sorry, but no - it cannot work this way. As I said before, GPS doesn't give you a proper camera orientation so you cannot use only GPS to initialize the scene before bundle adjustment. "}],"action":{"name":"View Issue","url":"https://github.com/simonfuhrmann/mve/issues/341#issuecomment-302632909"}}}

**Comment by flanggut** [comment]
Alright so to avoid any further confusion can you please explain what exactly you are doing in MVE? Where did you get the scene? How does it look when you open it in UMVE? What tools are you trying to run? What parameters are you using? What is the output of each tool?

**Comment by bigakoz** [comment]
Hello,

I am using openMVG to process imagery and I am trying to generate  a textured 3D model.
I am using the pipeline from openMVG for this (in Python).

i.e. 
           [   "Export to MVE",
                os.path.join(OPENMVG_SFM_BIN,"openMVG_main_openMVG2MVE2"),
                 ["-i", "%reconstruction_dir%/sfm_data.bin", "-o", "%output_dir%"]],
	    [   "Export to DmRecon",
		os.path.join(OPENMVE_BIN,"dmrecon"),
		["-s", "2" , "%mve_dir%"]],
	    [   "Export to Scene2pset",
		os.path.join(OPENMVE_BIN,"scene2pset"),
		["-F2", "%mve_dir%","%mve_dir%/output.ply" ]],
	    [   "Export to fssrecon",
		os.path.join(OPENMVE_BIN,"fssrecon"),
		["%mve_dir%/output.ply", "%mve_dir%/output_mesh.ply" ]],
	    [   "Export to meshclean",
		os.path.join(OPENMVE_BIN,"meshclean"),
		["-t10","-c10000","%mve_dir%/output_mesh.ply", "%mve_dir%/output_mesh_clean.ply" ]],
	    [   "Export to texrecon",
		os.path.join(OPENMVE_BIN,"texrecon"),		["%mve_dir%::undistorted","%mve_dir%/output_mesh_clean.ply","%mve_dir%/output_mesh_textured" ]]
	    ]

This works fine when I don't use pose priors in openMVG
The "-P" flag in openMVG uses the coordinates from Exif header when forming the datastructures in openMVG_main_SfMInit_ImageListing and computing the bundle adjustement in openMVG_main_IncrementalSfM

The solution is good but the MVE pipeline doesn't like the data. When I don't use pose priors it works fine

My suspicion is that it could be a double to float issue.
My Geodetic coordinates are in ECEF and are large numbers (i.e. -2336145.405,4850787.979,-3411991.401)

Any manipulation of these numbers probably should use doubles.

Anyway any suggestions would be appreciated

**Comment by nmoehrle** [comment]
Not only the manipulation but also the storage of such numbers would have to be double. We do not consequently store everything in double, an example is our [mesh class](https://github.com/simonfuhrmann/mve/blob/master/libs/mve/mesh.h#L33) where we chose to store coordinates as floats, this will cause problems with all ECEF coordinates on the surface of the earth.
Whenever I have coordinates in ECEF I subtract an offset (e.g. the mean of all GCPs) from each coordinate, which works fine if you're not processing huge areas (hundreds of square kilometers, assuming one meter is one unit).

In my opinion converting the whole pipeline to double would be a enormous effort and at the moment not necessary or desirable.

**Comment by bigakoz** [comment]
Thanks,

As long as I understand that that is the issue then I can work around it.

I can , as you say, process the pipeline by subtracting an offset from the start
i.e.  openMVG_main_SfMInit_ImageListing

At some point I will convert the solution back to projected coordinates and I can then add back the offset to get ECEF and then apply the convertion to projected coordinates.

Thanks for clarifying the problem.

Regards,

Alan

**Comment by simonfuhrmann** [comment]
Closing this. Feel free to re-open with further questions.
