### ISSUE TITLE
Limit number of cores?

### ISSUE THREAD

**Issue by JacobRoth** [simonfuhrmann/mve#344]
Hi all,

I'm doing some work with MVE in an academic environment, and I've gotten permission to use the CS department's 64-core high-performance-computing machine to run MVE. However, I would need the MVE programs to not take up all 64 cores of the machine. Is there any way I can compile/configure MVE so that all of its parts (or at least the pipeline we use: makescene -> sfmrecon -> dmrecon -> scene2pset -> fssrecon -> meshclean, with sfmrecon and dmrecon and fssrecon being the really important bits here) only use a limited number of CPU cores, perhaps just 48?

If there's a way to accomplish this from the Linux shell environment rather than from within MVE itself, that would also work.

**Comment by simonfuhrmann** [comment]
We use OpenMP for parallelization. Try the `OMP_NUM_THREADS` environment variable, or [check the docs](https://gcc.gnu.org/onlinedocs/libgomp/Environment-Variables.html).

**Comment by JacobRoth** [comment]
Ah, thanks. Do I set that variable at compile time, run time, or both?

**Comment by simonfuhrmann** [comment]
At runtime.

**Comment by simonfuhrmann** [comment]
On another note, you can specify the CPU assignment for a program independent of how it's implemented using [taskset](https://linux.die.net/man/1/taskset), e.g., `taskset 0xf program` to use at most four cores for `program`.

**Comment by JacobRoth** [comment]
Perfect. Will do.
