### ISSUE TITLE
Processing large high resolution data

### ISSUE THREAD

**Issue by bigakoz** [simonfuhrmann/mve#346]
I am looking for some advice.

I have  a dataset with 750 images. The image resolution is 8100x4300 pixels.
This is aerial photography flown at 10,000'. The ground resolution is about 5 cm.

I processed in dmrcon using -s 2. This is a default setting from openMVG

The processing ran for about 6 days and then crashed !  

Could you suggest some more appropriate settings I should use with this type of data

**Comment by pmoulon** [comment]
You can split the dataset in smaller piece by using https://github.com/openMVG/openMVG/issues/857

This WIP binary provide you a way to split an OpenMVG SfM scene into many chunk. 
Then you can after post process the chunk in every software of your choice (MVE).

**Comment by simonfuhrmann** [comment]
Hi bigakoz,

sorry to hear this. Can you provide more details about the crash, maybe the console log? It shouldn't just crash. Did it run out of memory?

If you used dmrecon, the depth maps it finished processing should still be there saved in the scene. Try inspecting the scene with UMVE. You can always try to reduce the resolution.

I don't understand why `-s2` is a default setting from OpenMVG. As far as I understand, OpenMVG just exports the high resolution images and the bundle.

Simon

**Comment by bigakoz** [comment]
Simon,

I think it just ran out of memory. DmRecon was running at nearly the full 100% of my cpu and memory

The s-2 settings was a suggestion in the openMVG documentation for using the MVE pipeline.

I am using -s3 at the moment and is looking promising
