### ISSUE TITLE
Learn MVE as developper 

### ISSUE THREAD

**Issue by HelliceSaouli** [simonfuhrmann/mve#347]
Hello
I'm working on mulit-view stereo  and i like to learn as dev your library MVE so i can use it and develop with it my own algorithms and contributions. the thing is MVE is kind of large library there is not that match documentation on how to develop with it. i'm hopping for any hints and insights on how to start

**Comment by simonfuhrmann** [comment]
If you want to start MVE as your library, that's great. MVE isn't really that big, and it's self-contained, i.e., doesn't have any external dependencies except libpng, libjpg and libtiff.

To get started, I'd suggest you compile the Doxygen documentation (`make doc`) take a look into it. Start browsing libutil and libmath, that's just straightforward stuff. In libmve, look at view, scene, image and mesh, and that should be all you need to get started. libogl is for rendering. The other libraries are only interesting if you want to learn how the algorithms work.
