### ISSUE TITLE
Settings for Meshclean

### ISSUE THREAD

**Issue by bigakoz** [simonfuhrmann/mve#350]
Hello,

I am getting great results with your processing pipeline. So thanks for your excellent work.

I have one question regarding meshclean. I am getting a few holes in my model which I assume is a result of having holes in the mesh after meshclean.

There are a few settings that I can change (primarily the t and c parameters). I am not sure how these settings work. What is your suggested strategy for removing holes while still removing outliers in the mesh ? The holes generally occur on flat homogenous surfaces.

Regards,

Alan

**Comment by simonfuhrmann** [comment]
The -t flag removes geometry based on vertex confidence. Choose this as large as you can such that you still don't get holes in the mesh. Depending on the amount of redundancy you have, you can choose this pretty large. Example, if ever point on the mesh surface is roughly covered by 10 depth maps, you can roughly set this to 10.

The -c flag removes connected components with less vertices then the argument. If you have one giant component with 1mio vertices, set this to 1mio. If you want to preserve more components, make this smaller. 10k usually works well with a medium sized mesh.
