### ISSUE TITLE
Is possible to use colmap sparse  point cloud information to build the dense  point cloud in smvs ?

### ISSUE THREAD

**Issue by youngzi1004** [simonfuhrmann/mve#352]
hi, 

First of all, thanks so much for your hard work. I am graduate student in china. these days I am trying to build a  dense  point model based on mve.

 I have used colmap to calculate the camere information and sparse point position, and I try to build the dense  point cloud in smvs based upon this information.  howereve there is something wrong about the camera parameters.  Input images are the TempleRing dataset of the Middlebury benchmarkhttp://vision.middlebury.edu/mview/data/

refering to  mve/apps/makescene/makescene.cc , the mve scene has been built by using camera  information in colmap. I make sure that the K, R,T matrixs used in mve are the same  as those used in colmap. But the point cloud has some issues.  the footsteps in the model are wrong.shown as follows:
![image](https://user-images.githubusercontent.com/29294740/27216792-b8c51776-52a9-11e7-9171-b28cba0d8a7c.png)

would it's possible I misuse the camera information?

**Comment by HelliceSaouli** [comment]
I think you should post this issue on smvs.

**Comment by simonfuhrmann** [comment]
If the camera information was wrong, there would be no reconstruction. I don't think anything is wrong here. It's just noisy because the depth maps have not been merged into a final surface. Have you tried running FSSR on this?

Also, note that "exact" camera information is available for this dataset here: http://vision.middlebury.edu/mview/data/

**Comment by youngzi1004** [comment]
The camera information is true. I have got the accurate result with the  groundtrue camera information working with macOS. It turns out that the operating system win10 + vs2013 affected the result of SMVS.  I have post this issue on smvs. 

Thanks for your suggestion!
