### ISSUE TITLE
'png.h' file not found

### ISSUE THREAD

**Issue by zswmr** [simonfuhrmann/mve#355]
an error happened when make this project ,it can not find png lib. i am in mac system .
i have already installed libpng 1.6.29 in my system and what can i do ?

error lists as follow:

c++ -Wall -Wextra -Wundef -pedantic -msse2 -msse3 -msse4 -mpopcnt -funsafe-math-optimizations -fno-math-errno -std=c++11 -g -O3 -pthread -fPIC -I../../libs  -c -o image_io.o image_io.cc
image_io.cc:19:13: fatal error: 'png.h' file not found
#   include <png.h>
            ^
1 error generated.
make[2]: *** [image_io.o] Error 1
make[1]: *** [all] Error 2
make: *** [all] Error 2

**Comment by flanggut** [comment]
Well you definitely did not install libpng correctly. Please try again and follow the exact steps outlined [here](https://github.com/simonfuhrmann/mve/wiki/Build-Instructions-for-OS-X).

**Comment by nathantsoi** [comment]
I just got this working, but was having the exact same issue on a brand new 10.12.5 install. Swapping out clang for gcc 7 and explicitly specifying the missing libs seems to have done the trick. Clang can probably be fixed too somehow...

```
brew install gcc git libpng jpeg libtiff qt
brew link --force qt

git clone https://github.com/simonfuhrmann/mve.git
cd mve
export CXX=c++-7
export CXXFLAGS="-I/usr/local/include/ -msse4.2"
export LDFLAGS="-L$(brew --prefix libpng)/lib/ -L$(brew --prefix libtiff)/lib/ -L$(brew --prefix libjpeg)/lib/"
make -j8
```

I also had to patch the umve config:

```
diff --git a/apps/umve/umve.pro b/apps/umve/umve.pro
index 8944d10..c9e6be0 100644
--- a/apps/umve/umve.pro
+++ b/apps/umve/umve.pro
@@ -27,7 +27,12 @@ macx {
     QMAKE_LFLAGS += -L/usr/local/lib
     QMAKE_LFLAGS -= -fopenmp
     INCLUDEPATH += /usr/local/include
+    QMAKE_CC = gcc-7
+    QMAKE_CXX = c++-7
     QMAKE_CXXFLAGS -= -fopenmp
+    QMAKE_CXXFLAGS -= -stdlib=libc++
+    QMAKE_LINK = c++-7
+    QMAKE_LFLAGS -= -stdlib=libc++
 }
```

(I'll submit a PR if you would like to add this @simonfuhrmann)

Then I ran

```
cd apps/umve
qmake
make
./umve
```

**Comment by simonfuhrmann** [comment]
GCC 7 is out? Time is changing so fast...
