### ISSUE TITLE
Compilation error on Linux Ubuntu 16.04 LTS 64-bit - "error: template with C linkage"

### ISSUE THREAD

**Issue by mikeroberts3000** [simonfuhrmann/mve#356]
Hello there,

I am encountering a compilation error on a clean installation of Linux Ubuntu 16.04 LTS 64-bit. I just pulled the latest MVE code from GitHub. The error log is using GCC 5.4, but I have tried to compile the offending file using GCC 4.8, GCC 6, and GCC 7; I get the same error message each time. Should I be using clang or something?

Cheers,
Mike

```
mike@scanplan-eval:~/Code/GitHub/mve$ make
make -C libs
make[1]: Entering directory '/home/mike/Code/GitHub/mve/libs'
make -C math
make[2]: Entering directory '/home/mike/Code/GitHub/mve/libs/math'
#ar rcs libmve_math.a 
make[2]: Leaving directory '/home/mike/Code/GitHub/mve/libs/math'
make -C util
make[2]: Entering directory '/home/mike/Code/GitHub/mve/libs/util'
g++ -Wall -Wextra -Wundef -pedantic -msse2 -msse3 -msse4 -mpopcnt -funsafe-math-optimizations -fno-math-errno -std=c++11 -g -O3 -pthread -fPIC -I../../libs  -c -o arguments.o arguments.cc
In file included from /usr/include/c++/5/utility:69:0,
                 from /usr/include/c++/5/algorithm:60,
                 from ./endian.h:13,
                 from /usr/include/ctype.h:39,
                 from /usr/include/c++/5/cctype:42,
                 from /usr/include/c++/5/bits/localefwd.h:42,
                 from /usr/include/c++/5/ios:41,
                 from /usr/include/c++/5/ostream:38,
                 from /usr/include/c++/5/iostream:39,
                 from arguments.cc:10:
/usr/include/c++/5/bits/stl_relops.h:85:5: error: template with C linkage
     template <class _Tp>

...

mike@scanplan-eval:~/Code/GitHub/mve$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.4' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
```

**Comment by HelliceSaouli** [comment]
try to compile with this : --with-local-prefix=/usr

**Comment by simonfuhrmann** [comment]
Both clang and gcc should work with MVE, but clang won't give you OpenMP parallelization.
I have never seen this error, and I don't know what it is. Please keep me posted if you found the reason why this error is generated.

**Comment by flanggut** [comment]
This looks like the code is compiled as C instead of C++ code. I don't know how, but my guess is that your compiler setup is somehow broken.

**Comment by simonfuhrmann** [comment]
Are you compiling on a 32 bit system? What does `uname -m` say?

**Comment by HelliceSaouli** [comment]
as flanggut said it the compiler setup is  broken and the solution to this is found here : [solution](https://unix.stackexchange.com/questions/346133/gcc-compilation-terminated-with-fatal-error-string-no-such-file-or-directory/346171#346171)

**Comment by mikeroberts3000** [comment]
To everyone in this thread, thanks for the help. I agree, it looks like my compiler setup is broken somehow.

Interestingly, when I try to invoke g++ with the --with-local-prefix option, I get the following error:

```
mike@scanplan-eval:~/Code/GitHub/mve/libs/util$ g++ --with-local-prefix=/usr
g++: error: unrecognized command line option ‘--with-local-prefix=/usr’
g++: fatal error: no input files
compilation terminated.
```

Which is very suspicious. I think the g++ I have installed might actually be gcc or something. I'm on a totally clean new install of Ubuntu though, and I haven't installed any non-standard weird packages or modified gcc in any way. So I'm surprised that I'm having this problem.

Here is the output I get when I run uname -m:

```
mike@scanplan-eval:~/Code/GitHub/mve/libs/util$ uname -m
x86_64
```

I am running Ubuntu in a virtual machine though (guest OS Ubuntu 16.04 LTS 64-bit, host OS Windows 10 64-bit), so that's a potential complication. But it's not clear to me that GCC would even know its running in a virtual machine.

**Comment by mikeroberts3000** [comment]
I was able to fix this problem by doing a clean install of an older version of Ubuntu. So I'm going to mark this issue as closed, since this problem appears to have nothing to do with the MVE codebase. I think the way that GCC was configured by default on my system - running Ubuntu 16.04 LTS 64-bit - was broken. To everyone in this thread, thanks for the helpful suggestions 😄

**Comment by nmoehrle** [comment]
Clang has OpenMP support since 3.8.0 http://openmp.llvm.org/.

**Comment by Sjoerdie** [comment]
We were experiencing exactly this issue when compiling on multiple ubuntu machines (tested in 14.04, 16.04, 17.04). The problem seems to come with the naming of 2 header files that can also exist in the c system headers. Which leads to duplication errors when compiling.

The following script fixes the problem as a work around. But breaks when `make clean && make` is invoked. Be aware that the script uses `sed` so don't execute as super user.

```bash

cd path/to/your/clone/of/mve

cd libs/ &&
mv util/endian.h util/mve-endian.h &&
mv util/string.h util/mve-string.h &&
grep -rl 'util/endian.' . | xargs sed -i 's/util\/endian./util\/mve-endian./g' &&
grep -rl 'util/string.' . | xargs sed -i 's/util\/string./util\/mve-string./g'
```

If appreciated we're happy to make a pull request.

Cheers. Sjoerd

**Comment by simonfuhrmann** [comment]
Interesting. I'll take a look. Thanks for investigating!
