### ISSUE TITLE
Footprint function in dmrecon

### ISSUE THREAD

**Issue by HelliceSaouli** [simonfuhrmann/mve#357]
can some one explain what are the exact maths behind the function **footprint**(math::vec3f point)

**Comment by flanggut** [comment]
I don't understand your question, if you look at the definition of the function you can see the exact maths.

**Comment by HelliceSaouli** [comment]
i know, but what i can't understand is how can  a a Z component of a 3D point in camera coordinate multiplied by the the first element of of inverse matrix K gives you the size of pixel  spacing in 3D

**Comment by flanggut** [comment]
The K matrix converts from 3D space to image space - so the inverse does just the opposite, from image space to 3D space. If you have a single pixel (which has a size of 1 in image space) you need the inverse K matrix to project it and get the size in 3D space.

**Comment by HelliceSaouli** [comment]
yes, but what u did in code is multiplying 3D point (a  point in camera coordinate and it's not in image space yet) by the inverse K

**Comment by flanggut** [comment]
No. The code multiplies the Z component of the point in camera coordinates, which is the depth of the pixel, with the first entry of the inverse K.
