### ISSUE TITLE
Results coordinate system and scale

### ISSUE THREAD

**Issue by yylovess** [simonfuhrmann/mve#358]
Hello,

Thanks for your excellent work. I have got great results from your work combined with VisualSFM.

I have one question regarding the coordinate system and scale for the reconstructed mesh results.
Is the results in camera coordinate system? I think not. If not, how can I translate the results in camera coordinate system, for example the first view camera system? Or is there some parameter or setting to control this?

Thank you very much.

**Comment by flanggut** [comment]
In general the result will be in an arbitrary coordinate system (the coordinate system is actually dictated by VisualSFM in your case). But you can simply get the rotation and translation for any camera from the `meta.ini` files in the view folders (look [here](https://github.com/simonfuhrmann/mve/wiki/MVE-File-Format) for the reference) and transform the mesh yourself into the coordinate system you prefer.

**Comment by simonfuhrmann** [comment]
Every scene is determined with up 6 degrees of freedom of ambiguity. This ambiguity is resolved in SfM, usually by fixing the position of the initial camera pair (3 dof position), placing the cameras at a distance of one (1 dof scale) and having one camera facing down one axis (2 dof orientation).

All results are in the coordinate system generated by SfM. If you want a specific scene coordinate system, you have to transform it yourself. In your case, you'd have to decide where your first view camera should be in the global coordinate system, set up a transformation from its current position/orientation to the desired position/orientation, make up a desired scale, and then transform everything, the camera positions and orientation, and all SfM points.

**Comment by yylovess** [comment]
Thanks all for the answer. I do not know if I understand it correctly.

The camera rotation and translation data in meta.ini file for every camera view is based on the results coordinate system (which is fixed by the initial camera pair), So I can get the results in the coordinate system of any camera system I want by translate the results with the camera rotation and translation data in meta.ini file? By the results I mean the mesh data, (I have transfered it to .obj file), all vertex position and normal.

Or another way, after the SFM from VisualSFM, I need to transfer the out put data of VisualSFM, the .nvm file. To transfer all the camera and points data in the .nvm file? Then use this as input of your reconstruction system? This may difficult because I am not very familiar with this.

Thank you very much.

**Comment by simonfuhrmann** [comment]
I am not sure if I understand what you want to accomplish. You say you want to transform the results in the camera coordinate system. What does that mean?

If really all you want is to transform the global mesh in the local coordinate system (LCS) of a camera C, then just obtain the rotation **R** and translation **t** for camera C (stored the `meta.ini` file) and compute for every vertex **x** in the mesh:

    x' = R * x + t

The LCS of a camera is defined here (see illustration).
https://github.com/simonfuhrmann/mve/wiki/Math-Cookbook

**Comment by HelliceSaouli** [comment]
I think she wants to render (draw) the resulted mesh and get an image similar to one of the input views

**Comment by simonfuhrmann** [comment]
We have re-photography code built into UMVE, which also considers the camera intrinsics.

**Comment by yylovess** [comment]
Thanks all for the answer.
 And what I want to do is making the resulted mesh in the same view with one the input images.
And your answers help. I wound try.

Thanks a lot.
