### ISSUE TITLE
benefitFromView()

### ISSUE THREAD

**Issue by HelliceSaouli** [simonfuhrmann/mve#360]
Hello
In global selection class a function that compute score **beniftFromView()**, the part where you compute parallax with other selected views that see the same feature. although  you are saying selected view that see the same features but i can't see where you did handle that, it seems that you pick a feature visble to refV and tmpV and with it you compute parallex for selected view and tmpV. what am i missing.

thank you

**Comment by HelliceSaouli** [comment]
Well i re-implemented the global selection with MVE ( to get my self  familiar with it and it's style) according to my own understanding and using a bit from existing code. the problem is the results are off by just one view different from the original implementation result. that's why i'm asking if i'm missing something.

here is my implementation : https://github.com/HelliceSaouli/MVScpc
please check if you have some time

thx

**Comment by simonfuhrmann** [comment]
I don't think we have time to compare your implementation with ours. If you have specific questions, however, we can help answering them.
