### ISSUE TITLE
Licensing Questions

### ISSUE THREAD

**Issue by bigakoz** [simonfuhrmann/mve#362]
Simon,

I have recently completed processing of a large data set of aerial photography with openMVG/openMVE with excellent results.

I have been contacted by a large company that specializes in Lidar acquisition and processing. They are interested in adding photogrammetric processing to add to their products line. They have large computer resources (over 1000 cores) and cloud based storage.

Are there any licensing issues associated with using your software. Obviously my plan is to generate income from this.

I understand that the GPL licensing requires that I share back to openMVE any software changes that are made. 

Please advise of anything I need to do to comply with your licensing requirements.

Regards,

Alan

**Comment by pmoulon** [comment]
Hi. @simonfuhrmann FYI, somehow this post is also related to this one https://github.com/openMVG/openMVG/issues/978

**Comment by simonfuhrmann** [comment]
I can't speak for OpenMVG. But for MVE, our master branch is BSD. So no, no licensing issues.
