### ISSUE TITLE
Displaying normals of faces in Qt UMVE

### ISSUE THREAD

**Issue by vikasTmz** [simonfuhrmann/mve#363]
Is there currently an option to display the normals of faces in a mesh?
If not could you suggest a possible way to do it?

**Comment by pmoulon** [comment]
You can use Meshlab or CloudCompare to display faces normals.

**Comment by vikasTmz** [comment]
I was looking for a way to get it done in the Qt scene view. Possible inbuilt function within `mesh.render` or other methods..

**Comment by simonfuhrmann** [comment]
See if [1] does what you are looking for.
[1] https://github.com/simonfuhrmann/mve/pull/328
