### ISSUE TITLE
SMVS

### ISSUE THREAD

**Issue by stephane-lb** [simonfuhrmann/mve#364]
Hi Simon,

Any reason why SMVS is not integrated to MVE ? I remember that for a while FSSR was an extra repo but finally was integrated in the main repo. Why that's not the case of SMVS ?

Best Regards,

Stéphane

**Comment by HelliceSaouli** [comment]
i think because SMVS is alternative for _dmfrecon_ and _scene2pset_

**Comment by simonfuhrmann** [comment]
I will have a chat with Fabian and see what we can do. MVE has a no external deps policy.

**Comment by simonfuhrmann** [comment]
I talked with Fabian about pulling SMVS into MVE. It seems SMVS is not using external libraries. So we should be able to pull that into the MVE repository. This topic, however, raised the question of whether we should relocate the MVE repository into the MVE organization, which is somewhat more effort.
