### ISSUE TITLE
Can not Compile it  in MacOS X 10.12.2

### ISSUE THREAD

**Issue by smallworld-network-wupeng** [simonfuhrmann/mve#365]
There is a error when make it .

`image_io.cc:19:13: fatal error: 'png.h' file not found`

But I was installed libpng ,the other project can compile ,for example openMVS.

When I Cmake it , it's looks find the lib

`-- Found ZLIB: /opt/local/lib/libz.dylib (found version "1.2.8")
-- Found PNG: /opt/local/lib/libpng.dylib (found version "1.6.13")
-- Found JPEG: /opt/local/lib/libjpeg.dylib
-- Found TIFF: /usr/local/lib/libtiff.dylib (found version "4.0.8")`

**Comment by flanggut** [comment]
Yeah, that's because you installed libpng with an unsupported package manager (my guess is macports). We don't account for all the random stuff that you can do to your machine. 
That's why the [wiki page](https://github.com/simonfuhrmann/mve/wiki/Build-Instructions-for-OS-X) tells you exactly what to do. If you follow these steps it will definitely work.

**Comment by smallworld-network-wupeng** [comment]
I do it as the wiki page step by step , use brew install libpng and other library

**Comment by flanggut** [comment]
what does `brew info libpng` say?

**Comment by smallworld-network-wupeng** [comment]
libpng: stable 1.6.30 (bottled), HEAD
Library for manipulating PNG images
http://www.libpng.org/pub/png/libpng.html
/usr/local/Cellar/libpng/1.6.30 (26 files, 1.2MB) *
  Poured from bottle on 2017-07-16 at 16:37:17
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libpng.rb

**Comment by flanggut** [comment]
can you please run `echo | gcc -Wp,-v -x c++ - -fsyntax-only`?

**Comment by smallworld-network-wupeng** [comment]
clang -cc1 version 8.1.0 (clang-802.0.42) default target x86_64-apple-darwin16.3.0
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/v1"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/local/include"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.1.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks (framework directory)
End of search list.

**Comment by flanggut** [comment]
seems like homebrew didn't add /usr/local/ to your include paths run `xcode-select --install` it should compile after that.

**Comment by smallworld-network-wupeng** [comment]
Thank you , it is looks worked
