### ISSUE TITLE
Normal vector

### ISSUE THREAD

**Issue by HelliceSaouli** [simonfuhrmann/mve#367]
Hello, I hope you guys are having a great vacation.
Well my question is about normal vector only for the extracted features (bundle),  is there a way to extract ( if they already exist) or compute it using MVE. the closest thing I found is  bundle2pset with no normal

**Comment by simonfuhrmann** [comment]
No, there are no normals for SfM points. The only way to compute something that is similar to normals is to average the direction from the SfM point to the cameras that observe it. This information is available. However, depending on what you want to do with it, the quality of the "normal" may not be good enough.
