### ISSUE TITLE
Possible to Pass initial depth guess to dmrecon?

### ISSUE THREAD

**Issue by soulslicer** [simonfuhrmann/mve#370]
i have a depth sensor attached as well, but gives poor depth results (error of up to 10cm). Is there a way I can incorporate this as an initial guess into dmrecon? Perhaps, it can speed it up?

**Comment by simonfuhrmann** [comment]
Unfortunately, you can't. The software doesn't support initializing from an existing depth map. And there are good reasons for it. With SfM tracks (the sparse 3D points), we know the views the track is visible in. So we can start optimizing depth from tracks and then propagate to neighboring pixels. A depth map, however, doesn't have this information. So this is a non-trivial extension of the algorithm. Sorry.

**Comment by soulslicer** [comment]
Ic, okay, can you point me at least to which part of the code generates the 16 bit depth map? I would like to convert it to a format I can read

**Comment by simonfuhrmann** [comment]
MVE generates floating point depth maps. The code is in `libs/dmrecon`.

**Comment by HelliceSaouli** [comment]
Since you are talking about dmrecon.. which part of MVE make use of the confidence map created by dmrecon ?

**Comment by simonfuhrmann** [comment]
Nothing does. It turns out the confidence map, which is essentially NCC scores, is not very useful in general apart from actual MVS use cases.
