### ISSUE TITLE
Texture, Holes and Distance

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [simonfuhrmann/mve#373]
How do I get the highest texture resolution in the final object?

How do I auto-close holes?

How do I mask by distance(ie the desired object is closer than x meters) roughly so only relevant areas are being computed?

So far I found it an interesting application.

**Comment by simonfuhrmann** [comment]
For texturing, see this project which works with MVE:
https://www.gcc.tu-darmstadt.de/home/proj/texrecon/index.en.jsp

MVE does not support mesh-editing, use Meshlab for that.

MVE also doesn't support masking depth maps by distance, you can, however, set a bounding box when you call `scene2pset`.

**Comment by ErfolgreichCharismatisch** [comment]
Meshlab's close holes does not close holes intelligently, it just looks for the shortest way. Autodesk ReMake could do that but it's not available anymore. Please share your approach with Meshlab or point to a tutorial.

**Comment by simonfuhrmann** [comment]
I don't have any other recommendations for closing holes.
