### ISSUE TITLE
Question regarding scale parameters for dmrecon and scene2pset

### ISSUE THREAD

**Issue by ssampang** [simonfuhrmann/mve#374]
Hi,

I'm unclear on the `F`/`fssr` parameter for `scene2pset`. The description `FSSR output, sets -nsc and -di with scale ARG` isn't very clear for users who don't know what `-nsc` and `-di` are :). The usage suggests that it has something to do with scale. Should it be set to the same value that was used for the `scale` parameter in `dmrecon`?

**Comment by simonfuhrmann** [comment]
The parameter `-nsc` actually means `-n -s -c`, and you can read in the `scene2pset` output what that does. The `-F` parameter is a scale, and it should be set to the same scale used with `dmrecon`. The latter creates depth maps, e.g., `depth-L2` for scale 2, and these depth maps are picked up when you set `-F2`.

So if you do `-F2` it will essentially do `scene2pset -n -s -c -ddepth-L2 -iundist-L2`.
