### ISSUE TITLE
How photogrammetry works

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [simonfuhrmann/mve#376]
To me, writing a photogrammetry software seems like an incredible amount of work to code even if you rely on many libraries.

I haven't read up on how it's done, yet, but I presume it all starts with pixel values that are being looked for in the other pictures to see similar points, then depending on distance you create a depth map, then you combine those depth maps again with distance measurements and assign voxels.

Is it that or did I miss a step?

**Comment by pmoulon** [comment]
I would advise to read some paper there:
https://www.gcc.tu-darmstadt.de/home/proj/mve/

[MVE – A Multi-View Reconstruction Environment](https://www.gcc.tu-darmstadt.de/media/gcc/papers/Fuhrmann-2014-MVE.pdf)

Else for a larger overview you can find some paper there:
https://github.com/openMVG/awesome_3DReconstruction_list

**Comment by simonfuhrmann** [comment]
Thanks Pierre for some references. The MVE paper gives a good overview of the reconstruction steps. But there are plenty of papers for each of the steps. Have fun reading.
