### ISSUE TITLE
Is there a way to improve reconstruction of black surfaces?

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [simonfuhrmann/mve#377]
![schwarz](https://user-images.githubusercontent.com/18123801/30733869-1a48588e-9f79-11e7-928f-ca4e8e29162c.jpg)

**Comment by simonfuhrmann** [comment]
`dmrecon` is not good at reconstructing textureless objects. You may want to try @flanggut SMVS for these surfaces.
https://github.com/flanggut/smvs
