### ISSUE TITLE
How do I make MVE accept the focal length from the EXIF in it's calculations to compute a better 3D model?

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [simonfuhrmann/mve#379]
I recorded a Gopro video in 4K wide. Then I extracted the frames and used them with mve.

Mve was bad at detecting, so I figured out the focal length (=17.2mm) and put it into the pictures' exif.

The program does not seem to pick up on that. How do I make it accept the focal length in it's calculations to compute a better model?

**Comment by simonfuhrmann** [comment]
MVE does look in the EXIF data for the focal length. It can only use the focal length if the camera is registered in the database. If you share an EXIF dump for one of the images, I can check if the camera is in the database.
