### ISSUE TITLE
How do I use the "--exif=ARG" parameter of sfmrecon?

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [simonfuhrmann/mve#380]
How do I use the `--exif=ARG` parameter of `sfmrecon`. Please share an example on how to set `focal length` if no focal length is present in the images.

**Comment by HelliceSaouli** [comment]
./sfmrecon -e will do the job.
Also try to check this out : [Issue 154]( https://github.com/simonfuhrmann/mve/issues/154)

**Comment by simonfuhrmann** [comment]
You don't have to touch the `--exif` argument. It's for locating the `exif` embedding, which is the EXIF blob extracted from the images. If the images don't have EXIF, you would have to use some tricks to initialize it along the lines of #154.
