### ISSUE TITLE
Iterative closest point (ICP) Algorithm

### ISSUE THREAD

**Issue by HelliceSaouli** [simonfuhrmann/mve#381]
Hello Sir

I was reading kinect fusion paper and they mentioned ICP algorithm and than I remembered that this algorithm is good for association  between point clods. in MVE/_scene2pset_ you just project depth maps all together in 3D to have final dense cloud. what if we align the projected depth map using ICP. would that effect the result of _fssrecon_.

**Comment by simonfuhrmann** [comment]
The depth maps that `scene2pset` generates are already aligned. It uses the camera parameters from SfM to do that. These parameters are usually VERY precise, i.e., in the order of sub-pixel reprojection accuracy. So there is really no point in doing ICP, and I bet ICP is going to make the alignment MUCH worse.
