### ISSUE TITLE
GCPs for georeferencing?

### ISSUE THREAD

**Issue by CarlosGrohmann** [simonfuhrmann/mve#386]
Does MVE support using GCPs (ground control points) to increase precision of the models? My research focus on deriving terrain models from UAV images and we use dGPS to get precise coordinates of targets on the ground which we can use in Photoscan/etc. MVE seems very promising and this would be a very important feature for us.

**Comment by simonfuhrmann** [comment]
The short version is: MVE doesn't support it. However, check out this issue with some more details and solutions:
https://github.com/simonfuhrmann/mve/issues/279

**Comment by flanggut** [comment]
Well, it sort of does. Have a look at this: https://github.com/simonfuhrmann/mve/pull/312

If you can create a list of 3D coordinates and corresponding 2D image coordinates this should work.

**Comment by flanggut** [comment]
Oh and if you use known 3D coordinates, try to normalize them down to something around the order of  1-10. I'm not familiar with all GPS systems but I think some coordinates might have insane scales which doesn't do well in the optimization (because precision matters).

**Comment by simonfuhrmann** [comment]
Do we actually optimize for GCPs in BA?

**Comment by CarlosGrohmann** [comment]
@flanggut a list of 3D coordinates and the corresponding 2D image coordinates is what we usually do with GCPs (see: https://github.com/OpenDroneMap/OpenDroneMap/wiki/Running-OpenDroneMap), but rescaling the coordinates to 1-10 wouldn't be useful, as we need the terrain models to be referenced to the real world coordinates (so we can use them in GIS analysis).

**Comment by simonfuhrmann** [comment]
Scaling to 1-10 doesn't mean you can't reference it in real word coordinates. Its just a scaling and possibly a translation. Until we support automatic transformation for numeric stability, that's the only solution.

**Comment by flanggut** [comment]
@simonfuhrmann Yes, we take care of the GCPs in BA. They are used to compute reprojection errors but their positions are constant so they are not changed by the BA. 

@CarlosGrohmann As Simon said, scaling doesn't make a difference. Let's say your original coordinates are [1000, 2000, 3000], you can just divide them by 1000 to get [1, 2, 3] which is more stable for the optimization. If you have your final mesh, you just multiply all coordinates by 1000 and it is referenced to your original coordinate system.

**Comment by CarlosGrohmann** [comment]
Thanks for the info @flanggut (and sorry for the late reply). Thinking on the proper academic description of the methods used in an analysis, what would be a good reference to cite about the numerical stability of the optimization?

**Comment by flanggut** [comment]
A general offset should also be fine, you just want to avoid the super large numbers.

I can't think of a specific publication to describe this. It's more like general knowledge, because floating point representations are just more accurate near 1.
