### ISSUE TITLE
missing filename in exception

### ISSUE THREAD

**Issue by fredlllll** [simonfuhrmann/mve#389]
hi there. im using opendronemap which somewhere uses mve. and i got the exception "cannot determine image format" which probably came from here https://github.com/simonfuhrmann/mve/blob/master/libs/mve/image_io.cc#L103

would you consider putting the filename in the exception text too?

same thing here https://github.com/simonfuhrmann/mve/blob/master/libs/mve/image_io.cc#L103

it would really help to know which image is causing problems, cause i can open them all

**Comment by simonfuhrmann** [comment]
Sure.

**Comment by fredlllll** [comment]
thanks :D
