### ISSUE TITLE
Camera positions viewer and/or exporter

### ISSUE THREAD

**Issue by cogitas3d** [simonfuhrmann/mve#392]
I would like to know if have some 3D viewer that you can see the cameras  and a way to export it to popular file formats like OBJ or DAE.

I study the .mve files but the informations about translation and rotation is a quite different that I usually work.

Thank you for the attention.

**Comment by nmoehrle** [comment]
You can view a scene with UMVE (_apps/umve/umve_), but there is currently no option to export the meshes used to render the cameras in UMVE to a OBJ file.
The camera format used in .mve files follows a common computer vision textbook notation and is explained in detail in the [Math-Cookbook](https://github.com/simonfuhrmann/mve/wiki/Math-Cookbook).

Best

**Comment by simonfuhrmann** [comment]
You can also export per-camera depth map reconstructions in UMVE in two ways, regular triangulation (ply, off, etc), and this Scanalize format (ply grid), both are very common.

**Comment by simonfuhrmann** [comment]
Here is a screenshot of UMVE
https://www.gcc.tu-darmstadt.de/home/proj/mve/

**Comment by cogitas3d** [comment]
Thank you very much @nmoehrle and @simonfuhrmann !
