### ISSUE TITLE
Which parameters are suitable to be used with pictures from gopro-cameras(SuperWide/Wide) either frames from video or photos?

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [simonfuhrmann/mve#394]
Details from the [gopro website](https://gopro.com/help/articles/Question_Answer/HERO4-Field-of-View-FOV-Information):

- Wide FOV | 17.2mm

```
          | V.FOV deg | H.FOV deg | Diag. FOV deg
4 x 3 W   | 94.4      | 122.6     | 149.2
16 x 9 W  | 69.5      | 118.2     | 133.6
```

Which parameters are suitable to be used with pictures from gopro-cameras(SuperWide/Wide) either frames from video or photos?

**Comment by flanggut** [comment]
Both should work, although photos usually provide a better quality. I would restrict it to the regular wide mode - super wide might have too much distortion.

**Comment by ErfolgreichCharismatisch** [comment]
Wide hasn't worked so far. Which parameters do I need to set for which programs for them to recognize the pictures according to the mentioned table?

**Comment by simonfuhrmann** [comment]
If the photos have proper EXIF tags, it should work automatically. If they don't, you'd have to inject the focal length in 35mm equivalent EXIF tag.
https://github.com/simonfuhrmann/mve/blob/master/libs/mve/image_exif.cc#L365

**Comment by ErfolgreichCharismatisch** [comment]
Injection does not work for me. How do you inject it properly and which commands do you use for it to be recognized?

**Comment by simonfuhrmann** [comment]
I don't have a command for you, but this website may:
http://u88.n24.queensu.ca/exiftool/forum/index.php?topic=2325.0

**Comment by ErfolgreichCharismatisch** [comment]
I used exiftool -exif:FocalLengthIn35mmFormat=17.2 -exif:FocalLength=14.0 *.jpg but it does not show up in meta.ini under focal_length.
My current workaround is to difish the video before, but this also doesn't work often. I presume it's better for mve to know the focal length and to defish it itself.

**Comment by simonfuhrmann** [comment]
1. I don't think you can use doubles
2. Does it show up in the .jpg file?
3. Did you re-run SfM?

**Comment by ErfolgreichCharismatisch** [comment]
> I don't think you can use doubles

You can't. But it sets the fl to 14mm and the 35mm fl to 17.
> Does it show up in the .jpg file?

Yes
> Did you re-run SfM?

Yes.
```
makescene -k -o -i "test" test
dmrecon -s3 test 
scene2pset -F3 test test\point-set.ply
```
...

**Comment by simonfuhrmann** [comment]
You re-run SfM by calling `sfmrecon`.

**Comment by ErfolgreichCharismatisch** [comment]
I did, I missed it here though. This is my full list:

```
makescene -k -o -i "test" test
sfmrecon test
dmrecon -s3 test 
scene2pset -F3 test test\point-set.ply
fssrecon test\point-set.ply test\surface.ply
meshclean -t10 -c10000 test\surface.ply test\surface-clean.ply
texrecon test::undistorted test\surface-clean.ply test\textured
pause
```

**Comment by ErfolgreichCharismatisch** [comment]
Should I see focal_length = 14 in meta.ini?

**Comment by simonfuhrmann** [comment]
You should see a valid focal length in the `meta.ini` file after `sfmrecon`, but it wouldn't be 14. The number is the optimized focal, so it will be different from your initial value, and it will be normalized, i.e., closer to 17/35 for the 35mm equivalent.

Also note that focal length is extracted for feature matching. If you already performed feature matching, you have to delete the `prebundle.sfm` file, and re-run feature matching.

**Comment by ErfolgreichCharismatisch** [comment]
I got `0.4866983593`. So it works.
