### ISSUE TITLE
Percentage & ETA for dmrecon

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [simonfuhrmann/mve#395]
See above.

**Comment by simonfuhrmann** [comment]
What's the question?

**Comment by ErfolgreichCharismatisch** [comment]
It's a feature request.

**Comment by simonfuhrmann** [comment]
Ah. Well, that's infeasible. `dmrecon` uses a region growing approach and can reconstruct anywhere between 0% and 100% of the pixels, and it's impossible to predict. The best we can do is show the queue length and current amount of reconstructed pixels. Which is what we do already.

**Comment by ErfolgreichCharismatisch** [comment]
Okay
