### ISSUE TITLE
fssr doesnt always return the same amount of vertices to same input data

### ISSUE THREAD

**Issue by panjekm** [simonfuhrmann/mve#397]
When running fssr tests I normally get about 50000 vertices after running my pointcloud through fssr. But sometimes it happens that 0 or some very small amount of vertices are returned even though i run the exact same test again.
Is the output of FSSR supposed to be deterministic?

![image](https://user-images.githubusercontent.com/16786244/35687732-c6317fdc-076f-11e8-9af0-079a4da1161c.png)

**Comment by simonfuhrmann** [comment]
This is odd, and I haven't seen this before. Yes, the output is supposed to be deterministic. How often does this happen? Your output also looks fine, given that 114k voxels have been initialized is an indicator that up until this step everything worked fine...

**Comment by panjekm** [comment]
It happens quite often, 50% of the time or so. Ill double check that its not something wrong with my input cloud...

**Comment by panjekm** [comment]
Ok. Seems like there was an issue with loading the pointcloud. We were converting PCLs PointSurfels in fssr::Samples, adding them to the fssr:SampleList and then adding them to octree using octree.insert_samples().
If we instead feed each fssr::Sample in octree by using octree.insert_sample() and not all at once then it works. A bit weird as insert_samples() just goes through the vector and calls insert_sample() for each one. Maybe there is some multithreading somewhere in the background and some parts dont finish in time?

**Comment by simonfuhrmann** [comment]
Inserting samples is not multi-threaded, as each insert can have side-effects like changing the octree structure. These two things (creating a vector then calling `insert_samples()` and calling `insert_sample()` on each sample) should be equivalent, as you stated, and as implemented.

I am still curious why this happens, but I'm glad it works now.
