### ISSUE TITLE
Query - can't start umve - failed to get the current screen resources

### ISSUE THREAD

**Issue by stanathong** [simonfuhrmann/mve#399]
Hello,

Thanks for making MVE and UMVE available.

I have successfully built mve and umve. However, when I tried to start umve by running ./umve. It showed messages below: 

failed to get the current screen resources
QXcbConnection: XCB error: 172 (Unknown), sequence: 163, resource id: 104, major code: 149 (Unknown), minor code: 20

I have looked through the previous reported issues but found none regarding this so I suspect it was the problem with my running system. Could anyone please share the solutions to what I am struggling with???

Thanks very much for your help.

**Comment by flanggut** [comment]
This looks weird, I think Qt doesn't find any appropriate displays to open the GUI on. Are you trying to run it on a remote machine?

**Comment by stanathong** [comment]
@flanggut Thanks for your quick reply. Yes, using x2go client. 
I might try reinstalling QT and will see if the problem still persists.

**Comment by simonfuhrmann** [comment]
I don't think OpenGL works remotely. As it needs to directly access the rendering hardware. Not sure about the "x2go" details here.

**Comment by stanathong** [comment]
@simonfuhrmann Thanks for your comment. Accessing the server remotely is the only choice for me. I'm just wanting to obtain the SFM results from MVE so I think I don't need UMVE for this matter.
