### ISSUE TITLE
[Feature Request] Recognition when recording was done with one light source on the camera

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [simonfuhrmann/mve#400]
Enable recognition even though light is showing from the camera at all times, for instance in dark settings, when you cannot light everything with external lights or your want to avoid lens-flares or you want to shed light in areas that are hard to reach with lamps without the lamps being obstacles or conceal areas of the object.

**Comment by flanggut** [comment]
Sorry but this is not possible. Stereo matching will never work properly in this scenario.

**Comment by ErfolgreichCharismatisch** [comment]
What are the challenges you see here?

**Comment by flanggut** [comment]
Feature and stereo matching assume that the appearance of the surface is independent of the viewing direction. In the setup you're describing this is not true, so all possible photo-consistency measures will fail.
