### ISSUE TITLE
[Feature Request] Fill black/undetected areas with the surrounding color and fill the voxels in between smoothly

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [simonfuhrmann/mve#405]
Fill black/undetected areas with the surrounding color and fill the voxels in between smoothly instead of creating holes.

**Comment by ErfolgreichCharismatisch** [comment]
Make it optional

**Comment by simonfuhrmann** [comment]
What you're suggesting is difficult and will probably not work. All this will do is hallucinate the wrong depth values that are inconsistent with other depth maps. If you're aiming for a global reconstruction, you should instead look into approaches that do regularization and interpolation in the final reconstruction step.

**Comment by ErfolgreichCharismatisch** [comment]
> If you're aiming for a more complete global reconstruction, you should instead look into approaches that do regularization and interpolation in the final reconstruction step.

Please be more specific.

**Comment by HelliceSaouli** [comment]
I suggest you read this paper ( tutorial made by Furukawa ) about Multi view stereo **" Multi-View Stereo: A Tutorial - Carlos Hernandez"**. escape to the last section of the paper (Limitations) and hopefully, you will form a good idea
