### ISSUE TITLE
Which general guidelines do you recommend for shooting useful photos?

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [simonfuhrmann/mve#406]
My experience is that to get good models, you need to

1. Keep exposure time the same
1. Keep the aperture size the same
1. not take photos of shallow objects
1. not take photos of moving objects
1. not use a fisheye lens

What else?

**Comment by simonfuhrmann** [comment]
Exposure is not that relevant, only if you're interested in a good texturing. Aperture radius should be small to keep everything in focus, keeping it constant is less relevant. Scenes should generally be static.

It helps to have a good lens with small radial distortion; this is why wide angle lenses usually don't work that well, and the fisheye camera model is not supported.

It's generally more important from where you take the photos, not how your camera settings are given that you consider the above advice. Reposition the camera not just circular around an object, but in a spherical "dome" shape. Use different distances to reconstruct both low- and high-frequency geometry, which helps to fill holes in the geometry.

http://simonfuhrmann.de/papers/cg2015-mve.pdf has some tips how to capture photos.

**Comment by ErfolgreichCharismatisch** [comment]
After reading your pdf, I became even more confident that giving the user the option to set rough positions of the camera in space will eliminate a lot of the problems you are facing. A first step could be done by mvs and then be corrected manually in a 3D space environment by moving the pictures to the appropriate locations if desired.
