### ISSUE TITLE
MVE does not produce output file .ply with some image inputs

### ISSUE THREAD

**Issue by thuyndieu** [simonfuhrmann/mve#410]
Hi, Simon, 
I am using your MVE apps for 3D reconstruction. Currently I am testing apps with some board circuit images ([https://www.dropbox.com/sh/kv614zfzjhdlqdv/AAB1kqVObKsuyaQvMLmcCkPla?dl=0](url)). I keep the board circuit standing still and move the camera around. Another way is, camera is static and I rotate the board circuit. In both case, the apps do not produce any matching of inputs. I assumed that because of the illumination and reflections on the board. 
Can you give me any hint for the inputs? For other samples, the apps work fine. 
Thank you.

**Comment by flanggut** [comment]
The board is almost only metal. Metal changes it's appearance depending on the angle you're looking from so it is impossible to match surface points across multiple images and you won't be able to reconstruct it with stereo methods.

**Comment by thuyndieu** [comment]
thank you. So in this case, what would you suggest to reconstruct the board? I can suppress the reflections on the board :)

**Comment by simonfuhrmann** [comment]
It's highly unlikely that you'll get a decent reconstruction out of this. Even if you use chalk spray to make it non-specular, you'll not have textures, and all the thin structures are challenging to reconstruct. I'd probably give up on this.
