### ISSUE TITLE
mve produces empty output

### ISSUE THREAD

**Issue by stiv-yakovenko** [simonfuhrmann/mve#412]
Here is my dataset: https://drive.google.com/drive/folders/1egatZWvy575HHdu82bdgXqEJH2vs1Rcx?usp=sharing

I add files this way: 

> makescene.exe -i C:\Users\steve\Dropbox\Projects\kinnekt\data\car\rect\png\ C:\Users\steve\Dropbox\Projects\kinnekt\data\car\rect\sc

(this command seems to succeed)
Then I launch reconstruction:

> sfmrecon.exe  C:\Users\steve\Dropbox\Projects\kinnekt\data\car\rect\sc

> MVE SfM Reconstruction (built on Mar 27 2018, 07:09:29)
> SSE2 accelerated matching is enabled.
> SSE3 accelerated matching is enabled.
> Initializing scene with 15 views...
> Initialized 15 views (max ID is 14), took 9ms.
> Loading pairwise matching from file...
> Cleanup: Released 0 embeddings in 0 of 15 views.
> Initializing camera intrinsics...
> Warning: No EXIF embedding for view 0, using fallback!
> Warning: No EXIF embedding for view 1, using fallback!
> Warning: No EXIF embedding for view 2, using fallback!
> Warning: No EXIF embedding for view 3, using fallback!
> Warning: No EXIF embedding for view 4, using fallback!
> Warning: No EXIF embedding for view 5, using fallback!
> Warning: No EXIF embedding for view 6, using fallback!
> Warning: No EXIF embedding for view 7, using fallback!
> Warning: No EXIF embedding for view 8, using fallback!
> Warning: No EXIF embedding for view 9, using fallback!
> Warning: No EXIF embedding for view 10, using fallback!
> Warning: No EXIF embedding for view 11, using fallback!
> Warning: No EXIF embedding for view 12, using fallback!
> Warning: No EXIF embedding for view 13, using fallback!
> Warning: No EXIF embedding for view 14, using fallback!
> Computing feature tracks...
> Propagating track IDs...
> Removing tracks with conflicts... deleted 26 tracks.
> Colorizing tracks...
> Created a total of 5389 tracks.
> Searching for initial pair...
>   Pair  11, 13:  777 matches,  726 H-inliers (93%)
>   Pair  11, 12:  858 matches,  829 H-inliers (96%)
>   Pair  13, 14:  959 matches,  935 H-inliers (97%)
>   Pair  12, 13: 1000 matches,  966 H-inliers (96%)
>   Pair   0, 10:  672 matches,  609 H-inliers (90%)
>   Pair   2,  3:  597 matches,  533 H-inliers (89%)
>   Pair   9, 10:  764 matches,  717 H-inliers (93%)
>   Pair  12, 14:  662 matches,  645 H-inliers (97%)
>   Pair   2, 14:  315 matches,  308 H-inliers (97%)
>   Pair   0,  9:  473 matches,  422 H-inliers (89%)
>   Pair   8,  9:  343 matches,  337 H-inliers (98%)
>   Pair  11, 14:  516 matches,  473 H-inliers (91%)
>   Pair   8, 14:  248 matches,  237 H-inliers (95%)
>   Pair   0,  1:  245 matches,  222 H-inliers (90%)
>   Pair   8, 13:  251 matches,  244 H-inliers (97%)
>   Pair   7,  8:  244 matches,  229 H-inliers (93%)
>   Pair   3,  4:  232 matches,  224 H-inliers (96%)
>   Pair   6, 13:  230 matches,  221 H-inliers (96%)
>   Pair   6, 14:  222 matches,  217 H-inliers (97%)
>   Pair   8, 12:  230 matches,  223 H-inliers (96%)
>   Pair   2, 13:  221 matches,  216 H-inliers (97%)
>   Pair   4,  5:  211 matches,  193 H-inliers (91%)
>   Pair   1, 10:  219 matches,  199 H-inliers (90%)
>   Pair   8, 11:  211 matches,  205 H-inliers (97%)
>   Pair   5, 11:  208 matches,  197 H-inliers (94%)
>   Pair   7, 12:  207 matches,  198 H-inliers (95%)
>   Pair   7, 11:  205 matches,  194 H-inliers (94%)
>   Pair   5, 13:  203 matches,  195 H-inliers (96%)
>   Pair   8, 10:  200 matches,  196 H-inliers (98%)
>   Pair   6, 12:  194 matches,  191 H-inliers (98%)
>   Pair   5, 12:  193 matches,  185 H-inliers (95%)
>   Pair   7, 13:  189 matches,  178 H-inliers (94%)
>   Pair   6, 11:  184 matches,  174 H-inliers (94%)
>   Pair   5, 14:  182 matches,  175 H-inliers (96%)
>   Pair   3, 14:  181 matches,  165 H-inliers (91%)
>   Pair   5,  6:  176 matches,  172 H-inliers (97%)
>   Pair   2, 12:  175 matches,  169 H-inliers (96%)
>   Pair   1,  9:  172 matches,  154 H-inliers (89%)
>   Pair   7, 14:  164 matches,  151 H-inliers (92%)
>   Pair   2,  9:  162 matches,  154 H-inliers (95%)
>   Pair   9, 14:  161 matches,  150 H-inliers (93%)
>   Pair   1,  5:  158 matches,  154 H-inliers (97%)
>   Pair   2,  4:  159 matches,  153 H-inliers (96%)
>   Pair   2, 11:  155 matches,  145 H-inliers (93%)
>   Pair   2,  8:  146 matches,  139 H-inliers (95%)
>   Pair   4, 14:  144 matches,  135 H-inliers (93%)
>   Pair   2, 10:  147 matches,  140 H-inliers (95%)
>   Pair   9, 13:  139 matches,  129 H-inliers (92%)
>   Pair   1,  4:  136 matches,  133 H-inliers (97%)
>   Pair   2,  5:  131 matches,  120 H-inliers (91%)
>   Pair  10, 14:  131 matches,  121 H-inliers (92%)
>   Pair   4, 11:  131 matches,  112 H-inliers (85%)
>   Pair   0,  8:  129 matches,  125 H-inliers (96%)
>   Pair   4, 13:  129 matches,  118 H-inliers (91%)
>   Pair   3, 13:  126 matches,  115 H-inliers (91%)
>   Pair   3,  5:  124 matches,  109 H-inliers (87%)
>   Pair   3, 11:  124 matches,  111 H-inliers (89%)
>   Pair   3, 12:  116 matches,  107 H-inliers (92%)
>   Pair   7,  9:  112 matches,  101 H-inliers (90%)
>   Pair   4, 12:  110 matches,  107 H-inliers (97%)
>   Pair   3,  8:  106 matches,   99 H-inliers (93%)
>   Pair   9, 12:  109 matches,   98 H-inliers (89%)
>   Pair  10, 12:  105 matches,   91 H-inliers (86%)
>   Pair  10, 13:  105 matches,   91 H-inliers (86%)
>   Pair   4, 10:  103 matches,   93 H-inliers (90%)
>   Pair   9, 11:  104 matches,   94 H-inliers (90%)
>   Pair   5,  8:  101 matches,   95 H-inliers (94%)
>   Pair  10, 11:   99 matches,   85 H-inliers (85%)
>   Pair   2,  7:   96 matches,   85 H-inliers (88%)
>   Pair   2,  6:   91 matches,   87 H-inliers (95%)
>   Pair   4,  8:   91 matches,   89 H-inliers (97%)
>   Pair   1,  8:   89 matches,   80 H-inliers (89%)
>   Pair   4,  9:   88 matches,   80 H-inliers (90%)
>   Pair   6,  8:   87 matches,   78 H-inliers (89%)
>   Pair   1, 12:   85 matches,   77 H-inliers (90%)
>   Pair   7, 10:   85 matches,   77 H-inliers (90%)
>   Pair   0,  2:   84 matches,   76 H-inliers (90%)
>   Pair   3, 10:   83 matches,   72 H-inliers (86%)
>   Pair   5, 10:   83 matches,   74 H-inliers (89%)
>   Pair   1,  7:   82 matches,   79 H-inliers (96%)
>   Pair   0,  4:   78 matches,   68 H-inliers (87%)
>   Pair   0,  5:   78 matches,   70 H-inliers (89%)
>   Pair   1, 11:   78 matches,   71 H-inliers (91%)
>   Pair   3,  6:   76 matches,   67 H-inliers (88%)
>   Pair   3,  9:   75 matches,   66 H-inliers (88%)
>   Pair   6,  7:   74 matches,   69 H-inliers (93%)
>   Pair   1,  2:   72 matches,   63 H-inliers (87%)
>   Pair   0, 14:   70 matches,   54 H-inliers (77%),  3.20 pair angle
>   Pair   1, 14:   69 matches,   61 H-inliers (88%)
>   Pair   0, 13:   69 matches,   44 H-inliers (63%)
>   Pair   5,  9:   68 matches,   61 H-inliers (89%)
>   Pair   0, 11:   68 matches,   43 H-inliers (63%),  8.53 pair angle
>   Pair   1, 13:   68 matches,   59 H-inliers (86%)
>   Pair   5,  7:   68 matches,   60 H-inliers (88%)
>   Pair   1,  6:   65 matches,   57 H-inliers (87%)
>   Pair   0,  7:   62 matches,   52 H-inliers (83%)
>   Pair   4,  6:   61 matches,   59 H-inliers (96%)
>   Pair   0, 12:   57 matches,   37 H-inliers (64%),  3.67 pair angle
>   Pair   0,  6:   46 matches
>   Pair   6,  9:   41 matches
>   Pair   6, 10:   33 matches
>   Pair   1,  3:   31 matches
>   Pair   4,  7:   54 matches,   33 H-inliers (61%), 12.35 pair angle
>   Pair   0,  3:   53 matches,   40 H-inliers (75%), 18.57 pair angle
>   Pair   3,  7:   53 matches,   40 H-inliers (75%)
> Searching for pair with best score...
> Using views 0 and 11 as initial pair.
> Triangulated 5 new tracks, rejected 63 bad tracks.
>   Rejected 12 tracks with large error.
>   Rejected 51 tracks with unstable angle.
>   Splitted 0 new tracks.
> Deleted 0 of 5 tracks (0.00%) above a threshold of 0.0159496.
> Running full bundle adjustment...
> BA: MSE 2.72751e-05 -> 4.67641e-10, 3 LM iters, 50 CG iters, 2ms.
> Camera   0, focal length: 1.00000 -> 0.99729, distortion: 0.02990 0.23148
> Camera  11, focal length: 1.00000 -> 0.96884, distortion: 0.00522 3.40669
> No valid next view.
> SfM reconstruction finished.
> SfM reconstruction took 5451 ms.
> Creating bundle data structure...
> Writing bundle (15 cameras, 5 features): C:/Users/steve/Dropbox/Projects/kinnekt/data/car/rect/sc/synth_0.out...
> Saving view C:/Users/steve/Dropbox/Projects/kinnekt/data/car/rect/sc/views/view_0011.mve
> Saving view C:/Users/steve/Dropbox/Projects/kinnekt/data/car/rect/sc/views/view_0000.mve

dmrecon output:

> C:\Users\steve\Projects\mve\apps\dmrecon\RelWithDebInfo>dmrecon.exe  -s2 C:\Users\steve\Dropbox\Projects\kinnekt\data\car\rect\sc
> MVE Depth Map Reconstruction (built on Mar 27 2018, 07:09:12)
> Initializing scene with 15 views...
> Initialized 15 views (max ID is 14), took 9ms.
> Reading Photosynther file (15 cameras, 5 features)...
> Reconstructing all views...
> Reconstruction took 3ms.
> Saving views back to disc...
> Saving views to MVE files... done.

On the next step:

> C:\Users\steve\Projects\mve\apps\scene2pset\RelWithDebInfo>scene2pset.exe  -F2 C:\Users\steve\Dropbox\Projects\kinnekt\data\car\rect\sc m.ply
> MVE Scene to Pointset (built on Mar 27 2018, 07:09:21)
> Using depthmap "depth-L2" and color image "undist-L2"
> Initializing scene with 15 views...
> Initialized 15 views (max ID is 14), took 16ms.
> Processing view "6" (with colors)...
> Processing view "0" (with colors)...
> Writing final point set (0 points)...
> Writing PLY file (0 verts, with colors, with normals, with confidences, with values, 0 faces)... done.

I get an empty PLY file:

> ply
> format binary_little_endian 1.0
> comment Export generated by libmve
> element vertex 0
> property float x
> property float y
> property float z
> property float nx
> property float ny
> property float nz
> property uchar red
> property uchar green
> property uchar blue
> property float confidence
> property float value
> end_header

Are there any parameters which I should try to tune to get this working? VisualSFM is able to produce decent reconstruction from same images.

**Comment by simonfuhrmann** [comment]
`sfmrecon` fails to find a good initial pair because the scene is mostly planar. Try specifying an initial pair manually, such as 11 and 13.

Having this said, it's unlikely

**Comment by simonfuhrmann** [comment]
`sfmrecon` fails to find a good initial pair because the scene is mostly planar. Try specifying an initial pair manually, such as 11 and 13.

Having this said, it's unlikely that this dataset will reconstruct well. The car is reflective and doesn't have texture, which is pretty much worst case scenario.

**Comment by stiv-yakovenko** [comment]
How can I do this?

**Comment by flanggut** [comment]
`sfmrecon` has command line options, just run it without any arguments and you'll get a full list. In your case its `--initial-pair=...`

**Comment by stiv-yakovenko** [comment]
initial-pair doens't help, ply is still empty

**Comment by simonfuhrmann** [comment]
Then try a different initial pair. Or import the output from VisualSfM, which makescene can do for you.
