### ISSUE TITLE
Core dumped on "scene inspect" tab

### ISSUE THREAD

**Issue by Harvie** [simonfuhrmann/mve#414]
```
[harvie@anemophobia photoscan]$ umve --gl
Resizing GL from 0x0 to 577x623
Resizing GL from 577x623 to 577x602
Using OpenGL 2.1 ...
Skipping shaders from /usr/local/bin/shaders/surface_330.*
Skipping shaders from /usr/local/bin/shaders/wireframe_330.*
Skipping shaders from /usr/local/bin/shaders/texture_330.*
Skipping shaders from /usr/local/bin/shaders/overlay_330.*
Skipping shaders from /home/harvie/.local/share/umve/shaderssurface_330.*
Skipping shaders from /home/harvie/.local/share/umve/shaderswireframe_330.*
Skipping shaders from /home/harvie/.local/share/umve/shaderstexture_330.*
Skipping shaders from /home/harvie/.local/share/umve/shadersoverlay_330.*
Skipping shaders from /usr/local/share/umve/shaders/surface_330.*
Skipping shaders from /usr/local/share/umve/shaders/wireframe_330.*
Skipping shaders from /usr/local/share/umve/shaders/texture_330.*
Skipping shaders from /usr/local/share/umve/shaders/overlay_330.*
Skipping shaders from /usr/share/umve/shaders/surface_330.*
Skipping shaders from /usr/share/umve/shaders/wireframe_330.*
Skipping shaders from /usr/share/umve/shaders/texture_330.*
Skipping shaders from /usr/share/umve/shaders/overlay_330.*
Using built-in surface shader.
terminate called after throwing an instance of 'util::Exception'
  what():  0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES

Neúspěšně ukončen (SIGABRT) (core dumped [obraz paměti uložen])
```

**Comment by Harvie** [comment]
On ArchLinux wiki i've found this:

`You only get support for GLSL 3.30 if you work with a forward-compatible (core) OpenGL context with version 3.3. You have to request that explicitely on context creation.`

Maybe it can be added to umve code.

**Comment by flanggut** [comment]
UMVE does request the correct context. If you can’t create an appropriate context, you’re either in a mobile setting (which we don’t support), or your system is configured wrong for some reason. A random 3rd party library won’t change that. Also, OpenGL 3.3 is more than 8 years old - there is absolutely no reason to support older architectures.

**Comment by Harvie** [comment]
Is there way to switch to software rendering at cost of performance loss?

**Comment by simonfuhrmann** [comment]
I am wondering if this is an issue with your driver or your graphics card. If you card supports OpenGL 3, you can probably upgrade your drivers?

**Comment by Harvie** [comment]
@simonfuhrmann unfortunately it seems to me that thinkpad x201 supports ogl only up to 2.1 :-/

**Comment by simonfuhrmann** [comment]
Then there's not much I can do, sorry. I'm closing this.
Regarding software rendering, I really don't know how to enable this. Maybe by disabling your hardware-accelerated graphics driver in the Xorg config? You'd also need a version of Mesa that supports OpenGL 3.
