### ISSUE TITLE
How to lower processing quality to get speedup trade?

### ISSUE THREAD

**Issue by Harvie** [simonfuhrmann/mve#416]
Before i run big MVE job (4 to 20 hours) i like to test if everything is OK with my photo dataset. Right now i use agisoft photoscan with low(est) settings and it can generate mesh from 200 8Mpx photos in 2 to 10 minutes (depending) how low i go with the settings. If there's no problem with low definition model, i go forward and run hours long job to get precise hi definition model from MVE.

I wonder what is reccomended way of doing this fast preview (that would calculate in around 5 minutes) using MVE. Should i decrease resolution of the photos? I use `dmrecon` parameter `-s2`, which should scale all photos down to 50%, but even the `sfmrecon` can easily take one hour for dataset with 200 photos. I've found no way to set `sfmrecon` to produce some low quality, but fast matches. I guess the same applies for other commands in my processing pipeline (as seen in script at the end of this post).

Also i am afraid that lowering the resolution of all photos (eg. using imagemagick: `mogrify -resize 25% *.jpg` or `mogrify -resize 500000@\> *` = limit to 0.5 Mpx) would be contraproductive as it might destroy the only matchable features in image. I guess it's just better to detect just some of the features of high res photo (and ignore the rest) than match all features on low res photo.

What should i do to get preview mesh in 2 to 10 minutes from 200 pieces of 8Mpx photos using MVE?

Eg. i've made this in agisoft (no GPU acceleration) under 10 minutes:

![image](https://user-images.githubusercontent.com/276504/38279843-8ecfe89a-37a2-11e8-94fd-5b4541c4d11a.png)

Then i made this from the same dataset in 12 hours using MVE:

![image](https://user-images.githubusercontent.com/276504/38279839-8915b4c0-37a2-11e8-85d5-25c4b445d05f.png)

It would make more sense to do the pre-flight preview in the same software that i use for final processing. But i don't know how to do that in MVE.

```
#!/bin/bash
set -x

makescene -i ./img ./scn
sfmrecon ./scn
dmrecon -s2 ./scn
scene2pset -F2 ./scn ./scn/pset-L2.ply
fssrecon ./scn/pset-L2.ply ./scn/surface-L2.ply
meshclean -t10 ./scn/surface-L2.ply ./scn/surface-L2-clean.ply
```

**Comment by Harvie** [comment]
I've found that simply running `makescene` with `-m 500000` increases speed extremely (while still everything takes longer than 10 minutes, but there's space for lowering that even further).

I guess **we can close this ticket** as i am relatively satisfied with what i've found. But before doing so i hope i'll get some more tips and tricks on speedup. Especialy related to some fine tuning of MVE performance using the parameters i've mentioned in previous post.

**Comment by simonfuhrmann** [comment]
Yes, `--max-pixels` is what you want for `sfmrecon` (or, `makescene` if you prefer that). Scale your images down to 1MP or even less to get results quicker. As a general suggestion, I would import high-res images with `makescene`, unless you want to safe space, and use `--max-pixels` for `sfmrecon` only.

If you specify `--max-pixels` on `sfmrecon` and not on `makescene`, it will just downscale images in memory for SfM, but you can still work on high-res images later in the pipeline. So for `dmrecon`, you have to specify again what image size you want to process. Either use `--scale`, or better, `--max-pixels` as well.

**Comment by simonfuhrmann** [comment]
I wouldn't play around with `--local-neighbors` for `dmrecon`, it doesn't safe you much time. `scene2pset` and `fssrecon` will automatically be faster as `dmrecon` produces less depth samples on lower resolution images. I wouldn't try tuning any parameters with `fssrecon` (especially not `--refine-octree` or `--scale-factor`, these are development features).

**Comment by Harvie** [comment]
Thanks for clarification.
