### ISSUE TITLE
Support for view clustering and removing redundant photos

### ISSUE THREAD

**Issue by Harvie** [simonfuhrmann/mve#417]
It sounds really usefull for processing large number of photos to have view clustering functionality. Also removing redundant or useless photos from dataset seems very useful to speed up the MVE operation.

These problems are already solved by CMVS https://www.di.ens.fr/cmvs/ , but that has some (not much) external dependencies (some of which could possibly be replaced with internal MVE code or other libraries already used by MVE itself).

**Comment by simonfuhrmann** [comment]
At this time we can't take larger feature requests as MVE is in maintenance mode, and we don't have the time to add features. So I am afraid I have to leave this request unfulfilled.

**Comment by flanggut** [comment]
Sure, feel free to adjust the code. That’s why we’re open source :)

**Comment by pmoulon** [comment]
@Harvie You can take a look to this: https://github.com/openMVG/openMVG/tree/master/src/software/SfM/clustering/domSetLibrary
