### ISSUE TITLE
Global View Selection failed

### ISSUE THREAD

**Issue by s9j4n8dba** [simonfuhrmann/mve#418]
What can be done to avoid or fix "Global View Selection failed" error, while running dmrecon? sfmrecon appears to be working fine and finding correspondences.

> 
> dmrecon -s2 ./vid_frames_4/mve
> MVE Depth Map Reconstruction (built on May 17 2016, 12:36:21)
> Initializing scene with 230 views...
> Initialized 230 views (max ID is 229), took 76ms.
> Reading Photosynther file (230 cameras, 0 features)...
> Reconstructing all views...
> scaled image size: 304 x 171
> Global View Selection failedscaled image size: 304 x 171
> 
> Global View Selection failed
> Reconstruction took 132ms.
> Saving views back to disc...
> Saving views to MVE files... done.

**Comment by simonfuhrmann** [comment]
I don't think `sfmrecon` was working fine. The log you posted says `0 features`. Have you inspected the scene in `UMVE`? What is the output of `sfmrecon`?

**Comment by s9j4n8dba** [comment]
I see, it appears that sfmrecon finds a lot of matches, but decided many weren't good enough. In the end it reports only 7 features. I guess this issue can be closed then.

> Computing feature tracks...
> Propagating track IDs...
> Removing tracks with conflicts... deleted 1078 tracks.
> Colorizing tracks...
> Created a total of 26251 tracks.
> Searching for initial pair...
>   Pair  10, 12:  620 matches,  585 H-inliers (94%)
>   Pair  17, 18:  599 matches,  597 H-inliers (99%)
>   Pair  11, 12:  764 matches,  758 H-inliers (99%)
>   Pair  10, 11:  692 matches,  683 H-inliers (98%)
>   Pair   9, 10:  576 matches,  568 H-inliers (98%)
>   Pair   9, 11:  506 matches,  466 H-inliers (92%)
>   Pair  18, 19:  488 matches,  473 H-inliers (96%)
>   Pair  19, 20:  585 matches,  574 H-inliers (98%)
>   Pair  42, 44:  458 matches,  454 H-inliers (99%)
>   Pair  12, 14:  463 matches,  358 H-inliers (77%)
>   Pair  28, 29:  459 matches,  320 H-inliers (69%)
>   Pair  20, 21:  483 matches,  469 H-inliers (97%)
>   Pair  16, 17:  447 matches,  434 H-inliers (97%)
>   Pair   9, 12:  455 matches,  420 H-inliers (92%)
>   Pair  11, 14:  435 matches,  312 H-inliers (71%)
>   Pair  27, 28:  439 matches,  320 H-inliers (72%)
>   Pair  12, 13:  434 matches,  417 H-inliers (96%)
>   Pair  19, 21:  408 matches,  389 H-inliers (95%)
>   Pair  17, 19:  401 matches,  354 H-inliers (88%)
>   Pair  11, 13:  401 matches,  356 H-inliers (88%)
>   Pair  29, 30:  395 matches,  274 H-inliers (69%)
>   Pair 209,210:  394 matches,  368 H-inliers (93%)
>   Pair 162,163:  392 matches,  386 H-inliers (98%)
>   Pair  26, 27:  390 matches,  274 H-inliers (70%)
>   Pair 101,102:  389 matches,  326 H-inliers (83%)
>   Pair  10, 13:  384 matches,  330 H-inliers (85%)
>   Pair  13, 14:  381 matches,  309 H-inliers (81%)
>   Pair  10, 14:  379 matches,  277 H-inliers (73%)
>   Pair  15, 16:  376 matches,  367 H-inliers (97%)
>   Pair  43, 44:  376 matches,  374 H-inliers (99%)
>   Pair  25, 26:  376 matches,  266 H-inliers (70%)
>   Pair 148,149:  373 matches,  368 H-inliers (98%)
>   Pair  50, 51:  370 matches,  301 H-inliers (81%)
>   Pair  18, 20:  369 matches,  300 H-inliers (81%)
>   Pair 147,148:  368 matches,  359 H-inliers (97%)
>   Pair  21, 22:  362 matches,  186 H-inliers (51%),  1.47 pair angle
>   Pair  16, 18:  361 matches,  344 H-inliers (95%)
>   Pair   4,  5:  358 matches,  237 H-inliers (66%)
>   Pair 161,162:  349 matches,  347 H-inliers (99%)
>   Pair 145,147:  347 matches,  341 H-inliers (98%)
>   Pair 144,145:  345 matches,  340 H-inliers (98%)
>   Pair  24, 25:  344 matches,  248 H-inliers (72%)
>   Pair  30, 31:  344 matches,  250 H-inliers (72%)
>   Pair 143,145:  343 matches,  337 H-inliers (98%)
>   Pair  27, 29:  342 matches,  217 H-inliers (63%)
>   Pair   7,  8:  339 matches,  337 H-inliers (99%)
>   Pair   9, 13:  337 matches,  291 H-inliers (86%)
>   Pair  26, 28:  338 matches,  230 H-inliers (68%)
>   Pair  28, 30:  335 matches,  217 H-inliers (64%)
>   Pair  22, 23:  332 matches,  159 H-inliers (47%),  1.10 pair angle
>   Pair   8,  9:  331 matches,  324 H-inliers (97%)
>   Pair 208,209:  330 matches,  277 H-inliers (83%)
>   Pair 203,204:  329 matches,  304 H-inliers (92%)
>   Pair 142,143:  328 matches,  321 H-inliers (97%)
>   Pair   9, 14:  325 matches,  232 H-inliers (71%)
>   Pair 147,149:  325 matches,  308 H-inliers (94%)
>   Pair  14, 15:  321 matches,  272 H-inliers (84%)
>   Pair 143,144:  320 matches,  315 H-inliers (98%)
>   Pair 166,167:  318 matches,  310 H-inliers (97%)
>   Pair 141,142:  318 matches,  312 H-inliers (98%)
>   Pair   5,  6:  316 matches,  210 H-inliers (66%)
>   Pair 210,211:  317 matches,  286 H-inliers (90%)
>   Pair  25, 27:  316 matches,  215 H-inliers (68%)
>   Pair  20, 22:  313 matches,  152 H-inliers (48%),  1.08 pair angle
>   Pair  17, 20:  310 matches,  224 H-inliers (72%)
>   Pair 149,150:  307 matches,  299 H-inliers (97%)
>   Pair   6,  7:  306 matches,  265 H-inliers (86%)
>   Pair  13, 15:  304 matches,  205 H-inliers (67%)
>   Pair  14, 16:  301 matches,  210 H-inliers (69%)
>   Pair 204,205:  297 matches,  280 H-inliers (94%)
>   Pair 115,116:  296 matches,  263 H-inliers (88%)
>   Pair 147,150:  296 matches,  285 H-inliers (96%)
>   Pair   8, 10:  294 matches,  256 H-inliers (87%)
>   Pair 148,150:  293 matches,  285 H-inliers (97%)
>   Pair 221,222:  291 matches,  250 H-inliers (85%)
>   Pair  23, 24:  291 matches,  198 H-inliers (68%)
>   Pair 208,210:  289 matches,  242 H-inliers (83%)
>   Pair 142,145:  287 matches,  275 H-inliers (95%)
>   Pair  40, 44:  287 matches,  280 H-inliers (97%)
>   Pair   2,  3:  283 matches,  178 H-inliers (62%)
>   Pair 153,154:  282 matches,  279 H-inliers (98%)
>   Pair  14, 17:  282 matches,  175 H-inliers (62%)
>   Pair 205,206:  281 matches,  253 H-inliers (90%)
>   Pair  16, 19:  281 matches,  230 H-inliers (81%)
>   Pair   8, 13:  279 matches,  220 H-inliers (78%)
>   Pair  18, 21:  278 matches,  230 H-inliers (82%)
>   Pair  15, 17:  276 matches,  234 H-inliers (84%)
>   Pair  35, 36:  274 matches,  210 H-inliers (76%)
>   Pair  26, 29:  272 matches,  185 H-inliers (68%)
>   Pair  24, 26:  271 matches,  194 H-inliers (71%)
>   Pair 161,163:  271 matches,  265 H-inliers (97%)
>   Pair 122,123:  271 matches,  247 H-inliers (91%)
>   Pair 223,224:  270 matches,  258 H-inliers (95%)
>   Pair 141,143:  270 matches,  264 H-inliers (97%)
>   Pair  19, 22:  268 matches,  150 H-inliers (55%),  1.52 pair angle
>   Pair 145,148:  268 matches,  258 H-inliers (96%)
>   Pair   3,  4:  268 matches,  183 H-inliers (68%)
>   Pair  25, 28:  267 matches,  183 H-inliers (68%)
>   Pair 142,144:  267 matches,  255 H-inliers (95%)
>   Pair 165,166:  266 matches,  263 H-inliers (98%)
>   Pair 204,206:  265 matches,  223 H-inliers (84%)
>   Pair  40, 43:  265 matches,  262 H-inliers (98%)
>   Pair 206,207:  264 matches,  210 H-inliers (79%)
>   Pair 132,133:  262 matches,  245 H-inliers (93%)
>   Pair 191,192:  262 matches,  199 H-inliers (75%)
>   Pair 218,219:  262 matches,  231 H-inliers (88%)
>   Pair 105,106:  261 matches,  190 H-inliers (72%)
>   Pair  27, 30:  261 matches,  169 H-inliers (64%)
>   Pair  41, 44:  260 matches,  258 H-inliers (99%)
>   Pair 224,225:  260 matches,  251 H-inliers (96%)
>   Pair 152,154:  258 matches,  252 H-inliers (97%)
>   Pair 183,184:  258 matches,  184 H-inliers (71%)
>   Pair  12, 15:  257 matches,  155 H-inliers (60%)
>   Pair  11, 15:  255 matches,  161 H-inliers (63%)
>   Pair 190,191:  253 matches,  206 H-inliers (81%)
>   Pair 207,208:  252 matches,  195 H-inliers (77%)
>   Pair  39, 40:  252 matches,  247 H-inliers (98%)
>   Pair 150,151:  251 matches,  246 H-inliers (98%)
>   Pair 152,153:  251 matches,  245 H-inliers (97%)
>   Pair  21, 23:  251 matches,  128 H-inliers (50%),  2.18 pair angle
>   Pair 112,113:  250 matches,  199 H-inliers (79%)
>   Pair   8, 12:  249 matches,  190 H-inliers (76%)
>   Pair   6,  8:  248 matches,  207 H-inliers (83%)
>   Pair  41, 42:  248 matches,  242 H-inliers (97%)
>   Pair 209,211:  248 matches,  212 H-inliers (85%)
>   Pair 203,205:  248 matches,  212 H-inliers (85%)
>   Pair  13, 16:  248 matches,  148 H-inliers (59%),  0.76 pair angle
>   Pair  42, 43:  248 matches,  245 H-inliers (98%)
>   Pair  17, 21:  247 matches,  195 H-inliers (78%)
>   Pair 143,147:  247 matches,  239 H-inliers (96%)
>   Pair  40, 42:  246 matches,  242 H-inliers (98%)
>   Pair 145,149:  246 matches,  235 H-inliers (95%)
>   Pair  14, 18:  246 matches,  149 H-inliers (60%)
>   Pair 217,218:  244 matches,  190 H-inliers (77%)
>   Pair 205,207:  245 matches,  177 H-inliers (72%)
>   Pair 136,137:  243 matches,  228 H-inliers (93%)
>   Pair  12, 16:  243 matches,  139 H-inliers (57%),  3.14 pair angle
>   Pair 154,155:  243 matches,  237 H-inliers (97%)
>   Pair   8, 11:  243 matches,  191 H-inliers (78%)
>   Pair   3,  5:  243 matches,  139 H-inliers (57%),  3.67 pair angle
>   Pair 119,120:  243 matches,  214 H-inliers (88%)
>   Pair 216,217:  243 matches,  154 H-inliers (63%)
>   Pair 219,221:  242 matches,  166 H-inliers (68%)
>   Pair  54, 55:  240 matches,  187 H-inliers (77%)
>   Pair 131,132:  239 matches,  216 H-inliers (90%)
>   Pair 148,151:  239 matches,  238 H-inliers (99%)
>   Pair 222,223:  238 matches,  201 H-inliers (84%)
>   Pair 203,206:  238 matches,  179 H-inliers (75%)
>   Pair  10, 15:  238 matches,  155 H-inliers (65%)
>   Pair 151,152:  237 matches,  231 H-inliers (97%)
>   Pair 108,109:  238 matches,  166 H-inliers (69%)
>   Pair 144,147:  237 matches,  221 H-inliers (93%)
>   Pair  12, 17:  236 matches,  130 H-inliers (55%),  0.97 pair angle
>   Pair 217,219:  234 matches,  139 H-inliers (59%),  1.02 pair angle
>   Pair  29, 31:  234 matches,  147 H-inliers (62%)
>   Pair  15, 18:  234 matches,  190 H-inliers (81%)
>   Pair 223,225:  231 matches,  188 H-inliers (81%)
>   Pair 141,144:  230 matches,  217 H-inliers (94%)
>   Pair 109,110:  231 matches,  184 H-inliers (79%)
>   Pair 188,189:  230 matches,  173 H-inliers (75%)
>   Pair 151,153:  229 matches,  223 H-inliers (97%)
>   Pair 116,117:  229 matches,  203 H-inliers (88%)
>   Pair  16, 20:  229 matches,  160 H-inliers (69%)
>   Pair   9, 15:  228 matches,  148 H-inliers (64%)
>   Pair 135,136:  228 matches,  221 H-inliers (96%)
>   Pair  11, 16:  227 matches,  135 H-inliers (59%),  4.64 pair angle
>   Pair 153,155:  227 matches,  222 H-inliers (97%)
>   Pair 160,161:  226 matches,  222 H-inliers (98%)
>   Pair  28, 31:  226 matches,  132 H-inliers (58%),  2.51 pair angle
>   Pair 163,165:  225 matches,  221 H-inliers (98%)
>   Pair 208,211:  225 matches,  175 H-inliers (77%)
>   Pair 141,145:  225 matches,  212 H-inliers (94%)
>   Pair 134,135:  225 matches,  216 H-inliers (96%)
>   Pair 167,168:  224 matches,  220 H-inliers (98%)
>   Pair 214,215:  224 matches,  146 H-inliers (65%)
>   Pair 149,151:  224 matches,  220 H-inliers (98%)
>   Pair 150,152:  224 matches,  218 H-inliers (97%)
>   Pair 192,193:  222 matches,  185 H-inliers (83%)
>   Pair  84, 85:  221 matches,  202 H-inliers (91%)
>   Pair  40, 41:  221 matches,  212 H-inliers (95%)
>   Pair 137,138:  220 matches,  201 H-inliers (91%)
>   Pair 133,135:  220 matches,  202 H-inliers (91%)
>   Pair 165,167:  220 matches,  218 H-inliers (99%)
>   Pair 149,152:  220 matches,  213 H-inliers (96%)
>   Pair  11, 17:  219 matches,  125 H-inliers (57%),  1.10 pair angle
>   Pair 144,148:  219 matches,  208 H-inliers (94%)
>   Pair 206,208:  219 matches,  152 H-inliers (69%)
>   Pair 219,222:  218 matches,  112 H-inliers (51%),  1.10 pair angle
>   Pair  26, 30:  218 matches,  144 H-inliers (66%)
>   Pair 130,131:  217 matches,  202 H-inliers (93%)
>   Pair 202,203:  218 matches,  194 H-inliers (88%)
>   Pair  12, 18:  217 matches,  126 H-inliers (58%)
>   Pair 189,190:  216 matches,  171 H-inliers (79%)
>   Pair  20, 23:  215 matches,  106 H-inliers (49%),  3.48 pair angle
>   Pair 120,121:  213 matches,  185 H-inliers (86%)
>   Pair 221,223:  213 matches,  138 H-inliers (64%)
>   Pair  24, 27:  213 matches,  153 H-inliers (71%)
>   Pair  31, 32:  213 matches,  126 H-inliers (59%),  1.40 pair angle
>   Pair  25, 29:  213 matches,  143 H-inliers (67%)
>   Pair 111,112:  212 matches,  166 H-inliers (78%)
>   Pair 156,157:  212 matches,  205 H-inliers (96%)
>   Pair 121,122:  212 matches,  193 H-inliers (91%)
>   Pair 211,212:  211 matches,  189 H-inliers (89%)
>   Pair 172,173:  211 matches,  174 H-inliers (82%)
>   Pair 118,119:  210 matches,  186 H-inliers (88%)
>   Pair   8, 14:  208 matches,  155 H-inliers (74%)
>   Pair   7,  9:  207 matches,  203 H-inliers (98%)
>   Pair 121,123:  207 matches,  190 H-inliers (91%)
>   Pair 117,118:  207 matches,  187 H-inliers (90%)
>   Pair 133,134:  206 matches,  189 H-inliers (91%)
>   Pair 204,207:  206 matches,  136 H-inliers (66%)
>   Pair 142,147:  204 matches,  194 H-inliers (95%)
>   Pair  18, 22:  203 matches,  122 H-inliers (60%)
>   Pair  10, 16:  203 matches,  128 H-inliers (63%)
>   Pair 189,191:  202 matches,  154 H-inliers (76%)
>   Pair 145,150:  202 matches,  193 H-inliers (95%)
>   Pair 152,155:  202 matches,  194 H-inliers (96%)
>   Pair 159,161:  201 matches,  199 H-inliers (99%)
>   Pair  11, 18:  201 matches,  122 H-inliers (60%)
>   Pair  14, 19:  200 matches,  124 H-inliers (62%)
>   Pair 219,220:  200 matches,  181 H-inliers (90%)
>   Pair  32, 33:  200 matches,  113 H-inliers (56%),  1.03 pair angle
>   Pair 116,118:  199 matches,  172 H-inliers (86%)
>   Pair 123,124:  197 matches,  174 H-inliers (88%)
>   Pair  19, 23:  199 matches,  111 H-inliers (55%),  3.72 pair angle
>   Pair   4,  6:  197 matches,  137 H-inliers (69%)
>   Pair  52, 53:  196 matches,  150 H-inliers (76%)
>   Pair   9, 16:  196 matches,  127 H-inliers (64%)
>   Pair 155,157:  196 matches,  190 H-inliers (96%)
>   Pair 143,148:  196 matches,  192 H-inliers (97%)
>   Pair 131,133:  196 matches,  165 H-inliers (84%)
>   Pair 147,151:  195 matches,  192 H-inliers (98%)
>   Pair  13, 17:  195 matches,  123 H-inliers (63%)
>   Pair 147,152:  194 matches,  186 H-inliers (95%)
>   Pair  10, 17:  194 matches,  110 H-inliers (56%),  4.33 pair angle
>   Pair 163,166:  193 matches,  187 H-inliers (96%)
>   Pair 220,221:  193 matches,  170 H-inliers (88%)
>   Pair 129,130:  193 matches,  175 H-inliers (90%)
>   Pair 104,105:  192 matches,  151 H-inliers (78%)
>   Pair  81, 82:  192 matches,  161 H-inliers (83%)
>   Pair 175,176:  192 matches,  142 H-inliers (73%)
>   Pair 207,209:  191 matches,  144 H-inliers (75%)
>   Pair  11,210:  191 matches,  168 H-inliers (87%)
>   Pair 202,204:  191 matches,  159 H-inliers (83%)
>   Pair 159,160:  191 matches,  189 H-inliers (98%)
>   Pair 114,115:  190 matches,  169 H-inliers (88%)
>   Pair  12,210:  190 matches,  164 H-inliers (86%)
>   Pair 218,221:  189 matches,  100 H-inliers (52%),  1.14 pair angle
>   Pair 157,158:  189 matches,  182 H-inliers (96%)
>   Pair 115,117:  186 matches,  172 H-inliers (92%)
>   Pair 203,207:  187 matches,  122 H-inliers (65%)
>   Pair 148,152:  186 matches,  183 H-inliers (98%)
>   Pair  55, 56:  186 matches,  145 H-inliers (77%)
>   Pair 210,212:  185 matches,  151 H-inliers (81%)
>   Pair  15, 19:  185 matches,  136 H-inliers (73%)
>   Pair 151,154:  184 matches,  179 H-inliers (97%)
>   Pair   8, 15:  184 matches,  125 H-inliers (67%)
>   Pair 202,205:  184 matches,  140 H-inliers (76%)
>   Pair  24, 28:  183 matches,  123 H-inliers (67%)
>   Pair  17, 22:  183 matches,  110 H-inliers (60%)
>   Pair 150,153:  183 matches,  172 H-inliers (93%)
>   Pair 113,115:  183 matches,  147 H-inliers (80%)
>   Pair 160,162:  182 matches,  179 H-inliers (98%)
>   Pair 184,185:  182 matches,  160 H-inliers (87%)
>   Pair 213,214:  182 matches,  119 H-inliers (65%)
>   Pair  34, 35:  182 matches,  127 H-inliers (69%)
>   Pair  22, 24:  181 matches,  103 H-inliers (56%),  1.45 pair angle
>   Pair 142,148:  181 matches,  174 H-inliers (96%)
>   Pair 222,224:  181 matches,  135 H-inliers (74%)
>   Pair  33, 34:  181 matches,  124 H-inliers (68%)
>   Pair  93,162:  181 matches,  180 H-inliers (99%)
>   Pair 225,226:  181 matches,  175 H-inliers (96%)
>   Pair 130,132:  180 matches,  144 H-inliers (80%)
>   Pair 155,156:  180 matches,  173 H-inliers (96%)
>   Pair 136,138:  180 matches,  163 H-inliers (90%)
>   Pair 150,154:  180 matches,  167 H-inliers (92%)
>   Pair 217,221:  177 matches,   82 H-inliers (46%),  1.34 pair angle
>   Pair   2,  4:  178 matches,   98 H-inliers (55%),  4.19 pair angle
>   Pair 149,154:  177 matches,  167 H-inliers (94%)
>   Pair 222,225:  177 matches,  110 H-inliers (62%)
>   Pair 149,153:  176 matches,  167 H-inliers (94%)
>   Pair 132,135:  176 matches,  164 H-inliers (93%)
>   Pair 154,156:  176 matches,  174 H-inliers (98%)
>   Pair  16, 21:  175 matches,  110 H-inliers (62%)
>   Pair  12,209:  174 matches,  150 H-inliers (86%)
>   Pair  27, 31:  174 matches,  101 H-inliers (58%),  7.47 pair angle
>   Pair   5,  7:  173 matches,  148 H-inliers (85%)
>   Pair 216,218:  173 matches,   94 H-inliers (54%),  1.02 pair angle
>   Pair 215,216:  172 matches,   99 H-inliers (57%),  1.24 pair angle
> Using views 27 and 31 as initial pair.
> Triangulated 7 new tracks, rejected 167 bad tracks.
>   Rejected 13 tracks with large error.
>   Rejected 130 tracks behind cameras.
>   Rejected 24 tracks with unstable angle.
> Deleted 0 of 7 tracks (0.00%) above a threshold of 0.0460345.
> Running full bundle adjustment...
> PBA: MSE 6.63796e-05 -> 8.42441e-09 (M), 6 iter, 75ms.
> Camera 27, focal length: 1 -> 0.998712, distortion: 0.268901
> Camera 31, focal length: 1 -> 1.03319, distortion: -0.0405923
> SfM reconstruction finished.
> SfM reconstruction took 32742 ms.
> Creating bundle data structure...
> Writing bundle (230 cameras, 7 features): ./vid_frames_4/mve/synth_0.out...
> Saving view C:/Users/Guetzkow/Videos/./vid_frames_4/mve/views/view_0018.mve
> Saving view C:/Users/Guetzkow/Videos/./vid_frames_4/mve/views/view_0011.mve
> Saving view C:/Users/Guetzkow/Videos/./vid_frames_4/mve/views/view_0027.mve
> Saving view C:/Users/Guetzkow/Videos/./vid_frames_4/mve/views/view_0031.mve

**Comment by simonfuhrmann** [comment]
Yes, the initial pair selection failed. Try manually specifying an initial pair with the `--initial-pair` flag.
