### ISSUE TITLE
Can I use these .ply file into MVE

### ISSUE THREAD

**Issue by yonelay11** [simonfuhrmann/mve#422]
Hello, 
I already have (.ply) file. Can I use these .ply file into MVE instead of images.

**Comment by HelliceSaouli** [comment]
you can clean your ply file using _meshclean_ or you can convert your mesh to point cloud using _mesh2pset_
also u can convert point cloud to surface using floating point _fssrecon_

**Comment by yonelay11** [comment]
I mean I already the sparse point cloud (.ply) file type generated by SfM and then I segment these point cloud by using Min-cut Algorithm. I want to reconstructed these segmented output into mesh model by MVE. In MVE, the input type is images., right?So, I want to know can I use these (.ply) into MVE instead of images.

**Comment by HelliceSaouli** [comment]
use fssrecon

**Comment by yonelay11** [comment]
Thank you for your advice @HelliceSaouli . I will try it.
