### ISSUE TITLE
Which workflow was proven to work to convert an 360° Equi-Angular Youtube-Video to frames useful with mve?

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [simonfuhrmann/mve#425]
See title.

**Comment by simonfuhrmann** [comment]
I'm not sure if anyone has proven it, but you should render overlapping perspective projections from the equi-rectangular video. Are these videos stereo? I wouldn't expect phenomenal results as the baseline between the two eyes is usually IPD ad 65mm, and not enough baseline to produce good stereo results.

**Comment by ErfolgreichCharismatisch** [comment]
The idea is to use 360°-videos by people walking around items, so you get a lot of different angles.
Which software should be used under windows?
