### ISSUE TITLE
Does MVE use GPS priors for estimating camera poses?

### ISSUE THREAD

**Issue by stanathong** [simonfuhrmann/mve#432]
Thanks for sharing your work.

I have a set of images tagged with GPS. Does MVE read GPS coordinates in exif and use them as priors for estimating camera poses? Thanks very much.

**Comment by simonfuhrmann** [comment]
Unfortunately, we don't have support for this. We support, however, ground control points. Not sure if that's useful in your situation.

**Comment by stanathong** [comment]
Thanks for your swift reply.
