### ISSUE TITLE
sfmrecon.exe not found in windows mve

### ISSUE THREAD

**Issue by MaxKrapp** [simonfuhrmann/mve#435]
![image](https://user-images.githubusercontent.com/23382521/40542078-d715bbf8-601e-11e8-9ab0-373b05651509.png)

Hi, I tried to directly use the MVE with executables to create the following pipeline 
```
makescene -i <image-dir> <scene-dir>
sfmrecon <scene-dir>
dmrecon -s2 <scene-dir>
scene2pset -F2 <scene-dir> <scene-dir>/pset-L2.ply
fssrecon <scene-dir>/pset-L2.ply <scene-dir>/surface-L2.ply
meshclean -t10 <scene-dir>/surface-L2.ply <scene-dir>/surface-L2-clean.ply
```

How ever i dont have the sfmrecon.exe file.....  Is there an alternative executable I can use instead? 
The Building of the git repo failed which is why I used the win binaries.

**Comment by simonfuhrmann** [comment]
Windows is not supported. It's likely these binaries are seriously outdated.
@andre-schulz, do you know how old these binaries are? Can we update the zip?

**Comment by andre-schulz** [comment]
@MaxKrapp, where did you download the binaries? The only official link I'm aware of is https://www.gcc.tu-darmstadt.de/media/gcc/code/mve-20160517-win64.zip which has `sfmrecon` but those binaries are also outdated.
Can you please tell us what went wrong when you tried to compile MVE?
@simonfuhrmann, no idea how old they are. I'll try to contact someone who can update the zip file.

**Comment by MaxKrapp** [comment]
@andre-schulz I downloaded exactly that link from the tu darmstadt but sfm recon was not in the zip folder. I got the executable then downloaded from https://git.ustclug.org/zfwang/FastSFM/tree/master/mve.
I am currently using the MeshRecon Pipeline from http://zhuoliang.me/meshrecon.html to test the Programms with the gargoyle images provided. I just exchanged the GPU steps in the nv file to CPU and then ran the programm getting an empty .ply file. Can you provide any test images that I can compare which step in the pipeline is breaking?
