### ISSUE TITLE
Does MVE automatically aligns model to cardinal points?

### ISSUE THREAD

**Issue by lvella** [simonfuhrmann/mve#439]
I've built a model with MVE from a set of pictures taken with a drone who writes GPS coordinates in the EXIF. Visually, the +x direction seemed aligned with north, and -z with up direction. Was the GPS coordinates used for alignment? Was the alignment a coincidence or can I count on this behavior?

**Comment by simonfuhrmann** [comment]
MVE doesn't read the GPS coordinate. This behavior was "coincidence", or rather a result of which image pairs have been chosen as initial pair. I guess since most of your photos are taken on a plane, that's what caused the overall geometry to roughly coincide with the coordinate system.
