### ISSUE TITLE
how i calculate depth?

### ISSUE THREAD

**Issue by ardashir66** [simonfuhrmann/mve#440]
hi.
i want to convert 2D point to 3D point. i used this method that you mentioned
`X = R^T * (K^-1 * x * d - t)`
but i dont know how i calculate d? 

i have only one camera and (K,R,t) matrix.

thanks in advance

**Comment by simonfuhrmann** [comment]
Sorry, can you explain your scenario a little bit more? Do you have a depth map? How is this question related to MVE?

**Comment by ardashir66** [comment]
I just see https://github.com/simonfuhrmann/mve/wiki/Math-Cookbook 
then i used it for my calibration and reconstruction 3D point.
my project is measurement of cars in road. i have to calibrate and find length of cars. 
i only know road dimension in real world as a rectangle. i don't know how u calculate D(depth)!

**Comment by simonfuhrmann** [comment]
That formula kind of assumes you know the depth. How you compute depth depends on your application. I'm closing this since it doesn't seem to be related to MVE. Feel free to re-open if it is.
