### ISSUE TITLE
mesh2pset unreferenced vertices

### ISSUE THREAD

**Issue by Poutsh** [simonfuhrmann/mve#442]
Hi.

I would like to use mesh2pset on a ply file that I generated with another program that only contains x, y, z, r, g, b (in ascii format) in order to have the normals and the scale value to use it with fssrecon. It only contains vertices.

But when I use mesh2pset I get this warning : 
Warning: 38239 unreferenced vertices.

And when I use fssrecon : 
WARNING: Skipped 38239 samples with invalid scale.

I checked mesh2pset code and basically it seems to skip every vertices of my ply file when it computes scale and put 0 as a scale value.

Did I do something wrong or is it  a bug? An explanation would be nice, thank you in advance. The ply file I'm using is attached.
[ply.txt](https://github.com/simonfuhrmann/mve/files/2274692/ply.txt)

**Comment by flanggut** [comment]
Your "mesh" does not contain any triangles so it is not really a mesh and rather a pointset. This is also the reason for `Warning: 38239 unreferenced vertices.` The vertices are not referenced in any traingles.

In this case it is impossible to estimate a reasonable scale and awkward to estimate normals. So your approach will simply not work as long as you don't have triangles or explicit normals and scales.

See also #281 and #298.

**Comment by simonfuhrmann** [comment]
@flanggut is correct, this is working as intended. The `mesh2pset` tool uses the mesh triangulation to estimate scale and normals. If you don't have a triangulation, this tool won't work for you. Estimating normals and scale solely from a point cloud is not trivial, very much depends on the application, and is thus not supported.
