### ISSUE TITLE
MVE Depth Map Reconstruction - problem

### ISSUE THREAD

**Issue by elenaVal** [simonfuhrmann/mve#443]
Hello, i am quite new to the MVE project. I am trying to integrate MVE in a qt c++ project. 
However, when i am trying to call the dmrecon  command, i got the following: 

> MVE Depth Map Reconstruction (built on Jul 16 2018, 17:27:11)
> Initializing scene with 10 views...
> View: Unrecognized extension undistorted.png.new, skipping.
> View: Unrecognized extension undistorted.png.new, skipping.
> View: Unrecognized extension undistorted.png.new, skipping.
> View: Unrecognized extension undistorted.png.new, skipping.
> Initialized 10 views (max ID is 9), took 62ms.
> Reading Photosynther file (10 cameras, 2068 features)...
> Reconstructing all views...
> Invalid master view
> Invalid master view
> Invalid master view
> Invalid master view
> 
It seems that the makescene and sfmrecon are executed correctly. 
Did you have any idea why?

Thank you in advance

**Comment by simonfuhrmann** [comment]
It's probably because of what it said: "Unrecognized extension undistorted.png.new"
MVE identifies image types based on extension. `.new` is not a recognized image extension.

**Comment by elenaVal** [comment]
I totally understand that MVE is not recognized ".new" image extension, however the undistorted images are created dynamically after the "sfmrecon" command and after making a check the undistorted images have .png extension only. So i do not know, how the "dmrecon" trying to read a undistorted.png.new file. Do you have any thoughts?

**Comment by simonfuhrmann** [comment]
If you have files in your view directory that MVE doesn't recognize (it recognizes png, jpeg, mvei and blob files), it will ignore these files.
If you want to make `dmrecon` use a different file, not the undistorted one, use the `--image` command line argument. Call `dmrecon` without arguments to get a help text.

If this doesn't solve your problem, please give some more information on what you're trying to do. Post the command you're trying to run. Also, please list the contents of one of your view directories, i.e., `ls <your-scene>/views/view_0000.mve/*`.
