### ISSUE TITLE
Load: Sparse & Dense point cloud

### ISSUE THREAD

**Issue by elenaVal** [simonfuhrmann/mve#446]
Hello, 

I would like to ask, if there is any way to open-load the intermediate outputs of the calculated sparse and dense point cloud which are produced before the mesh generation. 

In my case, i am trying to develop an app when the user can "select" if he wants to produce only the sparse or dense or mesh from a set of images.

Thanks a lot

**Comment by simonfuhrmann** [comment]
I'm not sure I understand the question. If you run `sfmrecon`, you will get camera poses and sparse points. You will have to run `dmrecon` if you want depth maps, and then `scene2pset` if you want dense points (essentially dumping all the depth map pixels in a point cloud).

You can access all these artifacts using the MVE libraries. Let me know if you have specific questions.

**Comment by elenaVal** [comment]
Thanks a lot for your answer. Yes, what i am trying to do is to give the user the option to calculate only (for example) the sparse point cloud and if the output of the `sfmrecon` can be previewed in a 3D viewer. At the same logic, if a user wants to calculate only the dense point cloud without the mesh, in this case if the `dmrecon ` output can be previewed in a 3D viewer.

Finally, a more general question within the MVE libraries there is also an .exe file, which is an interface where the user can load the mesh. Is it any command that i can use in order to view the 3D model inside my code (i am using C++/QT) without run this .exe file? 

Thank you in advance

**Comment by simonfuhrmann** [comment]
In C++, you can get the sparse point cloud from the mve::Bundle class. You can load the bundle manually, or obtain it from mve::Scene. To get dense point clouds, given they have been computed before, look at the code in scene2pset.

You may be able to fork some code from UMVE to display the points and meshes. MVE provides a gl library with a bunch of helpers for OpenGL, that work together with the datastructures in the mve library.

**Comment by HelliceSaouli** [comment]
Just use MVE libs and build your app with it. you can use the `mve::geom::load_mesh` to load your point cloud (PLY file)
