### ISSUE TITLE
textured the mesh(build by kinfu but with blur texture)

### ISSUE THREAD

**Issue by 18500864609** [simonfuhrmann/mve#447]
Hello ,
      I'm wondering if I could input the mesh built by kinfu and the images to output a better textured mesh like you  displayed result. If so, what should I pay attention to? wish for your reply ,thanks,

**Comment by simonfuhrmann** [comment]
What is "kinfu"? What "displayed result"?

**Comment by 18500864609** [comment]
Sorry, I didn't say it clearly. kinfu means the kinectfusion method which use the TSDF and marhing cubes method ,but when I try to use it to reconstruct face, the texture(color fusion )result was not good(blur).display result means I try the mvs-texturing with your mesh. it output a good texture.
I am not sure if I have made it clear, but I am glad to receive your reply.

**Comment by simonfuhrmann** [comment]
So yes, vertex coloring is not a great texturing strategy. You can use mvs-texturing, which will probably produce a much better result, as you mentioned. Now, what's the question exactly?

**Comment by 18500864609** [comment]
the question is if I have the mesh made by kineticfusion and the images with its' transform ,how to use the mvs-texturing to get a textured mesh!

**Comment by simonfuhrmann** [comment]
That's a question for the mvs-texturing folks.
https://github.com/nmoehrle/mvs-texturing

I assume you'd create an MVE scene from the images (`makescene -i`) and then add your camera intrinsics/extrinsics to the `meta.ini` file, as described in their documentation.
