### ISSUE TITLE
how to use FSSR to make the pointcloud to the mesh

### ISSUE THREAD

**Issue by 18500864609** [simonfuhrmann/mve#448]
Hello, I have get a pointcloud mode  in ply format(build by pcl),Can I use the FSSR to get a mesh from the pointcloud?
if so,can you give me some advice on how to change the pointcloud's format……

**Comment by 18500864609** [comment]
sorry to trouble you again. I want to make sure that weather the ply format must bebinary_little_endian 1.0 and what is the value and confidence mean?
I just have a pointcloud with x,y,z,nx,ny,nz,and r,g,b can I set the value and confidence 1.0?

**Comment by simonfuhrmann** [comment]
I'm not sure which PLY formats we support, but I believe all of them, that is binary LE and BE, and Ascii.

If you don't have confidence values for your points, you can just set them to 1.0 for all points. That's fine. However, the "value" attribute is important. It's the scale value of the samples. If you don't have scale values, you won't be able to use FSSR. While you could approximate the scale value from the average sample spacing, this is not recommended. Average sample spacing doesn't take redundancy and, well, the actual scale of the samples into account. See the publication "Floating scale surface reconstruction" for details what the scale value means.

What is the source of your data? If your samples are originating from a depth map, you'll be able to generate very good scale values. If you just obtained a point cloud without having any further information, maybe FSSR is not the right approach for your reconstruction task.

**Comment by 18500864609** [comment]
I'm glad to receive your reply,I just use a RGBD camera, using color maps and depth maps to get a color point cloud (ply)with  kinectfusion. I tried to resconstruct the color point cloud (ply)with FSSR. the first pic is pointcloud made by kinectfusion .the second one is made by FSSR .
![1](https://user-images.githubusercontent.com/35217567/47334087-323d3a00-d6b8-11e8-990f-a27b9a07c29b.jpg)
![_20181023113550](https://user-images.githubusercontent.com/35217567/47334092-408b5600-d6b8-11e8-9d01-fc30b4bfe7b0.jpg)
I'm wondering whether the mash patch grids should be reduce.
Another problem is whether I can make use of the scene2pset with depth images to get a pointcloud,now I tried with a problem that this procedure doesn't know the depth image(png)but .mvei format .so can you give me some advice.

**Comment by simonfuhrmann** [comment]
The FSSR reconstruction looks (bottom image?) very low resolution which is probably an issue with the scale values (the "value" PLY attribute). If you can, you should really try to import the depth maps into the views and use `scene2pset` to extract the point cloud. It will set the scale values for you, and properly take redundancy into account.

To see how depth maps work in MVE, I recommend you take a few dozens smart phone photos of a diffuse, texture-rich object, and follow the steps for image based reconstruction [1]. Then, after the `dmrecon` step, you can see the depth maps in UMVE and see how they are stored in the views.

[1] https://github.com/simonfuhrmann/mve/wiki/MVE-Users-Guide#the-reconstruction-pipeline

**Comment by 18500864609** [comment]
I'm sorry that it's hard for me to use the depth PNG to compute the pointcloud with scene2pset . Because after the dmrecon step,I can't see the depth maps in UMVE .I just use the opencv to save the depth map in PNG format ,Can you instruct me how to change it to be used in the next step?

**Comment by simonfuhrmann** [comment]
I'm not familiar with OpenCV. You'd have to save the depth map as a float image in `.mvei` format. The spec for the image format is here [1]. The depth values are the distances from the camera center.

[1] https://github.com/simonfuhrmann/mve/wiki/MVE-File-Format#the-mvei-image-format

**Comment by 18500864609** [comment]
hello, I have met another problem with the fssr.
it show :invalid PLY signature, 
I have make the ply file with ofstream.and I test it in ubuntu16.04,it 's ok!
however,when I make the ply file in windows, it can't work.
so I want to ask whether the systems make it a invalid PLY signature ,or somethingelse?

**Comment by simonfuhrmann** [comment]
Because you didn't set `std::ofstream::binary` on the file?
