### ISSUE TITLE
Scaling resolution

### ISSUE THREAD

**Issue by Muminpappan** [simonfuhrmann/mve#449]
Hi,

I have a couple of image that I'm trying to reconstruct into 3D. It works quite well when I use `--scale=2` in dmrecon, but if I lower the scaling number I get an empty point cloud after `scene2pset` which of course makes the rest of the pipeline fail. I have also tried altering the `--max-pixels` option because my images are larger than the default values here, but that doesn't help either.

I would prefer a better resolution 3D object in the end than the one I get using `--scale=2`. Is it otherwise possible to use the 3D surface or point cloud that I do get, but apply the colors with higher resolution?

Any ideas what the problem is, or what I'm doing wrong? Or any thoughts about how I can increase the final resolution?

**Comment by simonfuhrmann** [comment]
I think what's going wrong is you still use the `-F2` flag on `scene2pset`, but if you change the scale, say to `--scale=1`, you'll also need to change the flag to `-F1`.

The `--max-pixels` option is useful when you have input images at very different resolutions, say images you downloaded from a community photo collection, and you want your depth maps at roughly the same resolution.

Having this said, you can combine different scales pretty easily. Say you computed your depth maps with  various scales, just run `scene2pset` a few times:

    scene2pset -F0 scene pset-L0.ply
    scene2pset -F0 scene pset-L1.ply
    ...

and then use FSSR to operate on all the point sets at once

    fssrecon pset-L0.ply pset-L1.ply ... out.ply

Hope this helps.

**Comment by Muminpappan** [comment]
Thank you for the very good explanation! This sound exactly like what I wanted to hear. I will test this right away!

**Comment by Muminpappan** [comment]
Once again, thank you for the help @simonfuhrmann !

I ran the pipeline with scaling 0, 1 and 2, and the results were indeed better! Although it seems like only 2 of my 3 objects overlapped, since the resulting object actually is 2 objects a few centimeters apart. It seems like the scale 0 object didn't get the same position in 3d space as scale 1 and 2 (from the looks of it, it only/mostly differs in the depth direction).

Any ideas why that might be?

**Comment by simonfuhrmann** [comment]
Oh yea, you only want one scene for the three scales. MVE stores different scales in different files, e.g, "depth-L0", "depth-L1", etc. Also note that, depending on your image resolution, it's rarely advisable to really reconstruct at L0. In my experience, it takes way to long to reconstruct, and produces very incomplete depth maps. It all depends on your application though.
