### ISSUE TITLE
PMVS coupled with MVE

### ISSUE THREAD

**Issue by HelliceSaouli** [simonfuhrmann/mve#461]
Hey.
Happy new year to you guys. hope all of you doing ok.

Well, I want to know how accurate can we get if we used the patches resulted from early stages of PMVS as initialization for _dmrecom_ ?

**Comment by simonfuhrmann** [comment]
PMVS patches live in global coordinates, no? So you'd have to reproject them first. You may get some additional completeness from it, not sure about accuracy. Only one way to find out :-)
