### ISSUE TITLE
How to use prebundle.sfm file in sfmrecon?

### ISSUE THREAD

**Issue by jun1217** [simonfuhrmann/mve#462]
I want use my own prebundle.sfm file in sfmrecon procedure writed by opencv, when I detected all features,matched all pairs, and saved in prebundle.sfm, But when I sfmrecon this file , It pointed out 
what():  Cannot compute pose for initial pair, 
I want to know the rules behind the save_prebundle precedure, Is there some tricks behide hand made prebundle.sfm? Thanks!

**Comment by jun1217** [comment]
I use sift detector and describer provide by OpenCV, simulate the save_prebundle_data by MVE ,and  the question is :
1. When writing all view data , Does it needed write all features per image to prebundle?
2. When writing matching pairs, is there a order ? For example , matches_all[i][j]?matches_all[j][i]?queryIdx?trainIdx?
3. I have saved the prebundle.sfm, And the load_prebundle_data can works well, But when sfm_recon, It got wrong, I know it because first pair to reconstruct , No enough  pair. So I realise It should be the wrong type I have wrote.

**Comment by jun1217** [comment]
Thanks！
I found the question that the coordinate of keypoint should be normalized before saved as `prebundle.sfm` file. But when I tried to `sfmrecon` using this file ,I found almost all tracks had be Rejected with unstable angle. I'm working on it, Do you have any good ideas? Thanks，sincerely！

**Comment by simonfuhrmann** [comment]
The features get rejected because the baseline between the two photos is too small. Could this be the reason?

**Comment by jun1217** [comment]
Maybe not. Because I have try your MVE `sfmrecon`,It got the right result,  I think it may be some differences between hand mand features and mve features. I will have a try. Thanks!

**Comment by jun1217** [comment]
`Removing tracks with conflicts... deleted 528 tracks.
Colorizing tracks...
Created a total of 1709 tracks.
Reconstructing initial pair...
Using views 0 and 1 as initial pair.
Triangulated 3 new tracks, rejected 1706 bad tracks.
  Rejected 1706 tracks with unstable angle.
  Splitted 0 new tracks.
Deleted 0 of 3 tracks (0.00%) above a threshold of 0.0169314.
Running full bundle adjustment...
BA: MSE 3.71873e-05 -> 7.13134e-12, 3 LM iters, 30 CG iters, 0ms.
Camera   0, focal length: 1.00000 -> 0.92862, distortion: -0.28862 0.10762
Camera   1, focal length: 1.00000 -> 1.09934, distortion: 0.28776 -7.28692
No valid next view.
SfM reconstruction finished.
`
I use the orb feature and bf match, after I normalized keypoint positions, and saved in `prebundle.sfm`, still that problem, most feature tracks are rejected by `sfmrecon`, Is there some are reasons you know the difference between opencv feature extract and matching?
Is that the matching format I wrote wrong?
Thanks!

**Comment by jun1217** [comment]
If I want use my own features and matching result, Is there any good ways handle with mve?
I found the descriptors in mve have be sorted, Does that reasons?

**Comment by simonfuhrmann** [comment]
If you want your own features an matching result, writing the `prebundle.sfm` file is the way to go. I don't know if the descriptors have to be sorted... where do you get that impression from?
I would recommend you add some debugging statements to the code I mentioned [1] and see exactly what numbers are written. That might give you an idea what you are missing.

[1] https://github.com/simonfuhrmann/mve/blob/master/libs/sfm/bundler_common.cc#L57
