### ISSUE TITLE
how to use the initial pair option

### ISSUE THREAD

**Issue by vholod** [simonfuhrmann/mve#465]
Hi,

Thanks for this great work.
I couldn't find how to use the initial pair optinion in the SFM part.
Is there an option to provied many initial pairs to the sfm?How to do that?

Thanks,

**Comment by simonfuhrmann** [comment]
You can either let `sfmrecon` figure out the initial pair itself (the default), or use the `--initial-pair` option and provide the two views, e.g., `sfmrecon --initial-pair=0,1 <scenedir>`.
