### ISSUE TITLE
How to use UMVE in detail？

### ISSUE THREAD

**Issue by zhh110034** [simonfuhrmann/mve#470]
This project is so wonderful！I successfully ran the MVE project on OS X. But there was a problem when trying to use UMVE on Windows.
I successfully imported the images, But I don't know what to do next.....
Can you tell me some steps about using UMVE?
thanks.

**Comment by simonfuhrmann** [comment]
Check out the users guide in the Wiki here on GitHub. Basically, you run the pipeline using command line applications as described in the users guide. UMVE is mainly useful to inspect your scene, the SfM points, cameras, allows you to triangulate depth maps, etc.
