### ISSUE TITLE
"Invalid master view" error during dmrecon on Middlebury dataset

### ISSUE THREAD

**Issue by nsn88** [simonfuhrmann/mve#480]
I created  a scene of dinoRing (Middlebury dataset) as described [here](https://github.com/simonfuhrmann/mve/wiki/Middlebury-Datasets).

Then ran `featurerecon scene` and got [synth_0.out](https://gist.github.com/nsn88/b502b488ab48c2d2c38aafcd0ceea41f)

> MVE Feature Reconstruction (built on Jun 10 2019, 16:18:19)
> Initializing scene with 48 views...
> Initialized 48 views (max ID is 47), took 125ms.
> Loading pairwise matching from file...
> Computing feature tracks...
> Propagating track IDs...
> Removing tracks with conflicts... deleted 58 tracks.
> Colorizing tracks...
> Created a total of 2347 tracks.
> Writing bundle (48 cameras, 2288 features): scene/synth_0.out...

Then running `dmrecon scene` throws an error **Invalid master view** for all 48 cameras.

> MVE Depth Map Reconstruction (built on Jun 10 2019, 16:18:14)
> Initializing scene with 48 views...
> Initialized 48 views (max ID is 47), took 8ms.
> Reading Photosynther file (48 cameras, 2288 features)...
> Reconstructing all views...
> Invalid master viewInvalid master view
> Invalid master view
> Invalid master view
> Invalid master view
> Invalid master viewInvalid master view
> 
> 
> Invalid master viewInvalid master view
> 
> Invalid master viewInvalid master view
> 
> Invalid master viewInvalid master view
> 
> Invalid master view
> Invalid master viewInvalid master view
> Invalid master view
> Invalid master view
> 
> Invalid master viewInvalid master view
> 
> Invalid master viewInvalid master viewInvalid master view
> 
> Invalid master view
> Invalid master viewInvalid master view
> 
> 
> Invalid master viewInvalid master viewInvalid master view
> 
> 
> Invalid master view
> Invalid master view
> Invalid master viewInvalid master view
> Invalid master view
> Invalid master view
> 
> Invalid master viewInvalid master viewInvalid master view
> Invalid master view
> 
> 
> Invalid master viewInvalid master view
> Invalid master view
> 
> Invalid master viewInvalid master view
> 
> Invalid master viewInvalid master view
> 
> Invalid master view
> Invalid master view
> Reconstruction took 9ms.
> Saving views back to disc...
> Saving views to MVE files... done.

**Comment by simonfuhrmann** [comment]
What's the command line you used? It's probably because the image embedding is called differently?
Try: `dmrecon --image=original SCENE`.

**Comment by nsn88** [comment]
That worked, thanks!

Previously, I was using `dmrecon -s2 scene` as mentioned in the [MVE Users Guide](https://github.com/simonfuhrmann/mve/wiki/MVE-Users-Guide).

**Comment by simonfuhrmann** [comment]
Yea, `dmrecon` looks for the `undistorted` embedding. For Middlebury datasets, all images are already undistored, and if imported as `original`, they can be used as is. You just need to tell `dmrecon`.
