### ISSUE TITLE
unresolved external symbol memset refernenced in function glewContextInit

### ISSUE THREAD

**Issue by xuleidawang** [simonfuhrmann/mve#490]
Following the guide for building on Windows. 
Cannot build the 3rd party lib glew. And got this error. 
Using Visual Studio 2019.

**Comment by andre-schulz** [comment]
Hi @xuleidawang,
this seems to be a known issue. See nigels-com/glew#238. As a workaround you could install VS2017 or VS2015 which are both available as Community Editions or modify the 3rdparty CMakeLists.txt to use the snapshot posted in https://github.com/nigels-com/glew/issues/238#issuecomment-543485154 which seems to work with VS2019.

Cheers,
Andre

**Comment by xuleidawang** [comment]
Hi @andre-schulz ,
Thanks for you timely reply. I solved the problem by replace the glew download url in CMakeLists.txt with the new snapshot https://sourceforge.net/projects/glew/files/glew/snapshots/glew-20190928.tgz/download. 

Cheers,
Lei
