### ISSUE TITLE
How to view the appearance of the reconstructed 3D Model(.ply format)?

### ISSUE THREAD

**Issue by CriusT** [simonfuhrmann/mve#495]
Hi. I have reconstructed a scene successfully. Now I have a pset-L2.ply and a surface-L2-clean.ply. I want to know how I can view the whole appearance of the 3D model with its surface. Is there any 3D viewer software or converter that is recommended? Thanks a lot!

**Comment by simonfuhrmann** [comment]
PLY files are very common. Use Meshlab, or UMVE (shipped with MVE).

**Comment by CriusT** [comment]
OK. Thanks a lot.
