### ISSUE TITLE
Question about the sfm process

### ISSUE THREAD

**Issue by Alexsupernova** [simonfuhrmann/mve#496]
Hi, I'm a new comer in 3d-reconstruction.
Doing incremental sfm needs an init pair, and a photo chosen as the first viewport. So I think the coordinate of the photo should be set as the world coordinate, which means the rotation matrix should be [1,0,0;0,1,0;0,0,1] and translation should be [0,0,0]. However, I find that no meta.ini of photos can match the description. Do you know why?
Thanks a lot!

**Comment by simonfuhrmann** [comment]
Immediately after reconstructing the initial pair that would be true. There are two reasons why this is not the case in practice. First, every time bundle adjustment is executed it changes the extrinsics of every camera and the position of every point. Second, the scene is usually normalized from time to time for numerical accuracy.
