### ISSUE TITLE
incorporating ChArucoboard to get the extrinsic params 

### ISSUE THREAD

**Issue by hihihowru** [simonfuhrmann/mve#497]
Hello,

I am working on reconstructing a 3D object with the object being placed on a ChArucoBoard(like a chessboard with fiducial marker on the white space.) see [https://docs.opencv.org/3.4/df/d4a/tutorial_charuco_detection.html](ChArucoboard) or placed on a chessboard, and taking multiple images of the object from different angles. As the MVE pipeline suggested, SfM is used to  estimate extrinsic parameters, and is usually dealt with the case where camera is not calibrated.  
How can I take advantages of the known extrinsic params in sfm algorithm? or simply can I skip the sfm algorithm and continue on the next algorithmic steps (MVS) if that is possible?

**Comment by simonfuhrmann** [comment]
Yes, you can skip SfM if you have extrinsics and a reasonable focal length. Put your parameters in meta.ini for each view, then run the featurerecon tool to compute SfM features without actually running SfM. Then proceeded with dmrecon or smvs.

**Comment by hihihowru** [comment]
Thank you so much for your reply @simonfuhrmann 

How do you import a set of txt files for each of the image in which each of the txt file contains intrinsic and extrinsic params of the camera besides directly copy and paste the [camera] information (focal length, pixel_aspect .etc)
or is there any suggestions on auto-generating those meta.ini file with known camera params?

**Comment by simonfuhrmann** [comment]
That's what `makescene` is for, but if your input format is not supported you're probably best served by using makescene on the images only and writing a script that does the rest of the work for you in an automated fashion.
