### ISSUE TITLE
How to get MVE build for iOS

### ISSUE THREAD

**Issue by VerdaMunir** [simonfuhrmann/mve#498]
Hi everyone.
I am trying to build MVE for iOS. Any help or suggestions or links to articles on how it can be done ? Thank you.

**Comment by simonfuhrmann** [comment]
Please see here.
https://github.com/simonfuhrmann/mve/wiki/Build-Instructions-for-OS-X

It may be a little outdated, but the general approach is to install Xcode, the dependencies, then give it a shot.

**Comment by VerdaMunir** [comment]
Hi,
Thank you for responding.  I have followed the link and it builds mve but it doesn't make an Xcode project. While building OpenMVG, there was a -G flag with which we could tell which build generator to use but it seems that with "make" we cannot do that. we can only do it using cmake. 

If we could get the Xcode project then we can try building it from within Xcode for iOS.

**Comment by simonfuhrmann** [comment]
Generating an Xcode project is not supported, as we don't use cmake.

**Comment by andre-schulz** [comment]
Hi @VerdaMunir,
you can try my CMake branch (https://github.com/andre-schulz/mve/tree/cmake) but it's mainly for compiling on Windows so you might have to make some modifications to the build system.

**Comment by VerdaMunir** [comment]
Hi @andre-schulz 
Thank you, I will check it out right away.
