### ISSUE TITLE
Avoid white fringes in background

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [simonfuhrmann/mve#502]
My current workflow is

```
makescene -k -o -i
sfmrecon 
dmrecon -s3  
scene2pset -F3  
fssrecon
meshclean -t10 -c10000
texrecon ::undistorted
```

which makes some models have white fringes(from a mainly white background).

How to avoid that?

**Comment by simonfuhrmann** [comment]
It's hard to avoid. In stereo, the edges of objects match pretty well as the boundary between object interior and exterior provides a good matching contrast. The extra boundary is roughly half the MVS matching window size.

You can try to peel away triangles of depth maps boundaries. There's already a function for that. Call this function:

https://github.com/simonfuhrmann/mve/blob/30e5ba73556ec6d9d23df2147e7626c31bdc84a7/libs/mve/depthmap.h#L157

Right before this line:

https://github.com/simonfuhrmann/mve/blob/30e5ba73556ec6d9d23df2147e7626c31bdc84a7/apps/scene2pset/scene2pset.cc#L328

And then rerun scene2pset. Note this may also give you larger holes and will probably result in a sparser reconstruction.

**Comment by simonfuhrmann** [comment]
Feel free to reopen if you have more questions.
