### ISSUE TITLE
how to generate a PLY file after sfmrecon?

### ISSUE THREAD

**Issue by Davis-dev** [simonfuhrmann/mve#504]
Hi there,
I'm new to **mve**. I would like to visualize the result of `sfmrecon` in meshlab, but I don't konw how to generate a PLY file after it. 
Thanks in advance for any ideas.

**Comment by simonfuhrmann** [comment]
Your best bet is to use UMVE. It will allow you to triangulate depth maps, put them in 3D space, view them along with SfM points, and will also allow you to export them to PLY files so you can open them in Meshlab.

Then there is also `scene2pset` which will allow you to export all (or just certain) views into a point cloud to a PLY file which you can view in Meshlab. But that doesn't produce a triangulation (in fact internally drops the triangulation to convert it to a point cloud).

Further, `dmrecon` has an option `--writeply` and `--plydest` which outputs PLY files for the depth maps it generates, but you'd have to rerun `dmrecon`.

Again, use try to use UMVE and report back if this doesn't do what you want.

**Comment by Davis-dev** [comment]
@simonfuhrmann thanks.
After going through the pipeline, I could see the scene in the `Scene inspect` window by UMVE. it shows the SfM points, right?
But when I use the button `Export Scanalize PLY` to export the PLY file, the result is the PLY file of picture showing in the `View inspect` window. what I want is the SfM point PLY file.

**Comment by simonfuhrmann** [comment]
In scene inspect, there should be a panel somewhere that says "DM Triangulate", which generates a mesh for the depth map. You can then export that. Let me know if you are stuck.

**Comment by Davis-dev** [comment]
Thanks
But I don't know how to use it. When I click the triangulate, it shows the error `"no embedding selected"`. When I choose a picture in the left scene panel and click the triangulate again,it shows error` "Depthmap not available: <none>"`

**Comment by Davis-dev** [comment]
I found someone use `bundle2pset` to generate a PLY file #267 , so I use the follow command after command `sfmrecon`:
`bundle2pset  /path/to/synth_0.out /path/to/output_PLY_files/sparse.ply`
I visualize it in Meshlab, but it's a bit different from what's shown in UMVE. 
In UMVE, it seems that the sparse points are more clearer and the number of points are more than that in Meshlab. I'm not sure if it's an illusion.

**Comment by simonfuhrmann** [comment]
Select a view from the left panel. Then select the depth map you want to triangulate and the corresponding color image in the "DM Triangulate" panel. I'm sure you can figure out how it works.

I'm not aware of a reason why the exported sparse points should be different from the ones shown in UMVE.

**Comment by Davis-dev** [comment]
I can't select anything in the depthmap for the first time. Then I close UMVE and reopen it, it works. I don't know why.
No matter I choose `export reconstruction...` in the `scene` panel on the left or `export scanalize PLY` in the view scene, the results are the same. The difference is that the former exports the PLY and xf files of the whole pictures, and the latter only exports the selected picture's.

The exported PLY file is the depth map, right?
UMVE only shows SfM points and it can not be exported in UMVE, right? 

This is the result of `scene2pset`, I use the dataset `der_hass`
[sparse.zip](https://github.com/simonfuhrmann/mve/files/4352481/sparse.zip)

**Comment by simonfuhrmann** [comment]
Triangulating a depth map (as described above) results in a new mesh in the bottom right list in "Scene Inspect". If you right click the mesh, it can be saved as a PLY file.

**Comment by Davis-dev** [comment]
Yes, it generates a new mesh. Thank you for your kind help.
