### ISSUE TITLE
how to get rotation matrix 

### ISSUE THREAD

**Issue by Shen001** [simonfuhrmann/mve#506]
I read your code and cant very understand "Camera rotation which transforms from world to cam.",i mean  how to get this matrix. My Extrinsic parameters and Intrinsic parameters come from airplane,does it any different with camera parameters?

**Comment by simonfuhrmann** [comment]
I'm not sure I understand the question. The extrinsic matrix is stored in the meta.ini files in the view directories.

**Comment by Shen001** [comment]
> I'm not sure I understand the question. The extrinsic matrix is stored in the meta.ini files in the view directories.

thanks for your reply! the problem is how to get these files,by makescene.exe? Actually,i am not very clear about parameter "rotation" in the meta.ini file,i want to compute it myself by some parameters~

**Comment by simonfuhrmann** [comment]
No, `makescene` only imports your images. You need a SfM reconstruction, with the `sfmrecon` tool. Take a look at the users guide here:
https://github.com/simonfuhrmann/mve/wiki/MVE-Users-Guide

**Comment by Shen001** [comment]
well，thanks a lot. i will look more about this seriously.
