### ISSUE TITLE
Blender Addon to import MVE reconstructions

### ISSUE THREAD

**Issue by SBCV** [simonfuhrmann/mve#512]
[This Blender addon](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer) supports now MVE reconstructions. With that it is possible to import points and cameras including image planes. The following image shows an example of the imported results.
![import_result](https://user-images.githubusercontent.com/19491335/89572676-be870580-d829-11ea-8e99-46130fb94cdf.jpg)
It is also possible to automatically compute an animation of the camera. 
![camera_animation](https://user-images.githubusercontent.com/19491335/89573050-4bca5a00-d82a-11ea-9455-543a8e9b2b0f.gif)
I posted this issue as future reference - feel free to close it.

**Comment by simonfuhrmann** [comment]
Wow, that is really nice. I think I want to add this to the wiki.

**Comment by simonfuhrmann** [comment]
I added this to the bottom of the Users guide. https://github.com/simonfuhrmann/mve/wiki/MVE-Users-Guide
