### ISSUE TITLE
How to import COLMAP's SfM result into MVE?

### ISSUE THREAD

**Issue by Yzhbuaa** [simonfuhrmann/mve#520]
Hello, I notice that, recently, MVE was updated and could import COLMAP's SfM result directly. But I don't know how to use this functionality？ I tried `makescene ` on COLMAP's SfM result folder which contained cameras.bin, images.bin and points3D.bin. But I got an error:

> error: No bundle found.

Thank you!

**Comment by Yzhbuaa** [comment]
I've read the code, now I know how to import COLMAP's SfM result into MVE. Thanks for the great work!

**Comment by Yes-Jumby** [comment]
would you like to show me the command by which you using colmap?

I makescene success,then failed!:(
