### ISSUE TITLE
A bug in Sift::create_octaves?

### ISSUE THREAD

**Issue by stanleylijilin** [simonfuhrmann/mve#522]
It seems the comment is right, but the code is not.The third parameter of add_octave is not updated.

```
/*
 * Create new octave from 'img', then subsample octave image where
 * sigma is doubled to get a new base image for the next octave.
 */
float img_sigma = this->options.inherent_blur_sigma;
for (int i = std::max(0, this->options.min_octave);
    i <= this->options.max_octave; ++i)
{
  //std::cout << "Creating octave " << i << "..." << std::endl;
  this->add_octave(img, img_sigma, this->options.base_blur_sigma);
  img = mve::image::rescale_half_size_gaussian(img);
  img_sigma = this->options.base_blur_sigma;
}
```

**Comment by simonfuhrmann** [comment]
The third parameter describes the target blur of the first image in the octave, and is a constant (option). So it is correct that this parameter doesn't change. What I find a little more odd, however, is that `img_sigma` is set to `this->options.base_blur_sigma` in the loop. I'm not quite sure why, but it's probably because the image is not just resampled (which would cut the sigma in half) but resized.

**Comment by stanleylijilin** [comment]
Yes, I am also a little confused about the second parameter.
In my opinion:
The first octave sigma is:       sigma,          sigma * k,            sigma * k^2...
The second octave sigma is: sigma * k^n, sigma * k^(n+1), sigma * k ^(n+2)...
where k is 2^(1/n),so the target blur of first layer of the second octave is sigma * 2.
As you say the image is resized with a Gaussian, may be it is more reasonable to use rescale_half_size_subsample here.

**Comment by simonfuhrmann** [comment]
Maybe, maybe not. The problem with half-sizing by subsampling is that only one of the four pixels (in a 2x2 pixel block) can be chosen, which leads to a shift of the image contents in every iteration. That shift has to be accounted for when computing features on lower resolutions. It would be a decent effort/complication to consistently do that.

Further, after subsampling, the sigma is halved, and additional Gaussian blur has to be applied before computing the next octave with `add_octave()`, i.e., the second parameter to `add_octave()` has to be smaller than the third parameter. Rescaling using a Gaussian avoid the shift, and applies a good amount of blur during resizing, so I think the code here is actually correct.
