### ISSUE TITLE
missing seeFeature check GlobalViewSelection::benefitFromView(std::size_t i)?

### ISSUE THREAD

**Issue by xubury** [simonfuhrmann/mve#523]
As https://github.com/simonfuhrmann/mve/issues/360 metion, there's no feature see check while comment says: Parallax with other selected **views that see the same feature**
https://github.com/simonfuhrmann/mve/blob/aa831a824d5a73cfd00da41d8eda140f9e3235d9/libs/dmrecon/global_view_selection.cc#L88-L96
I feel like  following lines need to be added
```
if (!views[*citV]->seesFeature(nFeatIDs[k])) {
    continue;
}
```

**Comment by simonfuhrmann** [comment]
PR merged. I have not written the MVS code myself, so I hope this code is correct, and you have tested it :)
