### ISSUE TITLE
[Question] invalid track counting.

### ISSUE THREAD

**Issue by CaptainEven** [simonfuhrmann/mve#528]
Thanks for your excellent work! I have a question when i read the source code in the sfm/bundller_tracks.cc line 161-164:
```
  if (tracks->at(i).features.empty())
        {
            delete_tracks[i] = true;
            continue;
        }
```
why not add one for num_invalid_tracks here?

**Comment by simonfuhrmann** [comment]
I guess this case doesn't happen, but it should be there..
