### ISSUE TITLE
How to visualize the point cloud of SFM procedure?

### ISSUE THREAD

**Issue by CaptainEven** [simonfuhrmann/mve#529]
How to visualize the output(sparse point cloud) of SFM reconstruction?

**Comment by simonfuhrmann** [comment]
You can convert the bundle to a PLY file with the `bundle2pset` tool and inspect with any tool that can read PLY files:

```
Usage: ./bundle2pset [ OPTIONS ] INPUT_BUNDLE OUTPUT_PLY
Available options: 
  -s, --spheres=ARG     Generates a sphere for every point (radius ARG) [0.0]
```

Or, more conveniently, you can use the UMVE app.

**Comment by CaptainEven** [comment]
@simonfuhrmann Thank you for your quick and  helpful reply!
