### ISSUE TITLE
MVE for iOS

### ISSUE THREAD

**Issue by VerdaMunir** [simonfuhrmann/mve#532]
Hi Simon,

I am a PhD student in Scotland.
And have been working towards photogrammetry pipeline for iOS.
I want to use MVE for the process. 
I want to ask you if there is a way to use MVE for iOS? Are the libraries iOS compatible? Or can it be made compatible?
Your time is much appreciated.

Regards

**Comment by simonfuhrmann** [comment]
There are some parts of the libraries which are OS dependent, e.g. for file system operations, in `lib/util`. But most of the code is OS independent. So there is certainly a way, and it can be done. But I'm not sure if it has been attempted yet.
