### ISSUE TITLE
MVE for macbook pro M1

### ISSUE THREAD

**Issue by MatrixA** [simonfuhrmann/mve#533]
Hi Simon，I try to compile this project in my macbook pro(M1), but got some errors bellow. How can I solve this problem?
![image](https://user-images.githubusercontent.com/33066250/105707111-636adb80-5f4d-11eb-845d-263c40c5cfdd.png)

**Comment by simonfuhrmann** [comment]
Interesting. The M1 should be little endian, but the macros are not recognized on an M1.

**Comment by simonfuhrmann** [comment]
Can you try adding ARM to [/libs/util/system.h in line 149](https://github.com/simonfuhrmann/mve/blob/master/libs/util/system.h#L149):

```
#   elif defined(__i386__) || defined(__x86_64__) || defined(__aarch64__)
```

**Comment by MatrixA** [comment]
I did as you say and solve this problem successfully, thank you simon!
