### ISSUE TITLE
Makescene error

### ISSUE THREAD

**Issue by Dhananjay777** [simonfuhrmann/mve#536]
Hi,

I am trying to run ,,mve'' on WSL 2. When I execute the 'makescene' command  the following error shows up
 ''makescene: command not found ''. Please advise on this

Thanks
Dhananjay

**Comment by simonfuhrmann** [comment]
Did you also build the apps? In that case, you'd probably have to run something like `./apps/makescene/makescene`.

**Comment by Dhananjay777** [comment]
Thanks a lot that did it. Additionally I am wanting to run MVE on a synthetic dataset (blender). So for the Sfm to work I guess the focal length has to be entered into meta.ini for each image ? Is that it?

**Comment by simonfuhrmann** [comment]
If you're running on a synthetic dataset, do you need SfM at all? You can just import calibrated images directly.

**Comment by Dhananjay777** [comment]
Yes, ok so I am basically looking for the 3D dense point cloud. Then maybe directly proceed from the Multi-View Stereo step onwards.
The synthetic camera images are of size 400x400 and the camera setting used has a 39.6 deg fov. This yields a horizontal and vertical focal length of 555. So could please clarify how I could import this data for that step. Thanks

**Comment by simonfuhrmann** [comment]
Look at the directory/file structure of an existing scene that already ran sfm. You have to set the principal point to (0.5, 0.5) and the focal length to 555/400 = 1.3875 in the meta.ini file. Then you have to generate feature for MVS to work, there is a tool for that called featurerecon. After that proceed with MVS as outlined in the users guide. Also consult the users guide for details on the file formats.
