### ISSUE TITLE
Question about camera frame calculation in p3p kneip

### ISSUE THREAD

**Issue by keineahnung2345** [simonfuhrmann/mve#539]
In the following code snippet, it first tries to find the matrix T:
https://github.com/simonfuhrmann/mve/blob/26268035143c17c8b7b63eefb59b0eb351b1e424/libs/sfm/pose_p3p.cc#L96-L106
And if the T is invalid, it needs to find a new T:
https://github.com/simonfuhrmann/mve/blob/26268035143c17c8b7b63eefb59b0eb351b1e424/libs/sfm/pose_p3p.cc#L108-L121
In the case that the first T is invalid, it seems `f3` is multiplied by the old invalid T and then the new valid T.
Could you check if it is a bug? If it's a bug, I would like to send a PR to fix it.

**Comment by simonfuhrmann** [comment]
I don't see the bug. Before T is "reused" in the second code block, the new values of e1, e2 and e3 are copied into T. Does that make sense?

**Comment by keineahnung2345** [comment]
Thanks for your timely response.

> I don't see the bug. Before T is "reused" in the second code block, the new values of e1, e2 and e3 are copied into T. Does that make sense?

I think the `T` part is ok, what I concern is the correctness of `f3`:

In line 105, `f3` is changed, and in line 120, it operates on the changed `f3` to get the final `f3`. What I expect is that line 120 should operate on the original `f3`(the `f3` before line 105) to get the final `f3`.

**Comment by simonfuhrmann** [comment]
Maybe you're right. But maybe this is intention, as f3 is not "invalid", just has the wrong orientation? I honestly can't remember how that algorithm works. Would you be able to write a unit test that covers that code branch?

**Comment by keineahnung2345** [comment]
Actually there is already one: https://github.com/simonfuhrmann/mve/blob/master/tests/sfm/gtest_pose_p3p.cc, maybe we should add more test data?

**Comment by simonfuhrmann** [comment]
Well my point is, we need a test that confirms that there is a bug (i.e., a failing test). Then we fix it and then the test should pass :)

**Comment by keineahnung2345** [comment]
Yes, I mean adding more testcases so the test will be robust enough to make the original code fail.

**Comment by keineahnung2345** [comment]
I've generated 1000000 random `pose` and `p1`, `p2`, `p3` for testing. The results are as expected, please check them at https://travis-ci.org/github/keineahnung2345/mve/builds/760543599 and https://travis-ci.org/github/keineahnung2345/mve/builds/760544348

**Comment by simonfuhrmann** [comment]
Can you please patch this diff and tell me if this solves the problem?

```
diff --git a/libs/sfm/pose_p3p.cc b/libs/sfm/pose_p3p.cc
index aaf6366..ee19bd0 100644
--- a/libs/sfm/pose_p3p.cc
+++ b/libs/sfm/pose_p3p.cc
@@ -102,11 +102,10 @@ pose_p3p_kneip (
         std::copy(e1.begin(), e1.end(), T.begin() + 0);
         std::copy(e2.begin(), e2.end(), T.begin() + 3);
         std::copy(e3.begin(), e3.end(), T.begin() + 6);
-        f3 = T * f3;
     }
 
-    /* Change camera frame and point order if f3[2] > 0. */
-    if (f3[2] > 0.0)
+    /* Change camera frame and point order if new z > 0. */
+    if (T.row(2).dot(f3) > 0.0)
     {
         std::swap(p1, p2);
         std::swap(f1, f2);
@@ -117,8 +116,8 @@ pose_p3p_kneip (
         std::copy(e1.begin(), e1.end(), T.begin() + 0);
         std::copy(e2.begin(), e2.end(), T.begin() + 3);
         std::copy(e3.begin(), e3.end(), T.begin() + 6);
-        f3 = T * f3;
     }
+    f3 = T * f3;
 
     /* Create world frame. */
     math::Matrix3d N;
```

**Comment by keineahnung2345** [comment]
Oh, I didn't know that we could write something like `T.row(2).dot(f3)`. This coding style is much better!

The build result for original code: https://travis-ci.org/github/keineahnung2345/mve/builds/760670188 
The build result for patched code: https://travis-ci.org/github/keineahnung2345/mve/builds/760670370

**Comment by simonfuhrmann** [comment]
Sorry for the delay. I committed the fix.

Regarding the test code, the approach to randomize test cases is not ideal, as it is not reproducible. For example, a change in the randomizer seed, or the randomizer algorithm, could suddenly cause test cases to fail. It is better to construct a single test case with explicit numbers to test this specific instance. (It could very well be an example obtained through random numbers, but explicitly hard-coded.)

Please feel free to provide a PR for such a test case.

**Comment by simonfuhrmann** [comment]
Closing for now.
