### ISSUE TITLE
macOS build instruction update

### ISSUE THREAD

**Issue by patzm** [simonfuhrmann/mve#541]
hi there,
I updated the macOS build instructions: https://github.com/simonfuhrmann/mve/wiki/Build-Instructions-for-OS-X/_compare/96a42db45f946bd71243cf9faa3af7b82d49960d...13d3e3bd4c80e745ee1af966986c9ff1a928e129
I am filing an issue to let you know and ask if that was ok. Interestingly, the Wiki has no write protection 😆. Great spirit though 🚀. Please close this issue if the changes are fine.

**Comment by simonfuhrmann** [comment]
Looks good to me. Thanks.
