### ISSUE TITLE
How to construct a valid projection matrix from the synth_0.out file

### ISSUE THREAD

**Issue by AnaRhisT94** [simonfuhrmann/mve#542]
Hi,
I used the sfmrecon command and got a synth_0.out file,
I'm trying to figure out how to construct a valid projection matrix from the synth.out file,
I want to render the reconstructed model on a 2d plane.

I guess the only issue here is the focal length, it's normalized and I need to denormalize it. Any ideas how it's done? Should I just multiply it by width/length?

**Comment by simonfuhrmann** [comment]
If focal length is you only issue, you have to multiply it with max(width, height).
