### ISSUE TITLE
bundle2pset outputs a `.ply` file without any vertices

### ISSUE THREAD

**Issue by AnaRhisT94** [simonfuhrmann/mve#543]
Hi,

I've used `makescene -i IMAGE_DIR SCENE_DIR` and `sfmrecon SCENE_DIR`,

I'm trying to create a `.ply` object and visualize it in MeshLab, after using the command `bundle2pset -F2` I'm getting a `.ply` format file that weights 300 bytes and I don't see anything in MeshLab (# of vertices is zero)

Output:
![image](https://user-images.githubusercontent.com/33227900/112765304-4453fd00-9015-11eb-8093-7dc9464d0a7d.png)

Note: When I used smvs, it worked well https://github.com/flanggut/smvs , it says there that: This project is intended as an alternative multi-view stereo step and replaces the dmrecon and scene2pset applications with the smvsrecon

**Comment by simonfuhrmann** [comment]
Did `sfmrecon` succeed in reconstructing the scene? Also, `bundle2pset` does not accept a `-F2` argument. Did you use `scene2pset` instead?

**Comment by AnaRhisT94** [comment]
> Did `sfmrecon` succeed in reconstructing the scene? Also, `bundle2pset` does not accept a `-F2` argument. Did you use `scene2pset` instead?

Yup, I ran again `sfmrecon` and then tried both `scene2pset` with `F2` and `bundle2pset` too, it doesn't work.

`scene2pset` outputs an empty `.ply` file and `bundlet2pset` outputs this error:
![image](https://user-images.githubusercontent.com/33227900/112797044-80b64600-9073-11eb-85f4-f420ccdadfcc.png)

**Comment by simonfuhrmann** [comment]
Can you please provide the console output of sfmrecon?

**Comment by AnaRhisT94** [comment]
> Can you please provide the console output of sfmrecon?

It does work with dmrecon w/o any problems, smvs also does this process.
When doing w/ dmrecon and `bundlet2pset` it reconstructs a model that doesn't look good, not the results of smvs are really good.
I'm not sure why sfmrecon doesn't work though.
the log file:

[output_sfm.txt](https://github.com/simonfuhrmann/mve/files/6227573/output_sfm.txt)

**Comment by simonfuhrmann** [comment]
Let's clarify a few things here.

* `bundle2pset` outputs the _sparse_ point cloud from SfM, and depending on what your expectations are, that may "not look good". But as I said, it's sparse, not dense.
* The workflow for getting these _sparse_ point clouds is `makescene` -> `sfmrecon` -> `bundle2pset`.
* `scene2pset` outputs a _dense_ reconstruction which you can either get through `dmrecon` or `smvs`.
* The workflow for getting these _dense_ reconstructions is `makescene` -> `sfmrecon` -> `dmrecon` OR `smvs` -> `scene2pset`.

Having said that, what exactly is your problem now?

**Comment by simonfuhrmann** [comment]
Please reopen if there are remaining questions.
