### ISSUE TITLE
Reducing the number of points in the point cloud

### ISSUE THREAD

**Issue by BarmaJley** [simonfuhrmann/mve#547]
Hello!
I'm trying to get a point cloud from my datasets, usually 20-50 images. The fact is that I get very dense point clouds (3,000,000 - 7,000,000 points). I would like to receive a point cloud of about 60,000-100,000 points. How can this be done?
P.S. I tried to reduce the point cloud using the PointCloude library, but then for some reason I can't use the reduced point cloud in further operations.

**Comment by simonfuhrmann** [comment]
The easiest solution is perhaps to change the arguments to dmrecon and reconstruct the depth maps at a lower scale. Try -s3.
