### ISSUE TITLE
Speed problem

### ISSUE THREAD

**Issue by catmasteryip** [simonfuhrmann/mve#549]
I used this pipeline to generate a point cloud from a set of 11 .jpg images, each have the resolution of 230x230 and dimension of 2832x2128. The result is satisfactory yet the time taken was quite long (several minutes). What are the suggestions to raise the speed? Does the command line tool have the option to run on multi-thread?

**Comment by simonfuhrmann** [comment]
I'm not sure what the difference between "resolution" and "dimension" is. But "several minutes" doesn't sound too bad. This system is a "reference implementation" with little regard for efficiency. There is multi-threading in various places. I believe there is some OpenMP parallelization here and there but it isn't supported on clang.
