### ISSUE TITLE
dmrecon has no result[Global View Selection failed]

### ISSUE THREAD

**Issue by Yes-Jumby** [simonfuhrmann/mve#551]
**it seems to be that the data has no neighboring views.but i donnot know where is wrong**

**here is my pipe line:**
**step1**:using colmap to get pose etc
    mapper_args = [
        'colmap', 'mapper',
            '--database_path', os.path.join(basedir, 'database.db'),
            '--image_path', os.path.join(basedir, 'images'),
            '--output_path', os.path.join(basedir, 'sparse'), # --export_path changed to --output_path in colmap 3.6
            '--Mapper.num_threads', '16',
            '--Mapper.init_min_tri_angle', '4',
            '--Mapper.multiple_models', '0',
            '--Mapper.extract_colors', '1',
    ]
**step2**:using make scene to translate colmap to mve
.\makescene.exe D:\data\blend_mvs\bmvs_bear D:\data\blend_mvs\bmvs_bear\scene
**step3**:suing dmrecon ,but get no result:(
.\dmrecon.exe D:/data/blend_mvs/bmvs_clock/scene -s0

here is the log
MVE Depth Map Reconstruction (built on Dec 16 2021, 00:24:05)
Initializing scene with 143 views...
Initialized 143 views (max ID is 142), took 47ms.
Reading Photosynther file (143 cameras, 13355 features)...
Reconstructing all views...
scaled image size: 768 x 576
scaled image size: 768 x 576
scaled image size: 768 x 576
scaled image size: 768 x 576
scaled image size: 768 x 576
scaled image size: 768 x 576
scaled image size: 768 x 576
scaled image size: 768 x 576
scaled image size: 768 x 576
scaled image size: 768 x 576
scaled image size: 768 x 576
scaled image size: 768 x 576
scaled image size: 768 x 576
scaled image size: 768 x 576
scaled image size: 768 x 576
scaled image size: 768 x 576
Global View Selection failed
Global View Selection failedGlobal View Selection failed
Global View Selection failed
Global View Selection failed
scaled image size: 768 x 576
Global View Selection failed
Global View Selection failed
Global View Selection failed
Global View Selection failed
Global View Selection failed
Global View Selection failed
Global View Selection failed
Global View Selection failed
Global View Selection failed
Global View Selection failed
Global View Selection failed
Global View Selection failed
Global View Selection failed
Reconstruction took 3274ms.
Saving views back to disc...
Saving views to MVE files... done.

**Comment by Yes-Jumby** [comment]
here is my scene in umve:
![adf51faa5c075081c9abfc9743ca627](https://user-images.githubusercontent.com/51182133/146636874-4c160962-ca6f-4eb0-b221-5c594469007c.png)

here is the example data in umve:
![image](https://user-images.githubusercontent.com/51182133/146636915-879aeda9-02ec-405a-9a33-08c18833cc70.png)


there is a big difference in the pic ,where indicates camera

**Comment by Yes-Jumby** [comment]
maybe focal_length is the reason;(

**Comment by simonfuhrmann** [comment]
Yes, focal length seems to be the issue. The colmap one seems to be in pixels, wheres MVE expects a unitless, normalized one. Can you try normalizing the focal length? Divide it by max(with, height) of the original image size.

**Comment by Yes-Jumby** [comment]
> Yes, focal length seems to be the issue. The colmap one seems to be in pixels, wheres MVE expects a unitless, normalized one. Can you try normalizing the focal length? Divide it by max(with, height) of the original image size.

sure，i will try to do it in source code.

**Comment by Yes-Jumby** [comment]
> Yes, focal length seems to be the issue. The colmap one seems to be in pixels, wheres MVE expects a unitless, normalized one. Can you try normalizing the focal length? Divide it by max(with, height) of the original image size.

solve it ,thanks:)
