### ISSUE TITLE
distortion coefficient

### ISSUE THREAD

**Issue by lihui1998** [simonfuhrmann/mve#552]
Thank you for your work. I want to use .cam files, pictures and mesh files for texture reconstruction, but I cannot get the correct results. Whether the distortion coefficient has a great influence on the reconstruction result, because my default distortion coefficient is zero. Below is my reconstruction resul
![textured_material0000_map_Kd](https://user-images.githubusercontent.com/51204863/147177256-4d1b21cf-9db3-44ab-b5f3-82f7d86032bc.png)

**Comment by lihui1998** [comment]
This is my mesh file：
![image](https://user-images.githubusercontent.com/51204863/147177512-5c7e3b13-e899-4f2d-abc5-c8ee0e326f7a.png)

**Comment by simonfuhrmann** [comment]
What is the question?
