### ISSUE TITLE
Crash with large image

### ISSUE THREAD

**Issue by oleg-alexandrov** [simonfuhrmann/mve#553]
Dear authors of mve, thank you for the nice lib. I use it in my work and it is very helpful.

I managed to make it crash here: https://github.com/simonfuhrmann/mve/blob/master/libs/mve/image_base.h#L429

The problem seems to be that even on a 64-bit system, the 'int' is 32 bit. So, it can overflow. In my case I had an image of dimensions 158704 x 4096, with 4 channels. Their product is bigger than what that integer can hold. Granted, that is a big image.

The solution seems to me to use 'long' or 'size_t' instead of 'int' for image dimensions, or at least when it comes to that line, it should be replaced with:

this->data.resize(long(width) * long(height) * long(chans));

Some other logic in that file which has to do with buffer size needs to be changed as well.

**Comment by simonfuhrmann** [comment]
Congratulations. Yes, it seems doing what you suggested is a first good step, but no guarantees this is the only place that needs fixing... Let me get started with that fix first.

**Comment by oleg-alexandrov** [comment]
Thank you for the quick response. Here's the fix I put in my fork, if that may be of help:

https://github.com/oleg-alexandrov/mve/commit/cfde01c477b335c2564e3c9421e8a8615eb4ccc6

This is based off an older version of your repo, which I forked from https://github.com/nmoehrle/mve

This bug can bite also in your interpolation routines, since your images are stored in an array buffer, so to reach position (i, j) one has to do i * num_cols + num_rows. 
 
Lastly, I do appreciate the attention. While this may seem like an obscure thing, it would be triggered, by example, also by an image of size 40000 x 16000, which is not unreasonable if MVE is used in the context I used it, to create a texture for a cubic room, maybe 10 m x 10 m x 10 m, at a 1 mm resolution (approximately).

**Comment by simonfuhrmann** [comment]
I submitted 008841fa98b0e308f0b9434f51a8528409e739e8 to handle the cases in `image_base.h` but I am not convinced this is all that is needed. But please give this a try first.

I don't think it is necessary to change the dimensions (each of w, h, c) to a long, but the product should be properly handled. Here, I'm using `int64_t` as a remedy for now.

**Comment by simonfuhrmann** [comment]
The image utils are broken too. Trying to come up with a fix for those.

**Comment by simonfuhrmann** [comment]
More updates in 5ae0a4b6a55bf636e7a79d7d5a4e0dda13521607 and 177403ecb33b5327073f795daf15b488b5e44878

**Comment by simonfuhrmann** [comment]
Ugh, yea you are right. I fixed these in a new commit. However, I am indeed tempted to roll all the changes back and change all `int` to `int64` for the image class... probably a much cleaner change then this...

**Comment by simonfuhrmann** [comment]
Ok, I reverted the changes and pushed c0e2695a0474836278acaa21ddd694d88965b0ec. I hope this fixed most issues. Please let me know if that works for you. I am sure I missed some conversions from `int` to `int64_t`, let me know which ones are still problematic.

**Comment by oleg-alexandrov** [comment]
Dear Simon, thank you! I looked at the code, and it appears to be all good. Glad also some size_t were gone, it is easy to make mistakes with counters of unsigned type. 

BTW, there was a line which said:

std::size_t const MAX_ST = (std::size_t)-1;

Now it says: 

int64_t const MAX_ST = -1;

https://github.com/simonfuhrmann/mve/commit/c0e2695a0474836278acaa21ddd694d88965b0ec#diff-9172a0fd46142d0d91f3c3915a36c2972eb1656cd9cd7979b94e43028256d292R36

I think it is likely fine either way, as you want an unique value there which is not in the usual range, even though it is not a max anymore.

I appreciate all the hard work, I think it is well-justified. (Images which would overwhelm int32 also routinely show up in satellite images, those sensors are big nowadays.)

**Comment by simonfuhrmann** [comment]
You're welcome. Please let me know if you run into issues. Feel free to also close this issue.
