### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by jhaggle** [simonfuhrmann/mve#554]
These links are not working:

https://www.gcc.tu-darmstadt.de/home/proj/mve/

https://www.informatik.tu-darmstadt.de/gris/projects/floating-scale-surface-recon/

https://github.com/simonfuhrmann/mve/wiki/Multi-View-Stereo

**Comment by simonfuhrmann** [comment]
Thanks. It seems the tu-darmstadt.de site has been discontinued. I'll update the wiki and readme to reflect the changes.
