### ISSUE TITLE
Problema en la instalación

### ISSUE THREAD

**Issue by dectun** [simonfuhrmann/mve#556]
![Captura de Pantalla 2022-04-11 a las 15 05 55](https://user-images.githubusercontent.com/103385292/162745751-0696bdbd-26f8-4867-970e-34436b8c27b4.png)

He realizado el cambio en el archivo makefile.inc, cambiando el comando -march=native por el comando -mcpu=apple-m1. También probé poner el añadido en la linea 149 del archivo system.h, también sustituir `elif` por `else`. 

Estoy usando un macbook m1 16gb RAM.

Me sigue dando el error de; couldn`t determine host endianess!

**Comment by simonfuhrmann** [comment]
M1 is an arm processor, so you can try adding a check for `__arm__` to that logic. I don't know if M1 is LE or BE though.

**Comment by simonfuhrmann** [comment]
Install the libraries listed in the instructions:
https://github.com/simonfuhrmann/mve#building-mve-and-umve

**Comment by dectun** [comment]
i try to do this, but when a put "make -j8" get me an error; couldn´t determinate host endianes".
![Captura de Pantalla 2022-04-12 a las 1 54 44](https://user-images.githubusercontent.com/103385292/162851684-25c9378e-6e35-4c35-9194-5b6390dfc292.png)
