### ISSUE TITLE
Problema en el paso de build MVE and UMVE

### ISSUE THREAD

**Issue by dectun** [simonfuhrmann/mve#557]
https://github.com/simonfuhrmann/mve/wiki/Build-Instructions-for-OS-X

Ese  paso me da error continuamente. Primero con "error: Couldn't determine host endianess". Y ahora dice que el archivo "png.h" no existe. 
He instalado el resto de pasos bien hasta instalar el BREW y he descargado el clon de git también bien.

No sé si es que debo repetir algún paso. No entiendo el problema.
![Captura de Pantalla 2022-04-11 a las 19 02 18](https://user-images.githubusercontent.com/103385292/162841847-31e12374-4bff-4ccf-88d8-ef0468cbde28.png)

**Comment by simonfuhrmann** [comment]
Sorry mate, this is an English only support channel.

**Comment by dectun** [comment]
when i try to do the make MVE and UMVE. I get an error; "falta error: `png.h` file not found.


I did all steps. I installed homebrew, and libraries png, jpeg, ttif, ... like said this;
https://github.com/simonfuhrmann/mve/wiki/Build-Instructions-for-OS-X

I don`t undesrtand what is the problem.
![Captura de Pantalla 2022-04-12 a las 1 47 14](https://user-images.githubusercontent.com/103385292/162851065-a2bfdd0d-5c15-45cb-976e-701dd2b0606d.png)

**Comment by simonfuhrmann** [comment]
Answered in #558.
