### ISSUE TITLE
Problem in the build MVE and UMVE step

### ISSUE THREAD

**Issue by dectun** [simonfuhrmann/mve#558]
I can`t build MVE and UMVE in this;
(https://github.com/simonfuhrmann/mve/wiki/Build-Instructions-for-OS-X)

when I put this command; cd mve; make I get an error, like this. It don`t found "png.h" file.
![Captura de Pantalla 2022-04-12 a las 1 47 14](https://user-images.githubusercontent.com/103385292/162856791-ae752690-12d5-4761-b87d-b4ec1be1d67f.png)

and, I try to do this;
(https://github.com/simonfuhrmann/mve#building-mve-and-umve)
but when I try put this command; "make -j8", I get an error, like this. It said; "error: couldn`t determinate host endianess!
![Captura de Pantalla 2022-04-12 a las 1 54 44](https://user-images.githubusercontent.com/103385292/162857108-6d922a42-5d3a-4fef-a8cf-8cbca823e09a.png)

Finally, I try to found the file with this command; sudo find / -name png.h
And I get this; 
![Captura de Pantalla 2022-04-12 a las 2 46 32](https://user-images.githubusercontent.com/103385292/162857245-5a719b7f-6158-4d31-92dc-134a6c2af855.png)

I think that I need to create the file png.h. But I don´t know where is the correct place.

**Comment by dectun** [comment]
Hello. I need your help. Because I need to install MVE for a paleontologic proyecto of University of Extremadura. Please, do you help me?

**Comment by simonfuhrmann** [comment]
Please install the required libraries, libpng, libjpeg and libtiff, to resolve the first issue. This is documented here:
https://github.com/simonfuhrmann/mve#building-mve-and-umve

To resolve the second issue, please try adding `|| defined(__arm__)` to the end of this line:
https://github.com/simonfuhrmann/mve/blob/b9eba7e26f5c132a74c14cdd06dd1d6c948c374b/libs/util/system.h#L149

**Comment by simonfuhrmann** [comment]
Have you tried removing the `-march` option altogether?

**Comment by dectun** [comment]
Hello. good afternoon from Spain.

In the first time I need to say you and the other maintainer, developer, GO, admin, ...that you are helping me. VERY MUCH THANKS FOR ALL.

I read the link. And I understand this; the option -march:native not is very important to work MVE. Only this is important to optimice the compiler of code.

But I don`t know what is the way to remove this option.

And Since yesterday I´m thinking if is necessary defined the both in BE. And if I can change the command "(__arm__)" or "(__aarch64__) to the line 147 in the file systmen.h . 
What do you think about this? is it possible? is it dangerous?  it is not right?....
![Captura de Pantalla 2022-04-13 a las 3 51 49](https://user-images.githubusercontent.com/103385292/163245181-cf74c2c0-f8b3-4245-b4cf-64a8e7b803d4.png)
![Captura de Pantalla 2022-04-13 a las 8 42 44](https://user-images.githubusercontent.com/103385292/163245197-abe18eb0-ede9-42bd-a8eb-1521e818a051.png)

**Comment by simonfuhrmann** [comment]
I am pretty sure the M1 is a little endian CPU, so it should be on the same line as i386. Specifying the wrong LE/BE is not dangerous, but you'll probably run into weird issues and fundamentally, the software won't work.

**Comment by simonfuhrmann** [comment]
Closing this for now.

**Comment by simonfuhrmann** [comment]
The endian issue should be fixed for M1 processors with 354a652461377939ca136f451ba3271a1c52ee65.
