### ISSUE TITLE
Problem in build MVE

### ISSUE THREAD

**Issue by dectun** [simonfuhrmann/mve#559]
Hello. I can`t install MVE. I go to explain all events that i did.

In the first, I needed uninstall the MVE directory. And then I gone to clone step. I will put all steps whit a screenshot. So sorry, but I am user only, and very much thanks for your helps.

The clone step was well. And then when I try to use "make -j8" command return me an error with the "-march=native"

![Captura de Pantalla 2022-04-14 a las 22 28 35](https://user-images.githubusercontent.com/103385292/163470529-5d5b7437-23a1-4cf2-8bd8-c54b74886372.png)

I go to the makefile.inc and change the code to "-mcpu=apple-m1"

![Captura de Pantalla 2022-04-14 a las 22 31 40](https://user-images.githubusercontent.com/103385292/163470709-07446a94-3388-44ef-aaec-f6be472ffc1a.png)

And then i apply the ISSUE 533 (of this chat). And return me this.

![Captura de Pantalla 2022-04-14 a las 22 33 04](https://user-images.githubusercontent.com/103385292/163470893-755f54da-2f0c-4743-ae0f-cdf3bf8a5285.png)

Now the error that the machine return me is; "fatal error: 'png.h' file not found". And i apply the change code "elif to else", in the system.h on line 149. And the machine return me the same error with different sentences.

![Captura de Pantalla 2022-04-14 a las 22 35 43](https://user-images.githubusercontent.com/103385292/163471231-48068db2-1b6d-41da-83ee-e3c07d4575b5.png)

When I apply "brew doctor" the system say that is ready. 

![Captura de Pantalla 2022-04-14 a las 22 36 41](https://user-images.githubusercontent.com/103385292/163471424-5c3c04a9-ba4a-4d18-a67e-3467319f4552.png)

Actually,  I install the GCC package recently.

**Comment by simonfuhrmann** [comment]
You have to install the png, jpeg and tiff libraries. You can't hack your way around it, otherwise the program won't be able to read any images.

I can't really tell you how, but something like `brew install libpng` etc. should work. Maybe the package is called differently.

**Comment by dectun** [comment]
It say me that are install all. I use the command; "brew install git libpng jpeg libtiff qt@5"

![Captura de Pantalla 2022-04-15 a las 0 28 19](https://user-images.githubusercontent.com/103385292/163488429-1ed53930-8b08-4c8b-ba77-96cdea7e1144.png)
.

**Comment by simonfuhrmann** [comment]
Yeah, that's odd, then your homebrew setup may not be working correctly. Or you're missing some environment variables... Sorry mate, I'm not familiar with that system.

**Comment by dectun** [comment]
Ok, thanks. 

What do you think about this? I will uninstall homebrew and reinstall macports.

Is homebrew necessary for MVE?.

**Comment by simonfuhrmann** [comment]
MVE only cares about a compiler, make, and a few libraries.

**Comment by SMillerDev** [comment]
You likely didn't set the variables defined in https://github.com/simonfuhrmann/mve/wiki/Build-Instructions-for-OS-X#for-apple-m1-chip-users or you restarted your terminal after you did.

**Comment by dectun** [comment]
hello. I try to apply the variable commands, like this;

![Captura de Pantalla 2022-04-15 a las 9 18 22](https://user-images.githubusercontent.com/103385292/163538318-d33c3ba6-4ff8-4518-a789-4d3e2d714c15.png)

It return me this:

![Captura de Pantalla 2022-04-15 a las 9 16 18](https://user-images.githubusercontent.com/103385292/163538397-7ebd44f8-834d-4278-b786-43a8a51a8ea8.png)
![Captura de Pantalla 2022-04-15 a las 9 16 40](https://user-images.githubusercontent.com/103385292/163538423-f7e46cf7-bb6b-41d6-8c61-6442c1ea94e3.png)
![Captura de Pantalla 2022-04-15 a las 9 16 57](https://user-images.githubusercontent.com/103385292/163538436-e1585f53-f655-410d-af96-ed381ac389cb.png)


And then I try to apply this; "brew link --force qt@5". Because I think the reinstall stoped this. And it say this:
![Captura de Pantalla 2022-04-15 a las 9 17 09](https://user-images.githubusercontent.com/103385292/163538636-1c31c98a-cd3f-4de9-8216-ed32ba2f15d9.png)
