### ISSUE TITLE
Cannot stat path of directory + No such file or directory

### ISSUE THREAD

**Issue by jhaggle** [simonfuhrmann/mve#561]
I have been running makescene several time and it has worked fine. 

However, I needed to move the all images to another location and run from there.
When I try to run _mve.makescene -i input_folder out_scene_ from the new location, I get “cannot stat path of the current working directory: Permission denied”.

When running _mve.makescene -i input_folder out_scene_ from my home location I get 
“Error scanning input dir: Cannot open directory: No such file or directory”
However the directory exists, and the command _ls input_folder_ gives a list of the images in the folder.

Nothing of the above changes with sudo and all files and folders are rxw for all users.
NOTE: The above applies to mve downloaded using "snap install mve". However it works fine when installing snap from source.
That is however not an option for ubuntu18, it only works to install on ubuntu20 - and I need to use ubuntu18?

Any ideas what this depens on and how it can be solved?

**Comment by simonfuhrmann** [comment]
I do not know what causes this. And since you mentioned it works fine when installing from source on Ubuntu 20, can you just try to compile MVE yourself on Ubuntu 18 and see if that solves the problem too?

**Comment by jhaggle** [comment]
Ok thanks for the answer. It did not work to compile it on Ubuntu18, only on Ubuntu20 so I can not try that unfortunately.

**Comment by simonfuhrmann** [comment]
Why did it not work?
