### ISSUE TITLE
OpenMVG+MVE:  dmrecon: command not found

### ISSUE THREAD

**Issue by miroslavkuba** [simonfuhrmann/mve#564]
Hello, I tried to make a dense reconstruction from a sparse reconstruction of OpenMVG using the instruction from https://openmvg.readthedocs.io/en/latest/software/MVS/MVE/:

And when I used the instruction in the terminal (Ubuntu 22.04.1 LTS):
    Pavilion-dv7-Notebook-PC: ~/mve/apps/dmrecon$ dmrecon -s $resolution $directory
got an answer:
    dmrecon: command not found

When I tried to check command of instruction from MVE Users Guide, got follow:
    P-Pavilion-dv7-Notebook-PC:~/mve/apps/makescene$ makescene
    makescene: command not found
although the files dmrecon.exe and makescene.exe are present in /mve/apps/dmrecon and /mve/apps/makescene  folders respectively

why is it?

With regards,

**Comment by simonfuhrmann** [comment]
Did you try adding `./`, e.g., `./dmrecon`?

**Comment by miroslavkuba** [comment]
sorry for late
yes,  I  am had written already about it:     
    Pavilion-dv7-Notebook-PC:  ~/mve/apps/dmrecon$  dmrecon -s $resolution $directory
 
And here is information about how the dmrecon file is placed on the file system:
When I use the  ls command in the terminal, the dmrecon file is found in the package dmrecon:
    ***@***.***: ~/mve/apps/dmrecon $  ls     dmrecon      dmrecon.o                  fancy_progress_printer.h  Makefile  dmrecon.cc  fancy_progress_printer.cc  fancy_progress_printer.o  Makefile.dep
    ***@***.***: ~/mve/apps/dmrecon$
 
Here copy of instruction for using MVE after OpenMVG from https://openmvg.readthedocs.io/en/latest/software/MVS/MVE/:
 
With regards,
 
e-mail:  ***@***.***

**Comment by simonfuhrmann** [comment]
So, did you try adding `./`, e.g., `./dmrecon`?
