### ISSUE TITLE
Documentation lacks explanation

### ISSUE THREAD

**Issue by vonqo** [simonfuhrmann/mve#566]
Seems documentation is pretty out of date. I've noticed few deprecated links like ```http://qt.nokia.com```. And the reconstruction pipeline section is quite unclear about application order.

**Comment by simonfuhrmann** [comment]
I removed the Qt link. Their website is not very helpful anyways.

What exactly is unclear about the [reconstruction pipeline](https://github.com/simonfuhrmann/mve/wiki/MVE-Users-Guide#the-reconstruction-pipeline)?

Application order is top to bottom. Can you be a bit more specific about the confusion, so it can be improved? Also note, it's a Wiki. Feel free to just edit it to make improvements.
