### ISSUE TITLE
How can I compile MVS-Texturing?

### ISSUE THREAD

**Issue by wujiale123** [simonfuhrmann/mve#567]
Hello, thank you for open-sourcing MVE and providing the source code.
I want to use texrecon under Windows, but I can't compile the code and run the program, and I can't find the corresponding README. I don't know how to solve this problem.
I would really appreciate it if you take the time to help me out!

**Comment by simonfuhrmann** [comment]
Hi, there is a section in the users guide for compiling on Windows. 
https://github.com/simonfuhrmann/mve/wiki/Build-Instructions-for-Windows

But it's probably outdated, and Windows is generally unsupported.
I really can't help you with any specific issues. I hope this helps though.
