### ISSUE TITLE
Get all visible 3D feature points for a specific image.

### ISSUE THREAD

**Issue by lowerfain** [simonfuhrmann/mve#568]
Hello, I want to get all visible 3D feature points corresponding to a certain image. Is there a related method in sfmrecon or dmrecon?
Looking forward to your reply, thanks.

**Comment by simonfuhrmann** [comment]
Hello! You can read the bundle with the class here: libs/mve/bundle_io.h
Then you can use the `Bundle` instance it returns, iterate over all features (`Bundle::get_features()`) and use the method `Feature3D::contains_view_id()` to filter only the features for a specific view.

I hope this helps!

**Comment by lowerfain** [comment]
> Hello! You can read the bundle with the class here: libs/mve/bundle_io.h Then you can use the `Bundle` instance it returns, iterate over all features (`Bundle::get_features()`) and use the method `Feature3D::contains_view_id()` to filter only the features for a specific view.
> 
> I hope this helps!

Thanks for your suggestion, I got it.
But when I print the coordinates `Feature3D.pos` of each 3D feature point in the console, it shows as below.
Are these normalized or otherwise processed coordinates? I want to get their coordinates in the world coordinate system, do you have any suggestion for this?
![1](https://github.com/simonfuhrmann/mve/assets/35126772/77071214-596d-4362-b58a-d305f97fa5ad)

**Comment by simonfuhrmann** [comment]
Please define "world coordinate system". All points are in a consistent world coordinate system. But yes, at some point in the process there is some arbitrary choice that sets a scale for that coordinate system. Some bundlers set the position of the initial camera pair, which then pretty much defines the world coordinate system. MVE may do some additional scaling after SfM.

**Comment by lowerfain** [comment]
thx,

- I want to display all 3D feature points and all camera positions.

- Moreover, all visible feature points of a certain view `i` can also be displayed separately.As shown in the figure, as shown by visualSfM, the visibility distribution of the red feature points under the marked image represents the views.

Could you give me some advice?
![2](https://github.com/simonfuhrmann/mve/assets/35126772/8ab4097d-72ca-42e6-8316-6a67fea5d5f6)

**Comment by simonfuhrmann** [comment]
UMVE, the UI that accompanies MVE, doesn't support that directly. And the one thing you can do is write some code that does what I suggested above, and you apparently already go working. Then you can write these per-camera point clouds to individual meshes (e.g., create a mesh `libs/mve/mesh.h` and write it using `libs/mve/mesh_io.h`). You can even load these meshes as layers in UMVE and toggle them on/off.

**Comment by lowerfain** [comment]
I am not using UMVE now, I plan to implement it in `apps/bundle2pset`, do you think this is feasible?

**Comment by simonfuhrmann** [comment]
Yeah, that is definitely feasible.
