### ISSUE TITLE
a way to make the output into gltf/glb instead of PLY. 

### ISSUE THREAD

**Issue by Moaaz10** [simonfuhrmann/mve#571]
I need my files to have gltf/glb format. is there an option to change the format of the output? and if not do you know somewhere good to convert the files? (I am new to 3d modeling :) )

**Comment by simonfuhrmann** [comment]
Sorry for the late response. MVE doesn't support this format. You can implement it in `libs/mve/mesh_io_*`. Or you have to find another converter. MVE stores a bunch of per-vertex attributes (scale, color, etc.), so make sure it supports what you need.

**Comment by Moaaz10** [comment]
Alright Thank you!
